/**
 * GitHub shipping — creates one private repository per exported bot and
 * pushes its bundle files via the Contents API (one commit per file; fine at
 * this scale, and it keeps the deploy trail readable on GitHub's UI).
 *
 * Auth: a classic PAT in GITHUB_TOKEN (repo scope). GITHUB_OWNER optionally
 * pins the target account; otherwise the token owner is resolved once.
 */
import { Buffer } from 'node:buffer';
import { ApiError } from '../middleware/errorHandler.js';

const GH_API = 'https://api.github.com';
const UA = 'scarlet-chatbot-factory';

function creds() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new ApiError(503, 'GitHub is not configured — add GITHUB_TOKEN (a personal access token with repo scope) to the Factory .env file.');
  }
  return token;
}

async function gh(path, { method = 'GET', body } = {}) {
  const res = await fetch(`${GH_API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${creds()}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': UA,
      ...(body ? { 'Content-Type': 'application/json' } : {}),
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  if (res.status === 204) return null;
  const json = await res.json().catch(() => ({}));
  if (!res.ok) {
    const err = new Error(`github_call_failed_${path.split('?')[0]}_${res.status}`);
    err.status = res.status;
    err.ghBody = json;
    throw err;
  }
  return json;
}

/** Turn raw GitHub fetch failures into friendly, secret-free ApiErrors. */
function translate(err, message) {
  if (err instanceof ApiError) return err;
  if (err.status === 401) return new ApiError(503, 'GitHub rejected the token — check GITHUB_TOKEN in .env.');
  if (err.status === 403) return new ApiError(503, 'GitHub denied the request — the token may be rate-limited or missing the repo scope.');
  return new ApiError(502, message);
}

async function resolveOwner() {
  const envOwner = String(process.env.GITHUB_OWNER || '').trim();
  if (envOwner) return envOwner;
  const me = await gh('/user');
  return me.login;
}

const suffixed = (name) => `${name}-${Math.random().toString(36).slice(2, 6)}`;

function repoResult(owner, repo, created) {
  return { owner, repo, fullName: `${owner}/${repo}`, url: `https://github.com/${owner}/${repo}`, created };
}

/**
 * Ensure a repo named `wanted` exists (private). Reuses an existing repo
 * (so re-shipping updates in place); on a name conflict creates with a
 * suffix. Returns { owner, repo, fullName, url, created }.
 */
export async function ensureRepo({ name, description }) {
  creds();
  const owner = await resolveOwner();
  let candidate = name;

  for (let attempt = 0; attempt < 3; attempt += 1) {
    try {
      const existing = await gh(`/repos/${owner}/${candidate}`);
      return repoResult(owner, existing.name || candidate, false);
    } catch (err) {
      if (err.status !== 404) throw translate(err, 'GitHub could not look up that repository. Please retry.');
    }
    try {
      await gh('/user/repos', {
        method: 'POST',
        body: {
          name: candidate,
          private: true,
          description: description || 'Standalone chatbot generated by the Scarlet Chatbot Factory.',
          auto_init: false,
        },
      });
      return repoResult(owner, candidate, true);
    } catch (err) {
      const msg = String(err.ghBody?.errors?.[0]?.message || err.ghBody?.message || '').toLowerCase();
      if (err.status === 422 && msg.includes('already exists')) { candidate = suffixed(name); continue; }
      throw translate(err, 'GitHub could not create the repository right now. Please retry in a moment.');
    }
  }
  throw new ApiError(502, 'GitHub could not find a free repository name after several attempts — retry shipping.');
}

/**
 * Push { path: content } into the repo. Existing files are updated in place
 * via their blob sha, so re-ships do not duplicate history noise.
 */
export async function pushRepoFiles({ owner, repo }, files) {
  const repoInfo = await gh(`/repos/${owner}/${repo}`).catch(() => {
    throw new ApiError(502, 'The repository disappeared mid-ship — retry.');
  });
  const defaultBranch = repoInfo.default_branch || 'main';

  for (const [p, content] of Object.entries(files)) {
    const endpoint = `/repos/${owner}/${repo}/contents/${encodeURI(p)}`;
    let sha;
    try {
      const info = await gh(endpoint);
      if (info?.sha) sha = info.sha;
    } catch (err) {
      if (err.status !== 404) throw translate(err, 'GitHub could not read an existing file — retry.');
    }
    try {
      await gh(endpoint, {
        method: 'PUT',
        body: {
          message: `Scarlet Factory: ship ${p}`,
          content: Buffer.from(content, 'utf8').toString('base64'),
          branch: defaultBranch,
          ...(sha ? { sha } : {}),
        },
      });
    } catch (err) {
      throw translate(err, 'GitHub could not push file contents — retry.');
    }
  }
}

/**
 * Permanently delete a repo. 404 counts as success (already gone) so the
 * unpublish flow stays idempotent and retry-safe.
 */
export async function deleteRepo(owner, repo) {
  const path = `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`;
  try {
    await gh(path, { method: 'DELETE' });
    return { deleted: true };
  } catch (err) {
    if (err.status === 404) return { deleted: false, alreadyGone: true };
    if (err.status === 403 && /rate limit|secondary/i.test(String(err.message))) {
      throw new ApiError(429, 'GitHub rate limit hit while deleting the repo — the batch will retry automatically.');
    }
    if (err.status === 401) throw new ApiError(503, 'GitHub rejected the API key (token revoked?) — regenerate it under GitHub → Settings → Developer settings → Fine-grained tokens, update GITHUB_TOKEN in the backend .env, then retry.');
    throw new ApiError(502, `GitHub could not delete ${owner}/${repo} — check the token has Administration permission on the repo.`);
  }
}
