// ============================================================
// SCARLET DOMAIN KNOWLEDGE — PART 10
// ============================================================

export const DOMAIN_PART10 = {
  'Real Estate': {
    themes: ['Royal', 'Slate', 'Mono'],
    specialties: {
      Buying: {
        expertise: ['buying a home', 'mortgages', 'negotiation', 'closing', 'inspections'],
        welcome: 'Home buying question? Ask about the process, financing, or closing.',
        allowed: ['buying', 'buy', 'home buying', 'house', 'mortgage', 'pre-approval', 'down payment', 'offer', 'negotiation', 'closing', 'title', 'inspection', 'appraisal', 'escrow', 'realtor', 'closing costs'],
        related: ['real estate', 'finance', 'home'],
        synonyms: ['purchasing property', 'home purchase'],
        intents: ['understanding the process', 'getting a mortgage', 'negotiating'],
        starters: ['How do I buy my first home?', 'How much down payment do I need?', 'What are closing costs?', 'How do I negotiate an offer?'],
        disclaimer: true,
      },
      Selling: {
        expertise: ['selling a home', 'pricing', 'listing', 'staging', 'negotiation'],
        welcome: 'Home selling question? Ask about pricing, staging, or negotiation.',
        allowed: ['selling', 'sell', 'home selling', 'listing', 'price', 'pricing', 'agent', 'staging', 'home staging', 'open house', 'offer', 'counteroffer', 'appraisal', 'disclosure', 'closing'],
        related: ['real estate', 'finance', 'home'],
        synonyms: ['listing a home', 'property selling'],
        intents: ['pricing a home', 'staging', 'negotiating'],
        starters: ['How do I price my home?', 'What is home staging?', 'Should I sell with an agent?', 'How do I handle multiple offers?'],
        disclaimer: true,
      },
      Renting: {
        expertise: ['renting', 'leases', 'tenants', 'landlords', 'rental market'],
        welcome: 'Renting question? Ask about leases, rights, or the market.',
        allowed: ['renting', 'rent', 'lease', 'tenant', 'landlord', 'security deposit', 'application', 'credit check', 'sublet', 'eviction', 'notice', 'utilities', 'roommate', 'rental market', 'lease agreement'],
        related: ['real estate', 'law', 'finance'],
        synonyms: ['leasing', 'rental housing'],
        intents: ['understanding leases', 'finding rentals', 'knowing rights'],
        starters: ['What should I look for in a lease?', 'How much rent can I afford?', 'What are tenant rights?', 'How do I get my security deposit back?'],
        disclaimer: true,
      },
      'Property Management': {
        expertise: ['property management', 'landlords', 'maintenance', 'tenants', 'operations'],
        welcome: 'Property management question? Ask about tenants, maintenance, or operations.',
        allowed: ['property management', 'property manager', 'landlord', 'tenant', 'maintenance', 'repair', 'rent collection', 'eviction', 'inspection', 'turnover', 'lease', 'emergency', 'accounting'],
        related: ['real estate', 'business', 'home'],
        synonyms: ['estate management'],
        intents: ['managing properties', 'handling maintenance', 'dealing with tenants'],
        starters: ['How do I screen tenants?', 'How do I handle maintenance requests?', 'What is property turnover?', 'How do I manage rent collection?'],
      },
      Commercial: {
        expertise: ['commercial real estate', 'offices', 'retail', 'leases', 'investment'],
        welcome: 'Commercial real estate question? Ask about offices, retail, or leases.',
        allowed: ['commercial real estate', 'commercial', 'office', 'retail', 'industrial', 'lease', 'nnn', 'gross lease', 'cap rate', 'zoning', 'foot traffic', 'tenant improvement', 'building', 'investment'],
        related: ['real estate', 'business', 'finance'],
        synonyms: ['cre', 'commercial property'],
        intents: ['leasing commercial space', 'investing in commercial', 'understanding cap rates'],
        starters: ['What is a NNN lease?', 'How do I value commercial property?', 'What is a cap rate?', 'Retail vs office vs industrial real estate?'],
        disclaimer: true,
      },
      Residential: {
        expertise: ['residential real estate', 'homes', 'neighborhoods', 'market', 'appreciation'],
        welcome: 'Residential real estate question? Ask about markets, homes, or neighborhoods.',
        allowed: ['residential', 'house', 'home', 'condo', 'apartment', 'townhouse', 'neighborhood', 'market', 'appreciation', 'comparables', 'zillow', 'listing', 'equity', 'renovation value'],
        related: ['real estate', 'home', 'finance'],
        synonyms: ['housing market', 'residential property'],
        intents: ['understanding markets', 'comparing homes', 'estimating value'],
        starters: ['How do I estimate a home value?', 'What is a buyer vs seller market?', 'Condo vs house — which is better?', 'What is home equity?'],
        disclaimer: true,
      },
      Investment: {
        expertise: ['real estate investing', 'rentals', 'flipping', 'reits', 'metrics'],
        welcome: 'Real estate investing question? Ask about rentals, flipping, or REITs.',
        allowed: ['real estate investing', 'investing', 'rental property', 'flip', 'flipping', 'reit', 'cap rate', 'cash flow', 'appreciation', 'leverage', 'mortgage', 'tax', '1031', 'airbnb', 'house hacking'],
        related: ['real estate', 'finance', 'investing'],
        synonyms: ['property investing', 'realty investing'],
        intents: ['analyzing deals', 'building a portfolio', 'understanding metrics'],
        starters: ['How do I analyze a rental property?', 'What is the BRRRR strategy?', 'REITs vs physical real estate?', 'How do I start house hacking?'],
        disclaimer: true,
      },
      Appraisal: {
        expertise: ['appraisal', 'valuation', 'comparables', 'reports', 'regulations'],
        welcome: 'Appraisal question? Ask about valuation, comparables, or reports.',
        allowed: ['appraisal', 'appraiser', 'valuation', 'value', 'comparables', 'comps', 'report', 'adjustment', 'income approach', 'cost approach', 'market approach', 'regulated', 'license'],
        related: ['real estate', 'finance', 'law'],
        synonyms: ['property valuation', 'assessment'],
        intents: ['understanding appraisals', 'preparing a home', 'challenging a value'],
        starters: ['How does an appraisal work?', 'How are comparables chosen?', 'What are the three approaches to value?', 'Can I challenge an appraisal?'],
        disclaimer: true,
      },
      Mortgage: {
        expertise: ['mortgages', 'rates', 'loans', 'refinancing', 'qualification'],
        welcome: 'Mortgage question? Ask about rates, loans, or refinancing.',
        allowed: ['mortgage', 'mortgages', 'loan', 'rate', 'interest rate', 'fixed rate', 'adjustable', 'arm', 'refinance', 'refinancing', 'pre-approval', 'fha', 'va', 'conventional', 'amortization', 'pmi'],
        related: ['real estate', 'finance', 'banking'],
        synonyms: ['home loan', 'mortgage loan'],
        intents: ['getting pre-approved', 'comparing rates', 'refinancing'],
        starters: ['What is the difference between fixed and adjustable rates?', 'How do I get pre-approved?', 'When should I refinance?', 'What is PMI?'],
        disclaimer: true,
      },
      'Land Development': {
        expertise: ['land development', 'zoning', 'subdivision', 'infrastructure', 'permits'],
        welcome: 'Land development question? Ask about zoning, subdivision, or permits.',
        allowed: ['land development', 'land', 'development', 'zoning', 'subdivision', 'plat', 'permit', 'infrastructure', 'utilities', 'environmental', 'survey', 'grading', 'entitlement', 'density', 'lot'],
        related: ['real estate', 'construction', 'urban planning'],
        synonyms: ['site development', 'real estate development'],
        intents: ['understanding zoning', 'planning a subdivision', 'getting permits'],
        starters: ['What is land entitlement?', 'How do I subdivide a parcel?', 'What does zoning determine?', 'What are the steps to develop land?'],
        disclaimer: true,
      },
    },
  },

  Retail: {
    themes: ['Sunset', 'Royal', 'Mono'],
    specialties: {
      'E-commerce': {
        expertise: ['ecommerce', 'stores', 'conversion', 'checkout', 'platforms'],
        welcome: 'E-commerce question? Ask about stores, conversion, or platforms.',
        allowed: ['ecommerce', 'e-commerce', 'online store', 'shopify', 'amazon', 'walmart', 'checkout', 'cart', 'conversion', 'product page', 'listing', 'shipping', 'returns', 'review', 'marketplace', 'dropshipping'],
        related: ['retail', 'marketing', 'technology'],
        synonyms: ['online retail', 'digital commerce'],
        intents: ['starting a store', 'improving conversion', 'choosing a platform'],
        starters: ['How do I start an online store?', 'Shopify vs Amazon — which is better?', 'How do I improve checkout conversion?', 'What is dropshipping?'],
      },
      'Visual Merchandising': {
        expertise: ['visual merchandising', 'displays', 'windows', 'layout', 'storytelling'],
        welcome: 'Visual merchandising question? Ask about displays, windows, or layout.',
        allowed: ['visual merchandising', 'display', 'displays', 'window', 'mannequin', 'fixture', 'layout', 'floor plan', 'planogram', 'color blocking', 'focal', 'signage', 'props', 'lighting', 'story'],
        related: ['retail', 'design', 'marketing'],
        synonyms: ['merchandising', 'retail display'],
        intents: ['creating displays', 'designing windows', 'planning layouts'],
        starters: ['How do I create an effective window display?', 'What is a planogram?', 'How do I merchandise a shelf?', 'What is retail storytelling?'],
      },
      'Customer Experience': {
        expertise: ['customer experience', 'service', 'journey', 'loyalty', 'feedback'],
        welcome: 'Retail customer experience question? Ask about service, journey, or loyalty.',
        allowed: ['customer experience', 'customer', 'experience', 'journey', 'service', 'satisfaction', 'loyalty', 'program', 'feedback', 'nps', 'csat', 'returns', 'queue', 'staff', 'personalization'],
        related: ['retail', 'marketing', 'service'],
        synonyms: ['cx', 'shopping experience'],
        intents: ['improving service', 'mapping journeys', 'building loyalty'],
        starters: ['How do I improve the customer journey?', 'How do I measure NPS?', 'What makes great retail service?', 'How do I build a loyalty program?'],
      },
      Inventory: {
        expertise: ['retail inventory', 'stock', 'replenishment', 'shrinkage', 'turns'],
        welcome: 'Retail inventory question? Ask about stock, replenishment, or shrinkage.',
        allowed: ['retail inventory', 'inventory', 'stock', 'sku', 'replenishment', 'reorder', 'shrinkage', 'theft', 'turns', 'turnover', 'planogram', 'safety stock', 'markdown', 'overstock', 'backorder'],
        related: ['retail', 'logistics', 'operations'],
        synonyms: ['stock management', 'merchandise'],
        intents: ['managing stock', 'reducing shrinkage', 'optimizing turns'],
        starters: ['How do I reduce inventory shrinkage?', 'What is inventory turnover?', 'How do I manage stockouts?', 'How do I handle overstock?'],
      },
      Pricing: {
        expertise: ['retail pricing', 'strategy', 'markdowns', 'promotions', 'psychology'],
        welcome: 'Retail pricing question? Ask about strategy, markdowns, or promotions.',
        allowed: ['retail pricing', 'pricing', 'price', 'markup', 'margin', 'markdown', 'promotion', 'discount', 'bundle', 'anchoring', 'psychological pricing', 'price elasticity', 'competitor', 'sale'],
        related: ['retail', 'business', 'marketing'],
        synonyms: ['price strategy', 'merchandise pricing'],
        intents: ['setting prices', 'planning markdowns', 'running promotions'],
        starters: ['How do I price my products?', 'What is psychological pricing?', 'How do I plan markdowns?', 'What is price anchoring?'],
      },
      'Loss Prevention': {
        expertise: ['loss prevention', 'theft', 'shrinkage', 'security', 'audits'],
        welcome: 'Loss prevention question? Ask about theft, shrinkage, or security.',
        allowed: ['loss prevention', 'theft', 'shoplifting', 'shrinkage', 'security', 'camera', 'cctv', 'tags', 'alarm', 'audit', 'employee theft', 'fraud', 'returns fraud', 'deterrence', 'apprehension'],
        related: ['retail', 'security', 'operations'],
        synonyms: ['shrink control', 'asset protection'],
        intents: ['reducing theft', 'implementing security', 'running audits'],
        starters: ['How do I reduce shoplifting?', 'What are the most common retail frauds?', 'How do I train staff for loss prevention?', 'What is a shrinkage audit?'],
      },
      Omnichannel: {
        expertise: ['omnichannel', 'channels', 'bopis', 'unified commerce', 'integration'],
        welcome: 'Omnichannel question? Ask about channels, bopis, or integration.',
        allowed: ['omnichannel', 'omnichannel', 'channel', 'bopis', 'buy online pickup', 'click and collect', 'ship from store', 'unified commerce', 'integration', 'catalog', 'order management', 'oms', 'curbside', 'digital'],
        related: ['retail', 'ecommerce', 'operations'],
        synonyms: ['unified commerce', 'multi-channel'],
        intents: ['integrating channels', 'implementing bopis', 'managing orders'],
        starters: ['What is omnichannel retail?', 'How do I implement BOPIS?', 'What is an OMS?', 'How do I unify online and offline?'],
      },
      'Retail Tech': {
        expertise: ['retail technology', 'pos', 'rfid', 'ai', 'self-checkout'],
        welcome: 'Retail tech question? Ask about POS, RFID, or automation.',
        allowed: ['retail tech', 'retail technology', 'pos', 'point of sale', 'rfid', 'barcode', 'self-checkout', 'self check-out', 'ai', 'computer vision', 'shelf sensors', 'smart shelf', 'cashless', 'mobile wallet', 'loyalty app', 'inventory system'],
        related: ['retail', 'technology', 'operations'],
        synonyms: ['store tech', 'retail innovation'],
        intents: ['choosing pos', 'implementing rfid', 'using ai'],
        starters: ['How do I choose a POS system?', 'What is RFID in retail?', 'How is AI used in retail?', 'Are self-checkouts worth it?'],
      },
      'Category Management': {
        expertise: ['category management', 'assortment', 'planning', 'vendor', 'performance'],
        welcome: 'Category management question? Ask about assortment, planning, or vendors.',
        allowed: ['category management', 'category', 'assortment', 'planning', 'vendor', 'supplier', 'planogram', 'shelf space', 'performance', 'scorecard', 'market share', 'growth', 'gap analysis'],
        related: ['retail', 'marketing', 'supply chain'],
        synonyms: ['assortment planning', 'category planning'],
        intents: ['planning assortments', 'managing vendors', 'analyzing performance'],
        starters: ['What is category management?', 'How do I build an assortment?', 'How do I manage vendors?', 'What is a category captain?'],
      },
      'Visual Display': {
        expertise: ['visual display', 'mannequins', 'props', 'signage', 'window'],
        welcome: 'Visual display question? Ask about mannequins, windows, or props.',
        allowed: ['visual display', 'display', 'mannequin', 'form', 'prop', 'signage', 'window display', 'tables', 'feature', 'lighting', 'color', 'theme', 'rigging', 'costume'],
        related: ['retail', 'design', 'art'],
        synonyms: ['display design', 'retail display'],
        intents: ['dressing mannequins', 'designing windows', 'using props'],
        starters: ['How do I dress a mannequin?', 'What makes a great window display?', 'How do I use lighting in displays?', 'How do I theme a seasonal display?'],
      },
    },
  },

  Security: {
    themes: ['Midnight', 'Crimson', 'Mono'],
    specialties: {
      'Physical Security': {
        expertise: ['physical security', 'access', 'perimeter', 'guards', 'systems'],
        welcome: 'Physical security question? Ask about access, perimeter, or guards.',
        allowed: ['physical security', 'security', 'access control', 'perimeter', 'fence', 'gate', 'guard', 'patrol', 'badge', 'turnstile', 'mantrap', 'locks', 'safes', 'alarm', 'lighting'],
        related: ['security', 'construction', 'operations'],
        synonyms: ['site security', 'premises security'],
        intents: ['securing a facility', 'planning access', 'hiring guards'],
        starters: ['How do I secure a facility?', 'What is access control?', 'How do I choose security guards?', 'What is a mantrap?'],
      },
      Cybersecurity: {
        expertise: ['cybersecurity', 'threats', 'defense', 'network', 'incident response'],
        welcome: 'Cybersecurity question? Ask about threats, defense, or response.',
        allowed: ['cybersecurity', 'cyber', 'security', 'malware', 'ransomware', 'phishing', 'firewall', 'ids', 'siem', 'vulnerability', 'penetration', 'pentest', 'incident response', 'zero trust', 'soc', 'threat'],
        related: ['security', 'technology', 'network'],
        synonyms: ['infosec', 'information security'],
        intents: ['protecting a network', 'responding to incidents', 'understanding threats'],
        starters: ['What is a penetration test?', 'How do I build a security operations center?', 'What is zero trust?', 'How do I respond to a ransomware attack?'],
      },
      Surveillance: {
        expertise: ['surveillance', 'cctv', 'cameras', 'monitoring', 'analysis'],
        welcome: 'Surveillance question? Ask about cameras, monitoring, or systems.',
        allowed: ['surveillance', 'cctv', 'camera', 'cameras', 'ip camera', 'analog', 'recorder', 'nvr', 'dvr', 'monitoring', 'video analytics', 'license plate', 'lpr', 'facial', 'storage', 'tampering'],
        related: ['security', 'technology', 'operations'],
        synonyms: ['video surveillance', 'monitoring'],
        intents: ['choosing cameras', 'designing coverage', 'storing footage'],
        starters: ['How do I choose a security camera?', 'How do I design camera coverage?', 'What is video analytics?', 'How long should I keep footage?'],
      },
      'Access Control': {
        expertise: ['access control', 'badges', 'biometrics', 'cards', 'doors'],
        welcome: 'Access control question? Ask about badges, biometrics, or doors.',
        allowed: ['access control', 'access', 'badge', 'card', 'keycard', 'biometric', 'fingerprint', 'facial', 'proximity', 'reader', 'controller', 'door', 'lockset', 'magnetic', 'mullion', 'anti-passback'],
        related: ['security', 'technology', 'operations'],
        synonyms: ['entry control', 'access management'],
        intents: ['choosing a system', 'integrating doors', 'managing credentials'],
        starters: ['How do I choose an access control system?', 'Keycards vs biometrics?', 'What is anti-passback?', 'How do I manage user credentials?'],
      },
      'Risk Assessment': {
        expertise: ['risk assessment', 'threats', 'vulnerabilities', 'mitigation', 'reports'],
        welcome: 'Security risk assessment question? Ask about threats, mitigation, or reports.',
        allowed: ['risk assessment', 'risk', 'threat', 'vulnerability', 'asset', 'likelihood', 'impact', 'mitigation', 'controls', 'residual risk', 'assessment report', 'compliance', 'gap analysis'],
        related: ['security', 'business', 'management'],
        synonyms: ['security risk analysis', 'risk review'],
        intents: ['assessing risks', 'implementing controls', 'writing reports'],
        starters: ['How do I conduct a security risk assessment?', 'What is the difference between threat and vulnerability?', 'How do I prioritize risks?', 'What is a risk register?'],
      },
      'Emergency Preparedness': {
        expertise: ['emergency preparedness', 'plans', 'evacuation', 'response', 'drills'],
        welcome: 'Emergency preparedness question? Ask about plans, evacuation, or response.',
        allowed: ['emergency preparedness', 'emergency', 'plan', 'evacuation', 'shelter', 'response', 'drill', 'first aid', 'communication', 'continuity', 'bcdr', 'business continuity', 'disaster', 'assembly point'],
        related: ['security', 'safety', 'operations'],
        synonyms: ['emergency planning', 'disaster readiness'],
        intents: ['building plans', 'running drills', 'preparing responses'],
        starters: ['How do I write an emergency plan?', 'What goes in a disaster kit?', 'How do I run an evacuation drill?', 'What is business continuity?'],
      },
      'Security Systems': {
        expertise: ['security systems', 'alarms', 'sensors', 'integration', 'design'],
        welcome: 'Security systems question? Ask about alarms, sensors, or design.',
        allowed: ['security systems', 'alarm', 'alarms', 'sensor', 'motion', 'door contact', 'glass break', 'panic', 'panel', 'monitoring', 'integration', 'design', 'installation', 'zones', 'smart security'],
        related: ['security', 'technology', 'home'],
        synonyms: ['alarm systems', 'protection systems'],
        intents: ['designing systems', 'choosing sensors', 'integrating smart'],
        starters: ['How do I design a security system?', 'What sensors do I need?', 'How do I integrate smart home security?', 'How do alarm monitoring services work?'],
      },
      Investigation: {
        expertise: ['investigation', 'interviews', 'evidence', 'reports', 'casework'],
        welcome: 'Investigation question? Ask about interviews, evidence, or reports.',
        allowed: ['investigation', 'investigate', 'interview', 'evidence', 'witness', 'statement', 'photograph', 'document', 'report', 'chain of custody', 'background check', 'fraud investigation', 'case'],
        related: ['security', 'law', 'operations'],
        synonyms: ['private investigation', 'inquiry'],
        intents: ['conducting interviews', 'preserving evidence', 'writing reports'],
        starters: ['How do I conduct an investigation?', 'What is chain of custody?', 'How do I interview witnesses?', 'How do I write an investigation report?'],
        disclaimer: true,
      },
      Compliance: {
        expertise: ['compliance', 'regulations', 'audits', 'policies', 'standards'],
        welcome: 'Security compliance question? Ask about regulations, audits, or policies.',
        allowed: ['compliance', 'regulation', 'regulations', 'audit', 'policy', 'policies', 'standard', 'gdpr', 'hipaa', 'sox', 'iso 27001', 'nist', 'pci dss', 'training', 'reporting'],
        related: ['security', 'law', 'business'],
        synonyms: ['regulatory compliance', 'standards compliance'],
        intents: ['implementing standards', 'passing audits', 'writing policies'],
        starters: ['What is ISO 27001?', 'How do I become GDPR compliant?', 'What is a security audit?', 'What is PCI DSS?'],
        disclaimer: true,
      },
      'Threat Analysis': {
        expertise: ['threat analysis', 'threat intelligence', 'ttps', 'indicators', 'reports'],
        welcome: 'Threat analysis question? Ask about intelligence, ttps, or indicators.',
        allowed: ['threat analysis', 'threat', 'intelligence', 'tti', 'ttp', 'indicator', 'ioc', 'tactics', 'techniques', 'procedures', 'adversary', 'campaign', 'report', 'automation', 'detection'],
        related: ['security', 'technology', 'intelligence'],
        synonyms: ['threat intel', 'threat assessment'],
        intents: ['building intel', 'analyzing campaigns', 'writing reports'],
        starters: ['What is threat intelligence?', 'What are IoCs?', 'How do I build a threat intel program?', 'What is the cyber kill chain?'],
      },
    },
  },
};