// ============================================================
// SCARLET DOMAIN KNOWLEDGE — PART 4
// ============================================================

export const DOMAIN_PART4 = {
  'Social Media': {
    themes: ['Sunset', 'Crimson', 'Royal'],
    specialties: {
      Instagram: {
        expertise: ['instagram', 'reels', 'stories', 'engagement', 'growth'],
        welcome: 'Instagram question? Ask about reels, stories, or growth.',
        allowed: ['instagram', 'ig', 'reel', 'reels', 'story', 'stories', 'post', 'feed', 'hashtag', 'growth', 'engagement', 'like', 'follower', 'bio', 'highlight', 'igtv', 'algorithm', 'explore', 'dm'],
        related: ['social media', 'marketing', 'content'],
        synonyms: ['insta', 'gram'],
        intents: ['growing followers', 'creating reels', 'improving engagement'],
        starters: ['How do I grow on Instagram?', 'What makes a good reel?', 'How do hashtags work?', 'What is the Instagram algorithm?'],
      },
      YouTube: {
        expertise: ['youtube', 'videos', 'channels', 'monetization', 'growth'],
        welcome: 'YouTube question? Ask about videos, channels, or monetization.',
        allowed: ['youtube', 'yt', 'video', 'channel', 'subscriber', 'thumbnail', 'title', 'description', 'keyword', 'monetization', 'adsense', 'cpm', 'rpm', 'youtube shorts', 'studio', 'analytics', 'algorithm', 'upload'],
        related: ['social media', 'video', 'content'],
        synonyms: ['yt', 'tube'],
        intents: ['growing a channel', 'improving videos', 'getting monetized'],
        starters: ['How do I grow my YouTube channel?', 'What makes a good thumbnail?', 'How does YouTube monetization work?', 'What are YouTube Shorts?'],
      },
      TikTok: {
        expertise: ['tiktok', 'videos', 'trends', 'fyp', 'growth'],
        welcome: 'TikTok question? Ask about trends, fyp, or growth.',
        allowed: ['tiktok', 'tt', 'fyp', 'for you', 'trend', 'trends', 'sound', 'duet', 'stitch', 'video', 'edit', 'algorithm', 'viral', 'hashtag', 'challenge', 'tiktok shop', 'creator', 'live'],
        related: ['social media', 'video', 'content'],
        synonyms: ['tok', 'tik tok'],
        intents: ['going viral', 'growing followers', 'creating trends'],
        starters: ['How does the TikTok algorithm work?', 'How do I go viral on TikTok?', 'What are trending sounds?', 'How do I use TikTok for business?'],
      },
      LinkedIn: {
        expertise: ['linkedin', 'professional networking', 'content', 'recruiting', 'personal branding'],
        welcome: 'LinkedIn question? Ask about networking, content, or branding.',
        allowed: ['linkedin', 'linked in', 'profile', 'network', 'connect', 'post', 'article', 'job', 'recruit', 'personal brand', 'recommendation', 'endorsement', 'inmail', 'linkedin learning', 'headline', 'summary'],
        related: ['social media', 'business', 'career'],
        synonyms: ['link', 'professional network'],
        intents: ['optimizing a profile', 'building a network', 'creating content'],
        starters: ['How do I optimize my LinkedIn profile?', 'What should I post on LinkedIn?', 'How do I grow my network?', 'How do I use LinkedIn for job hunting?'],
      },
      'Twitter/X': {
        expertise: ['twitter', 'x', 'tweets', 'trends', 'engagement'],
        welcome: 'Twitter/X question? Ask about tweets, threads, or trends.',
        allowed: ['twitter', 'x', 'tweet', 'tweets', 'thread', 'retweet', 'quote', 'reply', 'like', 'trending', 'hashtag', 'list', 'moment', 'blue', 'verification', 'engagement', 'analytics', 'community'],
        related: ['social media', 'news', 'content'],
        synonyms: ['x', 'tweet'],
        intents: ['growing followers', 'writing threads', 'understanding trends'],
        starters: ['How do I write engaging tweets?', 'What is a Twitter thread?', 'How do I grow on Twitter/X?', 'How do I use Twitter for news?'],
      },
      'Content Creation': {
        expertise: ['content creation', 'planning', 'production', 'editing', 'branding'],
        welcome: 'Content creation question? Ask about planning, production, or editing.',
        allowed: ['content creation', 'content', 'creator', 'planning', 'calendar', 'production', 'editing', 'camera', 'lighting', 'script', 'voiceover', 'brand', 'niche', 'audience', 'collaboration', 'tools'],
        related: ['social media', 'marketing', 'media'],
        synonyms: ['creator economy', 'content making'],
        intents: ['planning content', 'improving production', 'growing an audience'],
        starters: ['How do I plan content for social media?', 'What equipment do I need for content creation?', 'How do I edit videos?', 'How do I find my niche?'],
      },
      'Community Management': {
        expertise: ['community management', 'engagement', 'moderation', 'growth', 'strategy'],
        welcome: 'Community management question? Ask about engagement, moderation, or growth.',
        allowed: ['community management', 'community', 'engagement', 'moderation', 'moderator', 'member', 'group', 'discord', 'slack', 'facebook group', 'comment', 'feedback', 'guidelines', 'event', 'growth', 'loyalty'],
        related: ['social media', 'marketing', 'service'],
        synonyms: ['cm', 'community building'],
        intents: ['building a community', 'moderation', 'increasing engagement'],
        starters: ['How do I build a community?', 'How do I handle moderation?', 'How do I engage members?', 'What is a community manager?'],
      },
      Analytics: {
        expertise: ['social media analytics', 'metrics', 'insights', 'reporting', 'tools'],
        welcome: 'Social media analytics question? Ask about metrics, insights, or tools.',
        allowed: ['social media analytics', 'analytics', 'metrics', 'insights', 'reach', 'impressions', 'engagement', 'click', 'conversion', 'report', 'dashboard', 'sprout', 'hootsuite', 'buffer', 'native analytics', 'benchmark'],
        related: ['social media', 'marketing', 'data'],
        synonyms: ['smm analytics', 'social metrics'],
        intents: ['measuring performance', 'reading insights', 'reporting results'],
        starters: ['What social media metrics matter?', 'How do I read Instagram insights?', 'What is the best analytics tool?', 'How do I report social media results?'],
      },
      Monetization: {
        expertise: ['monetization', 'ads', 'sponsorships', 'affiliate', 'products'],
        welcome: 'Social media monetization question? Ask about ads, sponsorships, or products.',
        allowed: ['monetization', 'monetize', 'ad', 'ads', 'sponsorship', 'sponsor', 'affiliate', 'link', 'product', 'merch', 'digital product', 'course', 'membership', 'patreon', 'blue', 'creator fund', 'payout'],
        related: ['social media', 'business', 'marketing'],
        synonyms: ['making money', 'creator revenue'],
        intents: ['making money', 'getting sponsorships', 'selling products'],
        starters: ['How do I make money on social media?', 'How do I get sponsorships?', 'What is affiliate marketing?', 'How do I sell digital products?'],
      },
      'Platform Strategy': {
        expertise: ['platform strategy', 'cross-platform', 'distribution', 'channel', 'strategy'],
        welcome: 'Platform strategy question? Ask about cross-platform, distribution, or strategy.',
        allowed: ['platform strategy', 'strategy', 'cross-platform', 'distribution', 'channel', 'algorithm', 'optimize', 'repurpose', 'schedule', 'multichannel', 'omni', 'strategy', 'niche', 'audience'],
        related: ['social media', 'marketing', 'business'],
        synonyms: ['social strategy', 'content strategy'],
        intents: ['building a strategy', 'choosing platforms', 'optimizing distribution'],
        starters: ['How do I choose the right platforms?', 'How do I cross-post effectively?', 'How do I adapt content per platform?', 'What is a social media strategy?'],
      },
    },
  },

  Teaching: {
    themes: ['Forest', 'Slate', 'Mono'],
    specialties: {
      'Early Childhood': {
        expertise: ['early childhood education', 'play-based learning', 'literacy', 'numeracy', 'social skills'],
        welcome: 'Early childhood education question? Ask about teaching young children.',
        allowed: ['early childhood', 'preschool', 'kindergarten', 'play-based', 'learning through play', 'phonics', 'alphabet', 'counting', 'shapes', 'social skills', 'sharing', 'circle time', 'montessori', 'art', 'craft', 'storytime'],
        related: ['education', 'child development', 'teaching'],
        synonyms: ['preschool education', 'ece'],
        intents: ['teaching literacy', 'planning activities', 'managing a classroom'],
        starters: ['How do I teach phonics?', 'What is play-based learning?', 'How do I set up a preschool classroom?', 'How do I help children learn to share?'],
      },
      Elementary: {
        expertise: ['elementary education', 'reading', 'writing', 'math', 'science'],
        welcome: 'Elementary education question? Ask about teaching grades K-5.',
        allowed: ['elementary', 'elementary school', 'primary', 'grade', 'math', 'reading', 'writing', 'science', 'social studies', 'lesson plan', 'differentiation', 'assessment', 'spelling', 'grammar', 'multiplication', 'fractions', 'classroom management', 'classroom', 'manage classroom', 'students'],
        related: ['education', 'teaching', 'child development'],
        synonyms: ['primary education', 'grade school'],
        intents: ['planning lessons', 'teaching reading', 'managing classroom'],
        starters: ['How do I teach fractions?', 'How do I differentiate instruction?', 'How do I manage a classroom?', 'How do I teach reading comprehension?'],
      },
      Secondary: {
        expertise: ['secondary education', 'subject teaching', 'adolescent learning', 'assessment', 'college prep'],
        welcome: 'Secondary education question? Ask about teaching middle or high school.',
        allowed: ['secondary', 'middle school', 'high school', 'subject', 'algebra', 'biology', 'literature', 'history', 'essay', 'exam', 'test prep', 'sat', 'college prep', 'adolescent', 'motivation', 'engagement', 'project-based'],
        related: ['education', 'teaching', 'development'],
        synonyms: ['secondary education', 'high school teaching'],
        intents: ['teaching subjects', 'preparing for exams', 'engaging teens'],
        starters: ['How do I engage high school students?', 'How do I prepare students for exams?', 'How do I teach essay writing?', 'How do I use project-based learning?'],
      },
      'Higher Education': {
        expertise: ['higher education', 'college teaching', 'lectures', 'seminars', 'research'],
        welcome: 'Higher education question? Ask about college teaching, lectures, or research.',
        allowed: ['higher education', 'college', 'university', 'professor', 'lecture', 'seminar', 'curriculum', 'syllabus', 'grading', 'office hours', 'research', 'publication', 'thesis', 'dissertation', 'academic', 'tenure'],
        related: ['education', 'academia', 'research'],
        synonyms: ['tertiary education', 'university teaching'],
        intents: ['designing a course', 'lecturing', 'advising students'],
        starters: ['How do I design a college course?', 'How do I give a good lecture?', 'How do I mentor undergraduates?', 'How do I get tenure?'],
      },
      'Special Education': {
        expertise: ['special education', 'iep', 'accommodations', 'inclusion', 'behavior'],
        welcome: 'Special education question? Ask about ieps, accommodations, or inclusion.',
        allowed: ['special education', 'special ed', 'sped', 'iep', '504', 'accommodation', 'modification', 'inclusion', 'mainstream', 'behavior', 'autism', 'adhd', 'dyslexia', 'speech', 'occupational therapy', 'assistive technology'],
        related: ['education', 'child development', 'health'],
        synonyms: ['special needs education', 'sped'],
        intents: ['writing an iep', 'accommodating students', 'managing behavior'],
        starters: ['What is an IEP?', 'How do I accommodate students with ADHD?', 'What is inclusion?', 'How do I support a student with dyslexia?'],
        disclaimer: true,
      },
      ESL: {
        expertise: ['esl', 'ell', 'english teaching', 'language acquisition', 'lesson planning'],
        welcome: 'ESL question? Ask about teaching English, lesson plans, or activities.',
        allowed: ['esl', 'ell', 'english as a second language', 'english language learner', 'tefl', 'tesol', 'lesson plan', 'grammar', 'vocabulary', 'speaking', 'listening', 'reading', 'writing', 'pronunciation', 'conversation', 'activity'],
        related: ['education', 'languages', 'teaching'],
        synonyms: ['tefl', 'tesol'],
        intents: ['planning lessons', 'teaching grammar', 'improving speaking'],
        starters: ['How do I teach English grammar?', 'How do I plan an ESL lesson?', 'How do I improve student speaking?', 'What is TEFL?'],
      },
      'STEM Education': {
        expertise: ['stem education', 'science', 'technology', 'engineering', 'math'],
        welcome: 'STEM education question? Ask about teaching science, tech, or math.',
        allowed: ['stem', 'stem education', 'science', 'technology', 'engineering', 'math', 'coding', 'robotics', 'lab', 'experiment', 'project', 'problem-based', 'hands-on', 'maker', '3d printing', 'computational thinking'],
        related: ['education', 'science', 'technology'],
        synonyms: ['stem learning', 'science education'],
        intents: ['teaching stem', 'designing projects', 'integrating technology'],
        starters: ['How do I make STEM engaging?', 'How do I teach coding to kids?', 'What is project-based learning in STEM?', 'How do I set up a makerspace?'],
      },
      'Online Teaching': {
        expertise: ['online teaching', 'remote learning', 'lms', 'engagement', 'tools'],
        welcome: 'Online teaching question? Ask about remote learning, lms, or tools.',
        allowed: ['online teaching', 'remote learning', 'distance learning', 'zoom', 'google classroom', 'lms', 'canvas', 'moodle', 'synchronous', 'asynchronous', 'engagement', 'discussion', 'breakout', 'recording', 'digital assessment', 'student', 'students', 'engage', 'learners', 'remote class'],
        related: ['education', 'technology', 'teaching'],
        synonyms: ['e-learning', 'virtual teaching'],
        intents: ['setting up online classes', 'engaging students', 'using an lms'],
        starters: ['How do I teach effectively online?', 'What is the best LMS?', 'How do I engage remote students?', 'How do I assess online?'],
      },
      'Curriculum Design': {
        expertise: ['curriculum design', 'standards', 'alignment', 'assessment', 'mapping'],
        welcome: 'Curriculum design question? Ask about standards, mapping, or alignment.',
        allowed: ['curriculum design', 'curriculum', 'lesson plan', 'unit plan', 'standard', 'alignment', 'backward design', 'ubd', 'scope and sequence', 'mapping', 'assessment', 'rubric', 'competency', 'outcome', 'framework'],
        related: ['education', 'teaching', 'design'],
        synonyms: ['curriculum development', 'instructional design'],
        intents: ['designing a curriculum', 'aligning to standards', 'building assessments'],
        starters: ['How do I design a curriculum?', 'What is backward design?', 'How do I align to standards?', 'How do I create a rubric?'],
      },
      Assessment: {
        expertise: ['assessment', 'formative', 'summative', 'grading', 'feedback'],
        welcome: 'Assessment question? Ask about formative, summative, or grading.',
        allowed: ['assessment', 'formative', 'summative', 'diagnostic', 'grading', 'rubric', 'feedback', 'peer assessment', 'self-assessment', 'portfolio', 'standardized', 'test', 'quiz', 'exam', 'benchmark', 'data'],
        related: ['education', 'teaching', 'measurement'],
        synonyms: ['evaluation', 'educational measurement'],
        intents: ['designing assessments', 'giving feedback', 'using data'],
        starters: ['What is the difference between formative and summative?', 'How do I give effective feedback?', 'How do I create a good rubric?', 'How do I use assessment data?'],
      },
    },
  },

  Writing: {
    themes: ['Mono', 'Slate', 'Sunset'],
    specialties: {
      Fiction: {
        expertise: ['fiction writing', 'plot', 'character', 'setting', 'dialogue'],
        welcome: 'Fiction writing question? Ask about plot, character, or dialogue.',
        allowed: ['fiction', 'fiction writing', 'novel', 'short story', 'plot', 'character', 'protagonist', 'antagonist', 'setting', 'dialogue', 'scene', 'chapter', 'narrator', 'point of view', 'tension', 'conflict', 'genre', 'fantasy', 'mystery', 'romance', 'sci-fi'],
        related: ['writing', 'literature', 'creative'],
        synonyms: ['storytelling', 'creative writing'],
        intents: ['developing a plot', 'building characters', 'writing dialogue'],
        starters: ['How do I outline a novel?', 'How do I create compelling characters?', 'How do I write natural dialogue?', 'How do I build tension?'],
      },
      'Non-fiction': {
        expertise: ['nonfiction writing', 'research', 'structure', 'narrative', 'memoir'],
        welcome: 'Non-fiction writing question? Ask about research, structure, or memoir.',
        allowed: ['nonfiction', 'non-fiction', 'narrative', 'memoir', 'biography', 'essay', 'article', 'research', 'source', 'structure', 'thesis', 'argument', 'evidence', 'chapter', 'voice', 'true story', 'journalism'],
        related: ['writing', 'journalism', 'publishing'],
        synonyms: ['creative nonfiction', 'narrative nonfiction'],
        intents: ['writing a memoir', 'structuring arguments', 'conducting research'],
        starters: ['How do I write a memoir?', 'How do I structure a nonfiction book?', 'How do I conduct research for writing?', 'What is narrative nonfiction?'],
      },
      Poetry: {
        expertise: ['poetry', 'forms', 'meter', 'rhyme', 'imagery'],
        welcome: 'Poetry question? Ask about forms, meter, or imagery.',
        allowed: ['poetry', 'poem', 'poet', 'sonnet', 'haiku', 'free verse', 'meter', 'rhyme', 'rhythm', 'imagery', 'metaphor', 'simile', 'alliteration', 'stanza', 'line', 'verse', 'iambic', 'limerick', 'couplet'],
        related: ['writing', 'literature', 'art'],
        synonyms: ['verse', 'poesy'],
        intents: ['writing a poem', 'learning forms', 'analyzing poetry'],
        starters: ['How do I write a haiku?', 'What is iambic pentameter?', 'What is the difference between metaphor and simile?', 'How do I start writing poetry?'],
      },
      Screenwriting: {
        expertise: ['screenwriting', 'script', 'format', 'structure', 'dialogue'],
        welcome: 'Screenwriting question? Ask about script, format, or structure.',
        allowed: ['screenwriting', 'screenplay', 'script', 'scene', 'slugline', 'dialogue', 'parenthetical', 'transition', 'character', 'plot', 'structure', 'three-act', 'logline', 'treatment', 'beats', 'formatting', 'final draft', 'writer room'],
        related: ['writing', 'film', 'drama'],
        synonyms: ['scriptwriting', 'screenplay writing'],
        intents: ['writing a script', 'formatting correctly', 'structuring a story'],
        starters: ['How do I format a screenplay?', 'What is the three-act structure?', 'How do I write a logline?', 'How do I write for the screen vs stage?'],
      },
      'Technical Writing': {
        expertise: ['technical writing', 'documentation', 'manuals', 'procedures', 'style'],
        welcome: 'Technical writing question? Ask about documentation, manuals, or style.',
        allowed: ['technical writing', 'technical writer', 'documentation', 'manual', 'guide', 'procedure', 'style guide', 'api doc', 'user guide', 'release notes', 'readme', 'markdown', 'information architecture', 'diagram', 'screenshot'],
        related: ['writing', 'technology', 'design'],
        synonyms: ['tech comm', 'technical communication'],
        intents: ['writing documentation', 'structuring manuals', 'using style guides'],
        starters: ['How do I write good documentation?', 'What is a style guide?', 'How do I structure a user manual?', 'How do I write API documentation?'],
      },
      Copywriting: {
        expertise: ['copywriting', 'advertising', 'landing pages', 'calls to action', 'persuasion'],
        welcome: 'Copywriting question? Ask about ads, landing pages, or persuasion.',
        allowed: ['copywriting', 'copy', 'ad', 'advertising', 'landing page', 'headline', 'cta', 'call to action', 'value proposition', 'benefits', 'features', 'persuasion', 'aida', 'formula', 'email copy', 'social copy', 'tagline'],
        related: ['writing', 'marketing', 'business'],
        synonyms: ['ad copy', 'persuasive writing'],
        intents: ['writing ads', 'improving conversion', 'crafting headlines'],
        starters: ['How do I write a compelling headline?', 'What is the AIDA formula?', 'How do I write a landing page?', 'How do I write email copy that converts?'],
      },
      Journalism: {
        expertise: ['journalism', 'reporting', 'news writing', 'interviews', 'ethics'],
        welcome: 'Journalism question? Ask about reporting, news writing, or ethics.',
        allowed: ['journalism', 'journalist', 'news', 'reporting', 'article', 'interview', 'source', 'fact-checking', 'inverted pyramid', 'lede', 'headline', 'ethics', 'objectivity', 'feature', 'investigative', 'press', 'freedom'],
        related: ['writing', 'media', 'communication'],
        synonyms: ['news writing', 'reporting'],
        intents: ['writing a news story', 'conducting interviews', 'fact-checking'],
        starters: ['How do I write a news article?', 'How do I conduct an interview?', 'What is the inverted pyramid?', 'How do I fact-check?'],
      },
      'Academic Writing': {
        expertise: ['academic writing', 'research papers', 'theses', 'citations', 'structure'],
        welcome: 'Academic writing question? Ask about papers, theses, or citations.',
        allowed: ['academic writing', 'academic', 'research paper', 'thesis', 'dissertation', 'essay', 'abstract', 'introduction', 'methodology', 'results', 'conclusion', 'citation', 'apa', 'mla', 'chicago', 'reference', 'bibliography', 'peer review'],
        related: ['writing', 'education', 'research'],
        synonyms: ['scholarly writing', 'research writing'],
        intents: ['writing a paper', 'citing sources', 'structuring a thesis'],
        starters: ['How do I structure a research paper?', 'How do I cite sources in APA?', 'How do I write a strong thesis statement?', 'What is the peer review process?'],
      },
      Blogging: {
        expertise: ['blogging', 'content', 'platforms', 'seo', 'monetization'],
        welcome: 'Blogging question? Ask about content, platforms, or seo.',
        allowed: ['blogging', 'blog', 'blogger', 'content', 'post', 'wordpress', 'medium', 'substack', 'seo', 'keyword', 'traffic', 'monetization', 'affiliate', 'sponsored', 'email list', 'niche', 'editorial calendar'],
        related: ['writing', 'marketing', 'media'],
        synonyms: ['blog writing', 'online publishing'],
        intents: ['starting a blog', 'growing traffic', 'making money'],
        starters: ['How do I start a blog?', 'How do I get traffic to my blog?', 'How do I monetize a blog?', 'How do I write great blog posts?'],
      },
      Editing: {
        expertise: ['editing', 'copy editing', 'proofreading', 'rewriting', 'feedback'],
        welcome: 'Editing question? Ask about copy editing, proofreading, or rewriting.',
        allowed: ['editing', 'editor', 'copy editing', 'copyediting', 'proofreading', 'proofread', 'rewriting', 'rewrite', 'revision', 'manuscript', 'track changes', 'style guide', 'grammar', 'clarity', 'flow', 'feedback', 'developmental edit', 'line edit'],
        related: ['writing', 'publishing', 'communication'],
        synonyms: ['manuscript editing', 'revision'],
        intents: ['editing a manuscript', 'proofreading', 'giving feedback'],
        starters: ['How do I edit a manuscript?', 'What is the difference between copy editing and proofreading?', 'How do I give constructive feedback?', 'What is a developmental edit?'],
      },
    },
  },
};