// ============================================================
// SCARLET DOMAIN KNOWLEDGE — PART 6
// ============================================================

export const DOMAIN_PART6 = {
  'Government & Politics': {
    themes: ['Royal', 'Slate', 'Mono'],
    specialties: {
      'Political Science': {
        expertise: ['political systems', 'government', 'theory', 'comparative politics', 'democracy'],
        welcome: 'Political science question? Ask about systems, theories, or governments.',
        allowed: ['political science', 'politics', 'government', 'democracy', 'republic', 'parliament', 'president', 'political system', 'theory', 'comparative', 'state', 'sovereignty', 'legislature', 'executive', 'judiciary', 'federal'],
        related: ['government', 'history', 'law'],
        synonyms: ['poli sci', 'political studies'],
        intents: ['understanding systems', 'learning about democracy', 'comparing governments'],
        starters: ['What is the difference between a republic and a democracy?', 'How do parliamentary and presidential systems differ?', 'What is federalism?', 'What is the separation of powers?'],
      },
      'Public Policy': {
        expertise: ['policy making', 'analysis', 'implementation', 'evaluation', 'governance'],
        welcome: 'Public policy question? Ask about making, analyzing, or evaluating policy.',
        allowed: ['public policy', 'policy', 'policymaking', 'analysis', 'regulation', 'implementation', 'evaluation', 'governance', 'stakeholder', 'cost-benefit', 'evidence-based', 'legislation', 'statute', 'welfare', 'reform'],
        related: ['government', 'economics', 'law'],
        synonyms: ['policy analysis', 'policymaking'],
        intents: ['understanding policy', 'analyzing a policy', 'learning the process'],
        starters: ['How is public policy made?', 'What is cost-benefit analysis in policy?', 'What is the policy cycle?', 'How do stakeholders influence policy?'],
      },
      'International Relations': {
        expertise: ['international relations', 'diplomacy', 'treaties', 'organizations', 'conflict'],
        welcome: 'International relations question? Ask about diplomacy, treaties, or organizations.',
        allowed: ['international relations', 'ir', 'diplomacy', 'diplomat', 'treaty', 'united nations', 'un', 'nato', 'eu', 'wto', 'conflict', 'peace', 'sovereignty', 'foreign policy', 'embassy', 'ambassador', 'sanction'],
        related: ['government', 'geopolitics', 'law'],
        synonyms: ['world affairs', 'foreign affairs'],
        intents: ['understanding diplomacy', 'learning about organizations', 'analyzing conflicts'],
        starters: ['What does the UN actually do?', 'How does diplomacy work?', 'What is the difference between NATO and the UN?', 'How are sanctions used?'],
      },
      Civics: {
        expertise: ['citizenship', 'rights', 'responsibilities', 'voting', 'institutions'],
        welcome: 'Civics question? Ask about rights, voting, or institutions.',
        allowed: ['civics', 'citizen', 'citizenship', 'rights', 'responsibilities', 'voting', 'election', 'constitution', 'bill of rights', 'freedoms', 'duties', 'government', 'law', 'jury', 'taxes', 'community'],
        related: ['government', 'law', 'education'],
        synonyms: ['citizenship education', 'civic education'],
        intents: ['understanding rights', 'learning to vote', 'studying institutions'],
        starters: ['What are my rights as a citizen?', 'How does voting work?', 'What is the Bill of Rights?', 'What are the branches of government?'],
      },
      Elections: {
        expertise: ['elections', 'voting systems', 'campaigns', 'polling', 'electoral college'],
        welcome: 'Elections question? Ask about systems, campaigns, or polling.',
        allowed: ['election', 'elections', 'vote', 'voting', 'ballot', 'campaign', 'candidate', 'poll', 'polling', 'electoral college', 'proportional', 'first past the post', 'turnout', 'gerrymandering', 'primary', 'debate', 'electorate'],
        related: ['government', 'politics', 'civics'],
        synonyms: ['electoral politics'],
        intents: ['understanding voting systems', 'analyzing campaigns', 'learning about polling'],
        starters: ['What is the electoral college?', 'How does proportional representation work?', 'What is gerrymandering?', 'How accurate are opinion polls?'],
      },
      Diplomacy: {
        expertise: ['diplomacy', 'negotiations', 'ambassadors', 'summits', 'protocol'],
        welcome: 'Diplomacy question? Ask about negotiations, ambassadors, or protocol.',
        allowed: ['diplomacy', 'diplomatic', 'negotiation', 'negotiations', 'ambassador', 'embassy', 'summit', 'protocol', 'foreign policy', 'treaty', 'talks', 'mediation', 'consulate', 'envoy', 'visa diplomacy'],
        related: ['international relations', 'government', 'politics'],
        synonyms: ['statecraft', 'diplomatic relations'],
        intents: ['understanding diplomacy', 'learning about negotiations', 'studying protocol'],
        starters: ['What does an ambassador do?', 'How are treaties negotiated?', 'What is shuttle diplomacy?', 'What is diplomatic immunity?'],
      },
      Governance: {
        expertise: ['governance', 'institutions', 'accountability', 'transparency', 'public administration'],
        welcome: 'Governance question? Ask about institutions, accountability, or transparency.',
        allowed: ['governance', 'government', 'institution', 'accountability', 'transparency', 'corruption', 'public administration', 'civil service', 'bureaucracy', 'rule of law', 'oversight', 'audit', 'efficiency', 'reform', 'local government'],
        related: ['government', 'public policy', 'business'],
        synonyms: ['public governance', 'administration'],
        intents: ['understanding governance', 'combating corruption', 'learning about institutions'],
        starters: ['What is good governance?', 'How does bureaucracy work?', 'How do we reduce corruption?', 'What is the rule of law?'],
      },
      'Constitutional Law': {
        expertise: ['constitutions', 'constitutional law', 'amendments', 'judicial review', 'rights'],
        welcome: 'Constitutional law question? Ask about constitutions, rights, or amendments.',
        allowed: ['constitutional law', 'constitution', 'amendment', 'bill of rights', 'judicial review', 'supreme court', 'due process', 'equal protection', 'free speech', 'rights', 'federalism', 'precedent', 'court', 'charter'],
        related: ['government', 'law', 'civics'],
        synonyms: ['constitutional law', 'public law'],
        intents: ['understanding amendments', 'learning about judicial review', 'studying rights'],
        starters: ['What is judicial review?', 'How does the amendment process work?', 'What is due process?', 'What is the difference between a constitution and a statute?'],
        disclaimer: true,
      },
      'Political Theory': {
        expertise: ['political theory', 'philosophers', 'ideologies', 'liberty', 'justice'],
        welcome: 'Political theory question? Ask about ideas, philosophers, or ideologies.',
        allowed: ['political theory', 'theory', 'philosopher', 'plato', 'aristotle', 'machiavelli', 'locke', 'hobbes', 'rousseau', 'kant', 'marx', 'liberty', 'freedom', 'justice', 'equality', 'ideology', 'liberalism', 'conservatism', 'socialism'],
        related: ['politics', 'philosophy', 'history'],
        synonyms: ['political philosophy'],
        intents: ['learning about philosophers', 'understanding ideologies', 'analyzing ideas'],
        starters: ['What is the social contract?', 'What is the difference between liberalism and conservatism?', 'What did Machiavelli write?', 'What is distributive justice?'],
      },
      'Public Administration': {
        expertise: ['public administration', 'civil service', 'management', 'budgeting', 'service delivery'],
        welcome: 'Public administration question? Ask about management, service, or budgeting.',
        allowed: ['public administration', 'administration', 'civil service', 'bureaucracy', 'management', 'public manager', 'budget', 'budgeting', 'service delivery', 'procurement', 'public sector', 'efficiency', 'human resources', 'policy', 'government'],
        related: ['government', 'management', 'public policy'],
        synonyms: ['administrative science', 'public management'],
        intents: ['understanding administration', 'managing public services', 'learning about budgeting'],
        starters: ['What is public administration?', 'How is a government budget made?', 'What does a civil servant do?', 'How do I improve public service delivery?'],
      },
    },
  },

  Hospitality: {
    themes: ['Sunset', 'Amber', 'Ocean'],
    specialties: {
      'Hotel Management': {
        expertise: ['hotel operations', 'front office', 'reservations', 'housekeeping', 'revenue'],
        welcome: 'Hotel management question? Ask about operations, front office, or revenue.',
        allowed: ['hotel management', 'hotel', 'front office', 'reservation', 'booking', 'check-in', 'check-out', 'housekeeping', 'room', 'suite', 'concierge', 'revenue', 'occupancy', 'adr', 'revpar', 'upselling', 'guest service'],
        related: ['hospitality', 'business', 'tourism'],
        synonyms: ['lodging management', 'hotel operations'],
        intents: ['managing operations', 'improving occupancy', 'training staff'],
        starters: ['How do I manage hotel bookings?', 'What is RevPAR?', 'How do I improve guest satisfaction?', 'How does the front office work?'],
      },
      'Restaurant Management': {
        expertise: ['restaurant operations', 'staffing', 'menu', 'costs', 'service'],
        welcome: 'Restaurant management question? Ask about operations, costs, or service.',
        allowed: ['restaurant management', 'restaurant', 'operations', 'staff', 'staffing', 'menu', 'cost', 'food cost', 'portion', 'inventory', 'supplier', 'service', 'front of house', 'back of house', 'pos', 'reservation', 'turnover'],
        related: ['hospitality', 'business', 'food'],
        synonyms: ['food service management', 'f&b management'],
        intents: ['managing costs', 'training staff', 'improving service'],
        starters: ['How do I control food costs?', 'How do I train restaurant staff?', 'What is front of house vs back of house?', 'How do I set menu prices?'],
      },
      'Event Planning': {
        expertise: ['event planning', 'weddings', 'corporate events', 'logistics', 'budgets'],
        welcome: 'Event planning question? Ask about weddings, corporate events, or logistics.',
        allowed: ['event planning', 'event', 'wedding', 'conference', 'corporate event', 'birthday', 'logistics', 'venue', 'catering', 'budget', 'timeline', 'decor', 'entertainment', 'rsvp', 'vendor', 'theme', 'planning'],
        related: ['hospitality', 'business', 'creative'],
        synonyms: ['event management', 'occasion planning'],
        intents: ['planning an event', 'managing a budget', 'coordinating vendors'],
        starters: ['How do I plan a wedding?', 'How do I plan a corporate event?', 'How do I manage an event budget?', 'What should an event timeline include?'],
      },
      Tourism: {
        expertise: ['tourism', 'destinations', 'attractions', 'tour operations', 'marketing'],
        welcome: 'Hospitality tourism question? Ask about destinations or operations.',
        allowed: ['tourism', 'tourist', 'destination', 'attraction', 'tour', 'tour operator', 'guide', 'package', 'itinerary', 'travel', 'visitor', 'tourism marketing', 'seasonality', 'heritage tourism'],
        related: ['hospitality', 'travel', 'business'],
        synonyms: ['travel industry', 'tourist industry'],
        intents: ['creating tour packages', 'marketing a destination', 'managing tourism'],
        starters: ['How do I create a tour package?', 'What is sustainable tourism?', 'How do I market a destination?', 'What is the tourism multiplier effect?'],
      },
      'Food Service': {
        expertise: ['food service', 'kitchen', 'safety', 'menu', 'service standards'],
        welcome: 'Food service question? Ask about kitchens, service, or safety.',
        allowed: ['food service', 'kitchen', 'prep', 'line', 'expedite', 'service', 'waiter', 'serving', 'plating', 'food safety', 'haccp', 'menu', 'special', 'speed', 'upsell', 'table setting'],
        related: ['hospitality', 'food', 'management'],
        synonyms: ['f&b service', 'dining service'],
        intents: ['improving service', 'learning kitchen flow', 'ensuring safety'],
        starters: ['How do I set a table correctly?', 'What is HACCP?', 'How does a professional kitchen run?', 'How do I upsell without being pushy?'],
      },
      Housekeeping: {
        expertise: ['housekeeping', 'cleaning standards', 'linen', 'inspection', 'scheduling'],
        welcome: 'Housekeeping question? Ask about standards, linen, or scheduling.',
        allowed: ['housekeeping', 'cleaning', 'room cleaning', 'linen', 'laundry', 'amenity', 'inspection', 'checklist', 'turnover', 'scheduling', 'supplies', 'sanitize', 'turndown', 'maid', 'cart'],
        related: ['hospitality', 'cleaning', 'management'],
        synonyms: ['room care', 'cleaning services'],
        intents: ['building checklists', 'managing staff', 'improving standards'],
        starters: ['How do I build a housekeeping checklist?', 'How long should a room take to clean?', 'What are housekeeping standards in hotels?', 'How do I manage linen inventory?'],
      },
      Concierge: {
        expertise: ['concierge', 'guest requests', 'recommendations', 'bookings', 'local knowledge'],
        welcome: 'Concierge question? Ask about guest services or recommendations.',
        allowed: ['concierge', 'guest', 'request', 'recommendation', 'booking', 'restaurant', 'ticket', 'tour', 'transport', 'translation', 'arrival', 'departure', 'luggage', 'special request', 'local knowledge', 'insider'],
        related: ['hospitality', 'tourism', 'service'],
        synonyms: ['guest services', 'front desk'],
        intents: ['handling requests', 'making recommendations', 'booking services'],
        starters: ['How do I handle special guest requests?', 'What should a concierge know about the city?', 'How do I book restaurant reservations for guests?', 'What is the role of a concierge?'],
      },
      'Revenue Management': {
        expertise: ['revenue management', 'pricing', 'demand', 'forecasting', 'distribution'],
        welcome: 'Revenue management question? Ask about pricing, forecasting, or distribution.',
        allowed: ['revenue management', 'revenue', 'pricing', 'rate', 'demand', 'forecast', 'forecasting', 'occupancy', 'distribution', 'channel', 'direct booking', 'ota', 'segmentation', 'yield', 'dynamic pricing', 'package'],
        related: ['hospitality', 'business', 'analytics'],
        synonyms: ['yield management', 'pricing strategy'],
        intents: ['setting prices', 'forecasting demand', 'choosing channels'],
        starters: ['What is revenue management?', 'How do I forecast hotel demand?', 'What is dynamic pricing?', 'OTAs vs direct booking — how to balance?'],
      },
      'Guest Experience': {
        expertise: ['guest experience', 'service standards', 'feedback', 'personalization', 'loyalty'],
        welcome: 'Guest experience question? Ask about service, feedback, or loyalty.',
        allowed: ['guest experience', 'guest', 'experience', 'service', 'feedback', 'survey', 'complaint', 'personalization', 'loyalty', 'program', 'revisit', 'satisfaction', 'nps', 'upsell', 'wow', 'recovery'],
        related: ['hospitality', 'service', 'marketing'],
        synonyms: ['customer experience', 'guest satisfaction'],
        intents: ['improving experience', 'handling complaints', 'building loyalty'],
        starters: ['How do I measure guest satisfaction?', 'How do I handle a guest complaint?', 'What is service recovery?', 'How do I build a loyalty program?'],
      },
      Catering: {
        expertise: ['catering', 'menus', 'quantities', 'events', 'logistics'],
        welcome: 'Catering question? Ask about menus, quantities, or events.',
        allowed: ['catering', 'caterer', 'menu', 'event', 'buffet', 'plated', 'quantity', 'portions', 'food cost', 'staffing', 'rental', 'linen', 'logistics', 'delivery', 'kitchen', 'setup'],
        related: ['hospitality', 'food', 'events'],
        synonyms: ['food catering', 'event dining'],
        intents: ['planning a menu', 'calculating quantities', 'managing an event'],
        starters: ['How do I calculate food quantities for an event?', 'Buffet vs plated service?', 'How do I price a catering menu?', 'What should a catering contract include?'],
      },
    },
  },

  Insurance: {
    themes: ['Royal', 'Slate', 'Mono'],
    specialties: {
      'Life Insurance': {
        expertise: ['life insurance', 'term', 'whole life', 'beneficiaries', 'premiums'],
        welcome: 'Life insurance question? Ask about types, coverage, or beneficiaries.',
        allowed: ['life insurance', 'life policy', 'term', 'whole life', 'universal life', 'premium', 'beneficiary', 'coverage', 'death benefit', 'cash value', 'underwriting', 'rider', 'lapse', 'policy'],
        related: ['insurance', 'finance', 'retirement'],
        synonyms: ['life cover', 'mortality insurance'],
        intents: ['choosing a policy', 'understanding coverage', 'naming beneficiaries'],
        starters: ['Term vs whole life — which is right?', 'How much life insurance do I need?', 'What is a death benefit?', 'How do beneficiaries work?'],
        disclaimer: true,
      },
      'Health Insurance': {
        expertise: ['health insurance', 'plans', 'deductibles', 'networks', 'claims'],
        welcome: 'Health insurance question? Ask about plans, deductibles, or claims.',
        allowed: ['health insurance', 'health plan', 'premium', 'deductible', 'copay', 'coinsurance', 'out of pocket', 'network', 'in-network', 'out-of-network', 'hmo', 'ppo', 'medicare', 'medicaid', 'claim', 'coverage'],
        related: ['insurance', 'health', 'finance'],
        synonyms: ['medical insurance', 'health cover'],
        intents: ['choosing a plan', 'understanding deductibles', 'filing claims'],
        starters: ['What is the difference between HMO and PPO?', 'What is a deductible?', 'How do I file a health insurance claim?', 'What is out-of-pocket maximum?'],
        disclaimer: true,
      },
      'Auto Insurance': {
        expertise: ['auto insurance', 'coverage', 'deductibles', 'claims', 'discounts'],
        welcome: 'Auto insurance question? Ask about coverage, claims, or discounts.',
        allowed: ['auto insurance', 'car insurance', 'coverage', 'liability', 'collision', 'comprehensive', 'deductible', 'premium', 'claim', 'accident', 'uninsured', 'gap', 'discount', 'policy', 'fender bender'],
        related: ['insurance', 'automotive', 'finance'],
        synonyms: ['car insurance', 'motor insurance'],
        intents: ['choosing coverage', 'filing a claim', 'lowering premiums'],
        starters: ['What does car insurance cover?', 'How do I lower my car insurance premium?', 'What is the difference between collision and comprehensive?', 'How do I file an auto claim?'],
        disclaimer: true,
      },
      'Home Insurance': {
        expertise: ['home insurance', 'coverage', 'dwellings', 'claims', 'hazards'],
        welcome: 'Home insurance question? Ask about coverage, claims, or protection.',
        allowed: ['home insurance', 'homeowners', 'homeowner', 'renters', 'coverage', 'dwelling', 'personal property', 'liability', 'flood', 'fire', 'theft', 'claim', 'replacement', 'actual cash value', 'deductible'],
        related: ['insurance', 'home', 'finance'],
        synonyms: ['property insurance', 'homeowners insurance'],
        intents: ['choosing coverage', 'understanding claims', 'protecting property'],
        starters: ['What does homeowners insurance cover?', 'Do I need flood insurance?', 'What is the difference between replacement cost and actual cash value?', 'How do I file a home insurance claim?'],
        disclaimer: true,
      },
      'Business Insurance': {
        expertise: ['business insurance', 'liability', 'property', 'workers comp', 'policies'],
        welcome: 'Business insurance question? Ask about liability, property, or coverage.',
        allowed: ['business insurance', 'commercial insurance', 'liability', 'general liability', 'property', 'business interruption', 'workers comp', 'workers compensation', 'professional liability', 'errors and omissions', 'cyber', 'policy', 'coverage', 'deductible'],
        related: ['insurance', 'business', 'law'],
        synonyms: ['commercial insurance', 'commercial coverage'],
        intents: ['choosing business coverage', 'understanding liability', 'getting quotes'],
        starters: ['What insurance does a small business need?', 'What is general liability?', 'What is workers comp?', 'What is professional liability insurance?'],
        disclaimer: true,
      },
      Claims: {
        expertise: ['claims', 'filing', 'adjusters', 'settlements', 'disputes'],
        welcome: 'Insurance claims question? Ask about filing, adjusters, or settlements.',
        allowed: ['claim', 'claims', 'file', 'filing', 'adjuster', 'assessment', 'settlement', 'payout', 'denial', 'appeal', 'documentation', 'report', 'coverage', 'depreciation', 'total loss'],
        related: ['insurance', 'finance', 'consumer'],
        synonyms: ['claim processing', 'settlements'],
        intents: ['filing a claim', 'understanding settlements', 'appealing a denial'],
        starters: ['How do I file an insurance claim?', 'What does a claims adjuster do?', 'How long does a claim take?', 'What do I do if my claim is denied?'],
        disclaimer: true,
      },
      'Risk Management': {
        expertise: ['risk management', 'risk assessment', 'mitigation', 'transfer', 'frameworks'],
        welcome: 'Risk management question? Ask about assessment, mitigation, or frameworks.',
        allowed: ['risk management', 'risk', 'assessment', 'mitigation', 'transfer', 'avoidance', 'acceptance', 'framework', 'enterprise risk', 'erm', 'likelihood', 'impact', 'matrix', 'insurance', 'hedging'],
        related: ['insurance', 'business', 'finance'],
        synonyms: ['risk control', 'risk governance'],
        intents: ['assessing risk', 'mitigating risk', 'building frameworks'],
        starters: ['What is enterprise risk management?', 'How do I build a risk matrix?', 'What are the four ways to handle risk?', 'How do I identify business risks?'],
        disclaimer: true,
      },
      Underwriting: {
        expertise: ['underwriting', 'risk assessment', 'applications', 'pricing', 'renewals'],
        welcome: 'Underwriting question? Ask about assessment, pricing, or applications.',
        allowed: ['underwriting', 'underwriter', 'application', 'risk', 'pricing', 'premium', 'policy', 'renewal', 'inspection', 'medical', 'actuarial', 'rating', 'decline', 'endorsement'],
        related: ['insurance', 'finance', 'analytics'],
        synonyms: ['risk rating', 'policy issuance'],
        intents: ['understanding underwriting', 'pricing policies', 'processing applications'],
        starters: ['What does an underwriter do?', 'How is an insurance premium calculated?', 'What is a policy endorsement?', 'What is the difference between underwriting and actuarial work?'],
        disclaimer: true,
      },
      Reinsurance: {
        expertise: ['reinsurance', 'treaties', 'facultative', 'ceding', 'risk transfer'],
        welcome: 'Reinsurance question? Ask about treaties, ceding, or risk transfer.',
        allowed: ['reinsurance', 'reinsurer', 'treaty', 'facultative', 'cede', 'ceding', 'proportional', 'excess of loss', 'retention', 'catastrophe', 'cat bond', 'reinsurer', 'cedant', 'recovery'],
        related: ['insurance', 'finance', 'risk'],
        synonyms: ['insurance of insurance'],
        intents: ['understanding treaties', 'learning about cession', 'analyzing risk transfer'],
        starters: ['What is reinsurance?', 'What is the difference between proportional and excess of loss?', 'What is a treaty vs facultative?', 'How do cat bonds work?'],
        disclaimer: true,
      },
      InsurTech: {
        expertise: ['insurtech', 'digital insurance', 'telematics', 'ai in insurance', 'startups'],
        welcome: 'Insurtech question? Ask about digital insurance, telematics, or innovation.',
        allowed: ['insurtech', 'insurance technology', 'digital insurance', 'telematics', 'ai', 'machine learning', 'app', 'comparison', 'on-demand', 'micro-insurance', 'blockchain', 'smart contract', 'startup', 'policy admin', 'claims automation'],
        related: ['insurance', 'technology', 'finance'],
        synonyms: ['insurance tech', 'digital insurance'],
        intents: ['understanding insurtech', 'using telematics', 'learning about innovation'],
        starters: ['What is insurtech?', 'How does telematics work in car insurance?', 'How is AI changing insurance?', 'What is on-demand insurance?'],
        disclaimer: true,
      },
    },
  },
};
