// ============================================================
// SCARLET DOMAIN KNOWLEDGE — PART 8
// ============================================================

export const DOMAIN_PART8 = {
  Manufacturing: {
    themes: ['Midnight', 'Mono', 'Terminal'],
    specialties: {
      'Lean Manufacturing': {
        expertise: ['lean', 'waste', 'kaizen', 'value stream', '5s'],
        welcome: 'Lean manufacturing question? Ask about waste, kaizen, or value streams.',
        allowed: ['lean', 'lean manufacturing', 'waste', 'kaizen', 'value stream', 'value stream mapping', '5s', 'kanban', 'jidoka', 'heijunka', 'takt', 'pull', 'continuous flow', 'gemba', 'muda'],
        related: ['manufacturing', 'operations', 'quality'],
        synonyms: ['lean production', 'lean thinking'],
        intents: ['reducing waste', 'implementing 5s', 'mapping value streams'],
        starters: ['What are the 7 wastes of lean?', 'What is 5S?', 'What is a value stream map?', 'What is takt time?'],
      },
      'Quality Control': {
        expertise: ['quality control', 'inspection', 'sqa', 'defects', 'capability'],
        welcome: 'Manufacturing quality question? Ask about inspection, control, or capability.',
        allowed: ['quality control', 'quality', 'inspection', 'spc', 'statistical process control', 'cpk', 'defect', 'ppm', 'gauge', 'inspection plan', 'aql', 'control chart', 'six sigma', 'capability'],
        related: ['manufacturing', 'quality', 'operations'],
        synonyms: ['quality engineering', 'qc'],
        intents: ['implementing spc', 'reducing defects', 'measuring capability'],
        starters: ['What is statistical process control?', 'What is Cpk?', 'How do I read a control chart?', 'What is AQL?'],
      },
      Automation: {
        expertise: ['automation', 'robotics', 'plc', 'sensors', 'integration'],
        welcome: 'Manufacturing automation question? Ask about robots, plcs, or sensors.',
        allowed: ['automation', 'robot', 'robotics', 'plc', 'scada', 'hmi', 'sensor', 'actuator', 'conveyor', 'pick and place', 'cobot', 'automation', 'integration', 'vision system', 'servo'],
        related: ['manufacturing', 'technology', 'engineering'],
        synonyms: ['industrial automation', 'robotics'],
        intents: ['automating a process', 'learning plcs', 'integrating robots'],
        starters: ['How do I automate a production line?', 'What is a PLC?', 'What is the difference between a robot and a cobot?', 'How do vision systems work?'],
      },
      '3D Printing': {
        expertise: ['3d printing', 'filaments', 'printers', 'design for printing', 'post-processing'],
        welcome: '3D printing question? Ask about printers, filaments, or design.',
        allowed: ['3d printing', '3d printer', '3d print', 'fdm', 'sla', 'resin', 'filament', 'pla', 'abs', 'petg', 'slicer', 'layer', 'supports', 'infill', 'bed adhesion', 'nozzle', 'print quality'],
        related: ['manufacturing', 'technology', 'design'],
        synonyms: ['additive manufacturing', 'rapid prototyping'],
        intents: ['choosing a printer', 'improving print quality', 'designing for print'],
        starters: ['Which 3D printer should I buy?', 'PLA vs ABS vs PETG?', 'How do I fix stringing?', 'What is additive manufacturing?'],
      },
      CNC: {
        expertise: ['cnc machining', 'mills', 'lathes', 'tooling', 'programming'],
        welcome: 'CNC question? Ask about machines, tooling, or programming.',
        allowed: ['cnc', 'cnc machining', 'mill', 'milling', 'lathe', 'turning', 'g-code', 'cadcam', 'tool', 'end mill', 'insert', 'feed', 'speed', 'spindle', 'chuck', 'tolerance', 'finish'],
        related: ['manufacturing', 'engineering', 'mechanics'],
        synonyms: ['computer numerical control', 'machining'],
        intents: ['learning cnc', 'choosing tools', 'programming parts'],
        starters: ['How do I learn CNC machining?', 'What is G-code?', 'How do I choose end mills?', 'Milling vs turning — what is the difference?'],
      },
      Assembly: {
        expertise: ['assembly', 'line balancing', 'torque', 'fasteners', 'ergonomics'],
        welcome: 'Assembly question? Ask about lines, fasteners, or balancing.',
        allowed: ['assembly', 'assembly line', 'line balancing', 'fastener', 'bolt', 'screw', 'torque', 'press fit', 'snap fit', 'adhesive', 'workstation', 'poka-yoke', 'ergonomics', 'cycle time', 'hand tool'],
        related: ['manufacturing', 'operations', 'quality'],
        synonyms: ['assembly operations', 'production assembly'],
        intents: ['balancing a line', 'choosing fasteners', 'improving ergonomics'],
        starters: ['How do I balance an assembly line?', 'What are the types of fasteners?', 'What is poka-yoke?', 'How do I set torque specs?'],
      },
      'Plant Management': {
        expertise: ['plant management', 'production', 'maintenance', 'staff', 'kpis'],
        welcome: 'Plant management question? Ask about production, maintenance, or metrics.',
        allowed: ['plant management', 'plant', 'production', 'shift', 'supervisor', 'maintenance', 'preventive maintenance', 'oee', 'uptime', 'downtime', 'kpi', 'schedule', 'capacity', 'throughput', 'safety'],
        related: ['manufacturing', 'operations', 'management'],
        synonyms: ['factory management', 'plant operations'],
        intents: ['improving oee', 'managing shifts', 'reducing downtime'],
        starters: ['What is OEE?', 'How do I reduce downtime?', 'How do I manage production schedules?', 'What are the key plant KPIs?'],
      },
      'Six Sigma': {
        expertise: ['six sigma', 'dmaic', 'statistics', 'process improvement', 'belts'],
        welcome: 'Six Sigma question? Ask about dmaic, statistics, or belts.',
        allowed: ['six sigma', 'sigma', 'dmaic', 'define', 'measure', 'analyze', 'improve', 'control', 'green belt', 'black belt', 'statistics', 'variation', 'capability', 'defect', 'dpm', 'kaizen', 'process'],
        related: ['manufacturing', 'quality', 'operations'],
        synonyms: ['six sigma methodology'],
        intents: ['learning dmaic', 'getting certified', 'running projects'],
        starters: ['What are the 5 phases of DMAIC?', 'What is the difference between a green belt and black belt?', 'How is Six Sigma different from lean?', 'What is process capability?'],
      },
      'Industrial Safety': {
        expertise: ['industrial safety', 'osha', 'hazards', 'ppe', 'emergency'],
        welcome: 'Industrial safety question? Ask about hazards, osha, or ppe.',
        allowed: ['industrial safety', 'safety', 'osha', 'hazard', 'machine guarding', 'lockout tagout', 'confined space', 'ppe', 'hard hat', 'hearing', 'respirator', 'chemical', 'msds', 'emergency', 'fire', 'first aid', 'training'],
        related: ['manufacturing', 'construction', 'health'],
        synonyms: ['occupational safety', 'workplace safety'],
        intents: ['implementing safety', 'understanding osha', 'preventing incidents'],
        starters: ['What are the top industrial hazards?', 'What is lockout/tagout?', 'How do I create a safety program?', 'What is machine guarding?'],
      },
      'Materials Handling': {
        expertise: ['material handling', 'forklifts', 'conveyors', 'cranes', 'storage'],
        welcome: 'Materials handling question? Ask about equipment, storage, or safety.',
        allowed: ['material handling', 'materials handling', 'forklift', 'pallet jack', 'conveyor', 'crane', 'hoist', 'lift', 'storage', 'rack', 'container', 'ergonomics', 'picking', 'automated guided', 'agv', 'safety'],
        related: ['manufacturing', 'logistics', 'operations'],
        synonyms: ['materials movement', 'material flow'],
        intents: ['choosing equipment', 'improving flow', 'reducing injuries'],
        starters: ['How do I choose material handling equipment?', 'What is an AGV?', 'How do I reduce lifting injuries?', 'How do I design a material flow?'],
      },
    },
  },

  Marketing: {
    themes: ['Sunset', 'Royal', 'Mono'],
    specialties: {
      'Digital Marketing': {
        expertise: ['digital marketing', 'channels', 'funnels', 'crm', 'analytics'],
        welcome: 'Digital marketing question? Ask about channels, funnels, or analytics.',
        allowed: ['digital marketing', 'marketing', 'digital', 'channel', 'funnel', 'lead', 'conversion', 'landing page', 'crm', 'automation', 'analytics', 'roi', 'attribution', 'campaign', 'strategy'],
        related: ['marketing', 'business', 'technology'],
        synonyms: ['online marketing', 'growth marketing'],
        intents: ['building a strategy', 'optimizing funnels', 'measuring roi'],
        starters: ['How do I build a digital marketing strategy?', 'What is a marketing funnel?', 'How do I measure ROI?', 'What is attribution?'],
      },
      SEO: {
        expertise: ['seo', 'keywords', 'on-page', 'off-page', 'technical seo'],
        welcome: 'SEO question? Ask about keywords, links, or rankings.',
        allowed: ['seo', 'search engine optimization', 'keyword', 'rank', 'ranking', 'google', 'on-page', 'off-page', 'backlink', 'content', 'meta', 'title', 'schema', 'technical seo', 'core web vitals', 'local seo', 'search console'],
        related: ['marketing', 'web', 'analytics'],
        synonyms: ['search optimization'],
        intents: ['doing keyword research', 'building links', 'improving rankings'],
        starters: ['How do I do keyword research?', 'What is on-page SEO?', 'How do I build backlinks?', 'What are Core Web Vitals?'],
      },
      'Social Media': {
        expertise: ['social media', 'platforms', 'content', 'engagement', 'ads'],
        welcome: 'Social media question? Ask about platforms, content, or ads.',
        allowed: ['social media', 'instagram', 'facebook', 'twitter', 'linkedin', 'tiktok', 'youtube', 'content', 'post', 'reel', 'story', 'engagement', 'followers', 'hashtag', 'ads', 'boost', 'community'],
        related: ['marketing', 'content', 'business'],
        synonyms: ['social networking', 'smm'],
        intents: ['building a presence', 'creating content', 'running ads'],
        starters: ['How do I grow on Instagram?', 'What content should I post?', 'How do hashtags work?', 'How do I run social ads?'],
      },
      'Content Marketing': {
        expertise: ['content marketing', 'blogging', 'storytelling', 'editorial', 'distribution'],
        welcome: 'Content marketing question? Ask about content, strategy, or distribution.',
        allowed: ['content marketing', 'content', 'blog', 'blogging', 'article', 'video', 'podcast', 'storytelling', 'editorial', 'calendar', 'strategy', 'distribution', 'newsletter', 'ebook', 'webinar', 'cta'],
        related: ['marketing', 'writing', 'media'],
        synonyms: ['content strategy', 'inbound content'],
        intents: ['creating a strategy', 'building an editorial calendar', 'distributing content'],
        starters: ['How do I create a content strategy?', 'What is an editorial calendar?', 'How do I write a great blog post?', 'How do I distribute content?'],
      },
      'Email Marketing': {
        expertise: ['email marketing', 'campaigns', 'automation', 'deliverability', 'segmentation'],
        welcome: 'Email marketing question? Ask about campaigns, automation, or deliverability.',
        allowed: ['email marketing', 'email', 'campaign', 'newsletter', 'automation', 'workflow', 'segment', 'segmentation', 'subject line', 'open rate', 'click rate', 'deliverability', 'spam', 'a/b test', 'landing page'],
        related: ['marketing', 'content', 'business'],
        synonyms: ['email campaigns', 'edm'],
        intents: ['building campaigns', 'improving open rates', 'setting up automation'],
        starters: ['How do I improve open rates?', 'What is email automation?', 'How do I avoid the spam folder?', 'How do I segment a list?'],
      },
      PPC: {
        expertise: ['ppc', 'google ads', 'bidding', 'keywords', 'quality score'],
        welcome: 'PPC question? Ask about Google Ads, bidding, or keywords.',
        allowed: ['ppc', 'pay per click', 'google ads', 'bing ads', 'adwords', 'bid', 'bidding', 'keyword', 'quality score', 'ctr', 'cpc', 'cpm', 'conversion', 'campaign', 'ad group', 'remarketing'],
        related: ['marketing', 'analytics', 'business'],
        synonyms: ['search advertising', 'paid search'],
        intents: ['setting up campaigns', 'optimizing bids', 'improving quality score'],
        starters: ['How do I set up Google Ads?', 'What is quality score?', 'How do I improve CTR?', 'What is remarketing?'],
      },
      'Brand Strategy': {
        expertise: ['brand strategy', 'positioning', 'identity', 'differentiation', 'equity'],
        welcome: 'Brand strategy question? Ask about positioning, identity, or equity.',
        allowed: ['brand strategy', 'brand', 'positioning', 'identity', 'differentiation', 'equity', 'value proposition', 'archetype', 'personality', 'audience', 'story', 'naming', 'tone', 'loyalty', 'brand audit'],
        related: ['marketing', 'design', 'business'],
        synonyms: ['brand building', 'branding'],
        intents: ['building a brand', 'differentiating', 'auditing brand'],
        starters: ['How do I define brand positioning?', 'What is a brand archetype?', 'How do I build brand equity?', 'What is a brand audit?'],
      },
      'Influencer Marketing': {
        expertise: ['influencer marketing', 'creators', 'campaigns', 'disclosure', 'roi'],
        welcome: 'Influencer marketing question? Ask about creators, campaigns, or disclosure.',
        allowed: ['influencer', 'influencer marketing', 'creator', 'collaboration', 'campaign', 'sponsorship', 'micro-influencer', 'macro', 'disclosure', 'gifted', 'affiliate', 'engagement rate', 'roi', 'brief'],
        related: ['marketing', 'social media', 'content'],
        synonyms: ['creator marketing', 'influencer partnerships'],
        intents: ['finding creators', 'running campaigns', 'measuring roi'],
        starters: ['How do I find the right influencers?', 'What is a micro-influencer?', 'How do I brief a creator?', 'What are FTC disclosure rules?'],
      },
      Analytics: {
        expertise: ['marketing analytics', 'ga4', 'metrics', 'dashboards', 'testing'],
        welcome: 'Marketing analytics question? Ask about tools, metrics, or testing.',
        allowed: ['marketing analytics', 'analytics', 'ga4', 'google analytics', 'metrics', 'kpi', 'dashboard', 'reporting', 'cohort', 'attribution', 'experiment', 'a/b test', 'conversion', 'funnel analysis', 'data'],
        related: ['marketing', 'data', 'business'],
        synonyms: ['growth analytics', 'marketing measurement'],
        intents: ['setting up analytics', 'building dashboards', 'running tests'],
        starters: ['How do I set up GA4?', 'What are the most important marketing KPIs?', 'How do I run an A/B test?', 'What is cohort analysis?'],
      },
      'Growth Hacking': {
        expertise: ['growth hacking', 'experiments', 'virality', 'retention', 'loops'],
        welcome: 'Growth hacking question? Ask about experiments, loops, or retention.',
        allowed: ['growth hacking', 'growth', 'experiment', 'virality', 'referral', 'retention', 'activation', 'onboarding', 'a/b', 'north star', 'pirate metrics', 'aarrr', 'loop', 'product-led', 'growth team'],
        related: ['marketing', 'product', 'startups'],
        synonyms: ['growth marketing', 'experimentation'],
        intents: ['running experiments', 'building referral loops', 'improving retention'],
        starters: ['What is the AARRR framework?', 'How do I build a referral loop?', 'What is a north star metric?', 'How do I run growth experiments?'],
      },
    },
  },
};
