// ============================================================
// SCARLET DOMAIN KNOWLEDGE — PART 2
// Each specialty: expertise, welcome, allowed, related,
// synonyms, intents, starters (+ optional disclaimer).
// ============================================================

export const DOMAIN_PART2 = {
  Finance: {
    themes: ['Royal', 'Slate', 'Mono', 'Ocean'],
    specialties: {
      Investing: {
        expertise: ['stock market basics', 'fundamental analysis', 'portfolio building', 'risk management', 'dividends', 'long-term investing'],
        welcome: 'Let’s talk investing — educational, not personalized advice.',
        allowed: ['investing', 'invest', 'stock', 'stocks', 'share', 'equity', 'portfolio', 'dividend', 'index fund', 'etf', 'mutual fund', 'risk', 'diversify', 'diversification', 'asset allocation', 'bear market', 'bull market', 'p/e ratio', 'market cap', 'broker', 'compound'],
        related: ['retirement', 'trading', 'economics'],
        synonyms: ['wealth building', 'asset investing'],
        intents: ['building a portfolio', 'understanding stocks', 'managing risk'],
        starters: ['How do I start investing with a small amount?', 'What is dollar-cost averaging?', 'How do I analyze a stock?', 'What is a balanced portfolio?'],
        disclaimer: true,
      },
      Budgeting: {
        expertise: ['budgets', 'expense tracking', 'saving strategies', 'emergency funds', 'debt payoff'],
        welcome: 'Let’s get your money organized — ask me about budgeting and saving.',
        allowed: ['budget', 'budgeting', 'expense', 'expenses', 'spending', 'saving', 'savings', 'emergency fund', 'debt', 'payoff', 'envelope', 'track', 'income', 'rent', 'bills', 'subscription', 'goal', 'frugal', '50/30/20', 'pay yourself first'],
        related: ['banking', 'personal finance', 'money'],
        synonyms: ['money management', 'personal budgeting'],
        intents: ['making a budget', 'cutting expenses', 'building savings'],
        starters: ['How do I create a budget from scratch?', 'What is the 50/30/20 rule?', 'How much should I save for emergencies?', 'How do I pay off debt faster?'],
        disclaimer: true,
      },
      Crypto: {
        expertise: ['bitcoin and ethereum', 'blockchain basics', 'wallets and exchanges', 'risks', 'defi'],
        welcome: 'Crypto question? Let’s cover the fundamentals and the risks.',
        allowed: ['crypto', 'cryptocurrency', 'bitcoin', 'ethereum', 'blockchain', 'wallet', 'exchange', 'mining', 'defi', 'nft', 'token', 'altcoin', 'staking', 'ledger', 'smart contract', 'gas fee', 'volatility', 'cold storage', 'private key'],
        related: ['finance', 'technology', 'trading'],
        synonyms: ['digital currency', 'virtual currency'],
        intents: ['understanding bitcoin', 'choosing a wallet', 'learning about risks'],
        starters: ['What is Bitcoin, simply?', 'How do I buy my first cryptocurrency?', 'What is a blockchain?', 'How do I keep crypto safe?'],
        disclaimer: true,
      },
      Taxes: {
        expertise: ['income tax basics', 'deductions', 'filing', 'tax brackets', 'self-employment tax'],
        welcome: 'Tax questions? I can explain the general concepts.',
        allowed: ['tax', 'taxes', 'income tax', 'return', 'filing', 'deduction', 'credit', 'bracket', 'refund', 'w-2', '1099', 'self-employed', 'gst', 'vat', 'property tax', 'capital gains', 'ira', '401k', 'withholding', 'taxable', 'exempt'],
        related: ['finance', 'accounting', 'law'],
        synonyms: ['taxation', 'fiscal'],
        intents: ['understanding taxes', 'finding deductions', 'preparing to file'],
        starters: ['How do tax brackets work?', 'What deductions can I claim?', 'Self-employed: what do I need to know about taxes?', 'What is the difference between a credit and a deduction?'],
        disclaimer: true,
      },
      Retirement: {
        expertise: ['retirement accounts', '401k and IRA', 'pension plans', 'retirement planning', 'social security'],
        welcome: 'Planning for retirement? Ask me about accounts and strategies.',
        allowed: ['retirement', 'retire', '401k', 'ira', 'roth', 'pension', 'social security', 'annuity', 'nest egg', 'withdrawal', 'rrsa', 'superannuation', 'retirement planning', 'early retirement', 'drawdown', 'contribution', 'match'],
        related: ['investing', 'finance', 'insurance'],
        synonyms: ['pension planning', 'golden years'],
        intents: ['choosing retirement accounts', 'planning for retirement', 'understanding withdrawals'],
        starters: ['What is the difference between a 401k and an IRA?', 'How much should I save for retirement?', 'What is the Roth vs traditional debate?', 'When can I withdraw from retirement accounts?'],
        disclaimer: true,
      },
      'Real Estate Investment': {
        expertise: ['rental properties', 'REITs', 'property valuation', 'flipping', 'mortgage leverage'],
        welcome: 'Curious about investing in property? Ask me about the basics.',
        allowed: ['real estate', 'property', 'investment property', 'rental', 'landlord', 'reit', 'flip', 'appreciation', 'mortgage', 'down payment', 'cash flow', 'cap rate', 'equity', 'leverage', 'tenant', 'property value', 'condo', 'house hacking'],
        related: ['finance', 'real estate', 'investing'],
        synonyms: ['property investing', 'realty'],
        intents: ['understanding rental income', 'comparing REITs', 'buying investment property'],
        starters: ['What is a REIT?', 'How do I calculate cash flow on a rental?', 'What is the 1% rule in real estate?', 'Rentals vs REITs — which is better?'],
        disclaimer: true,
      },
      Trading: {
        expertise: ['day trading', 'technical analysis', 'charts', 'options', 'risk', 'order types'],
        welcome: 'Trading question? I can explain the mechanics and risks.',
        allowed: ['trading', 'trader', 'day trading', 'technical analysis', 'chart', 'candlestick', 'moving average', 'support', 'resistance', 'option', 'options', 'call', 'put', 'margin', 'lever', 'position', 'stop loss', 'take profit', 'order', 'market order', 'limit order', 'forex'],
        related: ['investing', 'finance', 'economics'],
        synonyms: ['speculation', 'market trading'],
        intents: ['learning technical analysis', 'understanding options', 'managing risk'],
        starters: ['What is the difference between investing and trading?', 'How do I read a candlestick chart?', 'What are options, simply?', 'How do I set a stop loss?'],
        disclaimer: true,
      },
    },
  },

  'Food & Cooking': {
    themes: ['Sunset', 'Amber', 'Forest', 'Mono'],
    specialties: {
      Italian: {
        expertise: ['pasta', 'pizza', 'sauces', 'regional italian food', 'antipasti', 'desserts'],
        welcome: 'Italian cooking! What would you like to make or learn?',
        allowed: ['italian', 'italy', 'pasta', 'spaghetti', 'pizza', 'risotto', 'sauce', 'marinara', 'bolognese', 'pesto', 'carbonara', 'lasagna', 'gnocchi', 'tiramisu', 'gelato', 'parmesan', 'mozzarella', 'bruschetta', 'olive oil', 'basil', 'tomato'],
        related: ['cooking', 'recipes', 'ingredients'],
        synonyms: ['italian cuisine', 'trattoria'],
        intents: ['making pasta', 'making pizza dough', 'learning italian recipes'],
        starters: ['How do I make authentic carbonara?', 'What is the best way to make pizza dough?', 'Fresh vs dried pasta — does it matter?', 'How do I make a proper risotto?'],
      },
      Indian: {
        expertise: ['curries', 'spices', 'breads', 'rice dishes', 'regional indian food', 'vegetarian dishes'],
        welcome: 'Indian cooking! Ask me about spices, curries, or breads.',
        allowed: ['indian', 'india', 'curry', 'spice', 'spices', 'masala', 'turmeric', 'cumin', 'coriander', 'garam masala', 'tikka', 'biryani', 'naan', 'roti', 'paratha', 'dal', 'lentil', 'chutney', 'tandoor', 'paneer', 'samosa', 'korma'],
        related: ['cooking', 'spices', 'recipes'],
        synonyms: ['indian cuisine', 'desi food'],
        intents: ['making a curry', 'understanding spices', 'cooking indian breads'],
        starters: ['How do I make a rich butter chicken?', 'What spices do I need for Indian cooking?', 'How do I get the right naan texture?', 'What is the difference between garam masala and curry powder?'],
      },
      Chinese: {
        expertise: ['stir-frying', 'wok techniques', 'noodles', 'dumplings', 'sauces', 'regional chinese food'],
        welcome: 'Chinese cooking! Ask me about stir-fries, noodles, or dumplings.',
        allowed: ['chinese', 'china', 'stir fry', 'stir-fry', 'wok', 'noodle', 'noodles', 'dumpling', 'spring roll', 'fried rice', 'soy sauce', 'hoisin', 'oyster sauce', 'szechuan', 'sichuan', 'kung pao', 'dim sum', 'bao', 'scallion', 'ginger', 'sesame oil'],
        related: ['cooking', 'recipes', 'wok'],
        synonyms: ['chinese cuisine', 'cantonese'],
        intents: ['stir-frying properly', 'making dumplings', 'using a wok'],
        starters: ['How do I get a proper wok hei?', 'How do I fold dumplings?', 'What is the difference between Szechuan and Cantonese food?', 'How do I make fried rice that is not mushy?'],
      },
      Mexican: {
        expertise: ['tacos', 'salsas', 'guacamole', 'tortillas', 'mexican flavors', 'regional dishes'],
        welcome: 'Mexican cooking! Ask me about tacos, salsas, or tortillas.',
        allowed: ['mexican', 'mexico', 'taco', 'tacos', 'salsa', 'guacamole', 'tortilla', 'burrito', 'quesadilla', 'enchilada', 'chili', 'cilantro', 'lime', 'jalapeño', 'corn', 'beans', 'fajita', 'mole', 'tamale', 'nachos', 'street corn'],
        related: ['cooking', 'recipes', 'spices'],
        synonyms: ['mexican cuisine', 'tex-mex'],
        intents: ['making tortillas', 'making salsa', 'building a taco bar'],
        starters: ['How do I make fresh corn tortillas?', 'What makes a great salsa?', 'How do I make guacamole that stays green?', 'What is the difference between Mexican and Tex-Mex?'],
      },
      Baking: {
        expertise: ['bread', 'cakes', 'pastry', 'cookies', 'yeast', 'baking science', 'decorating'],
        welcome: 'Baking questions? Ask about breads, cakes, or pastry.',
        allowed: ['baking', 'bake', 'bread', 'cake', 'cookies', 'pastry', 'dough', 'yeast', 'flour', 'gluten', 'rise', 'proof', 'oven', 'temperature', 'butter', 'sugar', 'eggs', 'meringue', 'pie', 'tart', 'sourdough', 'brownie', 'cupcake', 'icing'],
        related: ['cooking', 'kitchen', 'ingredients'],
        synonyms: ['bakehouse', 'patisserie'],
        intents: ['baking bread', 'making cakes', 'troubleshooting baking'],
        starters: ['Why did my bread not rise?', 'How do I make a flaky pie crust?', 'What is the difference between baking soda and baking powder?', 'How do I start a sourdough starter?'],
      },
      Vegan: {
        expertise: ['plant-based cooking', 'meat alternatives', 'dairy-free', 'vegan baking', 'protein sources'],
        welcome: 'Vegan cooking! Ask me about substitutes, meals, and nutrition.',
        allowed: ['vegan', 'plant-based', 'plant based', 'vegetarian', 'tofu', 'tempeh', 'seitan', 'jackfruit', 'nutritional yeast', 'cashew cream', 'oat milk', 'almond milk', 'dairy-free', 'egg-free', 'meat alternative', 'beyond meat', 'impossible', 'lentil', 'chickpea', 'vegan cheese'],
        related: ['nutrition', 'cooking', 'recipes'],
        synonyms: ['plant-based cooking', 'cruelty-free food'],
        intents: ['replacing eggs', 'cooking tofu', 'getting protein'],
        starters: ['How do I cook tofu so it is not bland?', 'What can I use instead of eggs in baking?', 'How do I get enough protein as a vegan?', 'What is a good vegan substitute for cheese?'],
      },
      'Meal Prep': {
        expertise: ['weekly meal prep', 'batch cooking', 'meal planning', 'storage', 'portable meals'],
        welcome: 'Meal prep question? Let’s plan efficient, tasty weeks.',
        allowed: ['meal prep', 'meal planning', 'batch cook', 'batch cooking', 'prepare', 'planning', 'leftover', 'container', 'refrigerate', 'freeze', 'reheat', 'weekend prep', 'portion', 'lunchbox', 'grab and go', 'marinade', 'prep day', 'cook once', 'freezer meal'],
        related: ['nutrition', 'cooking', 'budget'],
        synonyms: ['batch cooking', 'food prep'],
        intents: ['planning a week of meals', 'batch cooking', 'storing meals'],
        starters: ['How do I meal prep for a week?', 'What foods freeze well?', 'How do I keep meal prep interesting?', 'What is the best way to store prepared meals?'],
      },
      Wine: {
        expertise: ['wine basics', 'pairing', 'serving', 'storage', 'buying'],
        welcome: 'Wine questions? Ask about pairing, storage, or choosing a bottle.',
        allowed: ['wine', 'red wine', 'white wine', 'rosé', 'sparkling', 'champagne', 'pairing', 'food pairing', 'tannin', 'dry', 'sweet', 'sommelier', 'vintage', 'decant', 'aerate', 'cork', 'bottle', 'cellar', 'temperature', 'varietal', 'cabernet', 'pinot', 'chardonnay', 'sauvignon'],
        related: ['food', 'dining', 'hospitality'],
        synonyms: ['oenology', 'viticulture'],
        intents: ['pairing wine', 'storing wine', 'choosing wine'],
        starters: ['What wine should I serve with pasta?', 'How long does an open bottle last?', 'What does "tannic" mean?', 'How do I choose a good bottle under $20?'],
      },
      Coffee: {
        expertise: ['brewing methods', 'espresso', 'beans and roasts', 'grinding', 'latte art', 'equipment'],
        welcome: 'Coffee lover? Ask me about brewing, beans, or equipment.',
        allowed: ['coffee', 'espresso', 'latte', 'cappuccino', 'beans', 'roast', 'grind', 'grinder', 'brewing', 'pour over', 'french press', 'aeropress', 'moka pot', 'drip', 'extraction', 'crema', 'milk', 'steaming', 'barista', 'decaf', 'single origin', 'arabica', 'robusta'],
        related: ['beverages', 'food', 'dining'],
        synonyms: ['java', 'brew'],
        intents: ['brewing better coffee', 'choosing beans', 'making espresso'],
        starters: ['What is the best brewing method for beginners?', 'How do I dial in espresso?', 'Whole bean vs ground — does it matter?', 'What does "single origin" mean?'],
      },
      'Food Safety': {
        expertise: ['storage', 'cross-contamination', 'safe temperatures', 'expiry', 'hygiene'],
        welcome: 'Ask me about safe food handling and storage.',
        allowed: ['food safety', 'food poisoning', 'storage', 'refrigerate', 'freeze', 'thaw', 'cross-contamination', 'temperature', 'expiry', 'expiration', 'best before', 'hygiene', 'sanitize', 'raw', 'undercooked', 'shelf life', 'leftover', 'reheat', 'danger zone'],
        related: ['kitchen', 'health', 'cooking'],
        synonyms: ['food hygiene'],
        intents: ['storing food safely', 'avoiding contamination', 'understanding dates'],
        starters: ['How long can leftovers stay in the fridge?', 'What is the danger zone?', 'How do I thaw meat safely?', 'Can I eat food past its best-before date?'],
      },
    },
  },

  Travel: {
    themes: ['Ocean', 'Sunset', 'Forest'],
    specialties: {
      Europe: {
        expertise: ['european destinations', 'eurail', 'schengen', 'european itineraries', 'city breaks'],
        welcome: 'Planning a European trip? Ask me about destinations and logistics.',
        allowed: ['europe', 'european', 'paris', 'rome', 'london', 'barcelona', 'amsterdam', 'berlin', 'prague', 'lisbon', 'eurail', 'train', 'schengen', 'itinerary', 'city break', 'budget', 'hostel', 'walking tour', 'louvre', 'colosseum', 'alps'],
        related: ['trip planning', 'travel', 'destinations'],
        synonyms: ['european travel'],
        intents: ['planning a europe trip', 'booking trains', 'building an itinerary'],
        starters: ['Plan a 2-week Europe itinerary', 'How does the Eurail pass work?', 'What is the Schengen visa?', 'Best budget cities in Europe?'],
      },
      Asia: {
        expertise: ['asian destinations', 'southeast asia', 'east asia', 'street food', 'backpacking'],
        welcome: 'Planning a trip to Asia? Ask me about destinations and routes.',
        allowed: ['asia', 'asian', 'japan', 'thailand', 'vietnam', 'bali', 'india', 'tokyo', 'bangkok', 'kyoto', 'backpacking', 'street food', 'temple', 'itinerary', 'hostel', 'motorbike', 'beach', 'trains', 'southeast asia', 'hong kong', 'singapore'],
        related: ['trip planning', 'travel', 'culture'],
        synonyms: ['asian travel'],
        intents: ['planning an asia trip', 'backpacking routes', 'finding food'],
        starters: ['Plan a Thailand itinerary for 10 days', 'How do I travel Japan on a budget?', 'What are the must-try street foods in Vietnam?', 'Backpacking Southeast Asia — where to start?'],
      },
      Americas: {
        expertise: ['north america', 'south america', 'usa road trips', 'canada', 'latin america'],
        welcome: 'Traveling the Americas? Ask me about routes and destinations.',
        allowed: ['america', 'americas', 'usa', 'canada', 'mexico', 'brazil', 'argentina', 'peru', 'peru machu picchu', 'new york', 'road trip', 'national park', 'yellowstone', 'chicago', 'montreal', 'buenos aires', 'rio', 'patagonia', 'banff', 'grand canyon'],
        related: ['trip planning', 'travel', 'destinations'],
        synonyms: ['american travel'],
        intents: ['planning a road trip', 'visiting national parks', 'south america travel'],
        starters: ['Plan a USA road trip itinerary', 'What are the best national parks to visit?', 'Machu Picchu — how to plan the visit?', 'Best cities in South America for backpackers?'],
      },
      'Budget Travel': {
        expertise: ['cheap flights', 'hostels', 'free attractions', 'travel hacking', 'saving money'],
        welcome: 'Want to see the world for less? Ask me how.',
        allowed: ['budget', 'cheap', 'deal', 'discount', 'hostel', 'backpacking', 'couchsurfing', 'budget travel', 'low cost', 'saving', 'fare', 'off-season', 'street food', 'free', 'walking tour', 'travel hacking', 'points', 'miles', 'student'],
        related: ['trip planning', 'flights', 'money'],
        synonyms: ['affordable travel', 'backpacker'],
        intents: ['finding cheap flights', 'saving money', 'budget planning'],
        starters: ['How do I find cheap flights?', 'What is travel hacking?', 'How do I travel cheaply long-term?', 'When is the cheapest time to fly?'],
      },
      'Luxury Travel': {
        expertise: ['luxury hotels', 'first class', 'private tours', 'resorts', 'fine dining'],
        welcome: 'Planning a luxury getaway? Ask me about hotels, flights, and experiences.',
        allowed: ['luxury', 'luxury travel', 'five-star', '5-star', 'resort', 'villa', 'first class', 'business class', 'private', 'butler', 'spa', 'suite', 'yacht', 'fine dining', 'maldives', 'santorini', 'safari', 'private tour', 'concierge'],
        related: ['travel', 'hotels', 'dining'],
        synonyms: ['premium travel', 'high-end travel'],
        intents: ['booking luxury hotels', 'planning a splurge trip', 'finding experiences'],
        starters: ['Best luxury resorts in the Maldives?', 'How do I book first class affordably?', 'What is a private safari like?', 'How do I choose a luxury cruise?'],
      },
      Adventure: {
        expertise: ['trekking', 'scuba diving', 'skiing', 'adventure sports', 'extreme travel'],
        welcome: 'Adventure travel! Ask me about treks, dives, and adrenaline.',
        allowed: ['adventure', 'trek', 'trekking', 'hiking', 'mountaineering', 'climb', 'scuba', 'diving', 'snorkel', 'ski', 'snowboard', 'kayak', 'rafting', 'bungee', 'skydive', 'paragliding', 'safari', 'camping', 'wilderness', 'solo trek'],
        related: ['travel', 'sports', 'nature'],
        synonyms: ['expedition', 'outdoor travel'],
        intents: ['planning a trek', 'learning to dive', 'finding adventure trips'],
        starters: ['Best beginner trekking routes?', 'How do I get scuba certified?', 'What should I pack for a wilderness trek?', 'Safari in Africa — what do I need to know?'],
      },
      'Solo Travel': {
        expertise: ['solo trip planning', 'safety', 'hostels', 'meeting people', 'self-guided tours'],
        welcome: 'Traveling solo? Ask me about planning, safety, and making friends.',
        allowed: ['solo', 'alone', 'single traveler', 'safety', 'hostel', 'co-working', 'meetup', 'free walking tour', 'day trip', 'self-guided', 'solo female travel', 'lonely planet', 'insurance', 'emergency', 'sim card', 'group tour'],
        related: ['travel', 'budget', 'safety'],
        synonyms: ['independent travel'],
        intents: ['planning a solo trip', 'staying safe', 'meeting people'],
        starters: ['Is solo travel safe for beginners?', 'How do I meet people while traveling solo?', 'Best first solo-travel destinations?', 'What should I never forget when traveling alone?'],
      },
      'Family Travel': {
        expertise: ['family destinations', 'kid-friendly hotels', 'theme parks', 'travel with kids'],
        welcome: 'Planning a family trip? Ask me about kid-friendly travel.',
        allowed: ['family', 'kids', 'children', 'babies', 'toddler', 'theme park', 'disney', 'resort', 'kid-friendly', 'stroller', 'diaper', 'activities', 'holiday', 'all-inclusive', 'kids club', 'cruise', 'minivan', 'snacks', 'car seat'],
        related: ['travel', 'hotels', 'budget'],
        synonyms: ['family vacation'],
        intents: ['finding family destinations', 'traveling with kids', 'planning activities'],
        starters: ['Best family-friendly destinations?', 'How do I survive a long flight with a toddler?', 'What should I pack for kids on a trip?', 'Cruise vs resort for families?'],
      },
      'Business Travel': {
        expertise: ['corporate travel', 'frequent flyer', 'meetings abroad', 'expenses', 'airport tips'],
        welcome: 'Business trip coming up? Ask me about logistics and perks.',
        allowed: ['business trip', 'business travel', 'corporate', 'meeting', 'conference', 'frequent flyer', 'miles', 'airport lounge', 'expense report', 'hotel', 'workation', 'jet lag', 'seating', 'checked bag', 'per diem', 'visa for business'],
        related: ['travel', 'business', 'flights'],
        synonyms: ['corporate travel'],
        intents: ['planning a business trip', 'using points', 'managing jet lag'],
        starters: ['How do I manage jet lag on a business trip?', 'What is the best way to use travel points for business?', 'How do I expense a business trip?', 'Best airline lounges to access?'],
      },
      'Visa & Immigration': {
        expertise: ['visa types', 'applications', 'immigration', 'residency', 'documents'],
        welcome: 'Visa or immigration question? I can explain the general process.',
        allowed: ['visa', 'visas', 'immigration', 'application', 'passport', 'residency', 'permit', 'work permit', 'student visa', 'tourist visa', 'embassy', 'consulate', 'interview', 'biometrics', 'processing time', 'extension', 'overstay', 'green card', 'pr'],
        related: ['travel', 'legal', 'documents'],
        synonyms: ['entry permit', 'immigration process'],
        intents: ['applying for a visa', 'understanding requirements', 'extension of stay'],
        starters: ['How do I apply for a tourist visa?', 'What documents do I need for a work visa?', 'How long does a visa take to process?', 'What happens if I overstay my visa?'],
        disclaimer: true,
      },
    },
  },

  Sports: {
    themes: ['Emerald', 'Midnight', 'Amber'],
    specialties: {
      Football: {
        expertise: ['football tactics', 'teams and leagues', 'player roles', 'rules', 'training'],
        welcome: 'Football question? Ask about tactics, rules, or the beautiful game.',
        allowed: ['football', 'soccer', 'premier league', 'champions league', 'world cup', 'tactics', 'formation', 'offside', 'penalty', 'free kick', 'defender', 'midfielder', 'striker', 'goalkeeper', 'dribbling', 'passing', 'training', 'transfer', 'manager', 'match'],
        related: ['sports', 'fitness', 'training'],
        synonyms: ['soccer', 'the beautiful game'],
        intents: ['understanding rules', 'learning tactics', 'improving skills'],
        starters: ['How does the offside rule work?', 'What is the best formation for beginners?', 'How do I improve my first touch?', 'How do transfer windows work?'],
      },
      Basketball: {
        expertise: ['basketball fundamentals', 'NBA', 'plays', 'rules', 'training'],
        welcome: 'Basketball question? Ask about skills, rules, or the NBA.',
        allowed: ['basketball', 'nba', 'nba finals', 'dribbling', 'shooting', 'layup', 'three-pointer', 'rebound', 'assist', 'defense', 'zone', 'man-to-man', 'foul', 'traveling', 'double dribble', 'playoff', 'draft', 'leBron', 'curry'],
        related: ['sports', 'fitness', 'training'],
        synonyms: ['hoops', 'b-ball'],
        intents: ['improving shooting', 'understanding rules', 'learning plays'],
        starters: ['How do I improve my jump shot?', 'What is the difference between zone and man defense?', 'How do NBA playoffs work?', 'How do I increase my vertical jump?'],
      },
      Cricket: {
        expertise: ['cricket rules', 'batting', 'bowling', 'formats', 'teams and players'],
        welcome: 'Cricket question? Ask about formats, technique, or the game.',
        allowed: ['cricket', 'test match', 'odi', 't20', 'ipl', 'batting', 'bowling', 'fielding', 'wicket', 'run', 'over', 'spin', 'pace', 'swing', 'powerplay', 'wicketkeeper', 'all-rounder', 'captain', 'ashes', 'world cup'],
        related: ['sports', 'training', 'fitness'],
        synonyms: ['the gentleman game'],
        intents: ['understanding formats', 'improving batting', 'learning bowling'],
        starters: ['What is the difference between Test, ODI, and T20?', 'How do I improve my batting stance?', 'How does swing bowling work?', 'What is the Duckworth-Lewis method?'],
      },
      Tennis: {
        expertise: ['tennis strokes', 'rules', 'grand slams', 'strategy', 'training'],
        welcome: 'Tennis question? Ask about strokes, rules, or the tour.',
        allowed: ['tennis', 'grand slam', 'wimbledon', 'serve', 'forehand', 'backhand', 'volley', 'lob', 'deuce', 'advantage', 'tie-break', 'fault', 'double fault', 'rally', 'baseline', 'net play', 'racket', 'grip', 'court'],
        related: ['sports', 'fitness', 'training'],
        synonyms: ['lawn tennis'],
        intents: ['improving strokes', 'understanding scoring', 'learning strategy'],
        starters: ['How does tennis scoring work?', 'How do I improve my serve?', 'What grip should I use for forehand?', 'How do I play against a net player?'],
      },
      Swimming: {
        expertise: ['swimming strokes', 'technique', 'breathing', 'training', 'open water'],
        welcome: 'Swimming question? Ask about strokes, breathing, or training.',
        allowed: ['swimming', 'swim', 'freestyle', 'breaststroke', 'backstroke', 'butterfly', 'breathing', 'flip turn', 'kick', 'pull', 'lane', 'pool', 'open water', 'drowning', 'buoyancy', 'stroke rate', 'distance', 'triathlon swim'],
        related: ['sports', 'fitness', 'safety'],
        synonyms: ['aquatics', 'lap swimming'],
        intents: ['learning a stroke', 'improving breathing', 'building endurance'],
        starters: ['How do I learn freestyle breathing?', 'What is the correct body position in swimming?', 'How do I improve my kick?', 'How do I train for open water swimming?'],
      },
      Running: {
        expertise: ['running form', 'training plans', 'marathons', 'pace', 'injury prevention'],
        welcome: 'Running question? Ask about form, plans, or races.',
        allowed: ['running', 'run', 'runner', 'marathon', 'half marathon', '5k', '10k', 'pace', 'cadence', 'sprint', 'jog', 'trail running', 'interval', 'tempo run', 'long run', 'recovery', 'shoes', 'gait', 'shin splints', 'hydration'],
        related: ['sports', 'fitness', 'health'],
        synonyms: ['jogging', 'distance running'],
        intents: ['training for a race', 'improving pace', 'preventing injuries'],
        starters: ['How do I train for my first 5k?', 'What is the best running cadence?', 'How do I avoid shin splints?', 'What is a tempo run?'],
      },
      Yoga: {
        expertise: ['yoga poses', 'breathing', 'flow sequences', 'flexibility', 'meditation'],
        welcome: 'Yoga question? Ask about poses, breathing, or sequences.',
        allowed: ['yoga', 'pose', 'asana', 'sun salutation', 'downward dog', 'warrior', 'breathing', 'pranayama', 'meditation', 'flexibility', 'balance', 'flow', 'vinyasa', 'hatha', 'restorative', 'mats', 'alignment', 'chakra'],
        related: ['fitness', 'wellness', 'mental health'],
        synonyms: ['asana practice'],
        intents: ['learning poses', 'building a sequence', 'improving flexibility'],
        starters: ['What are the best poses for beginners?', 'How do I do a proper downward dog?', 'How often should I practice yoga?', 'What is the difference between Hatha and Vinyasa?'],
      },
      'Gym & Fitness': {
        expertise: ['workout splits', 'strength training', 'machine vs free weights', 'form', 'programming'],
        welcome: 'Gym question? Ask about programs, form, or exercises.',
        allowed: ['gym', 'workout', 'strength', 'muscle', 'bench press', 'squat', 'deadlift', 'bicep curl', 'shoulder press', 'machine', 'free weights', 'dumbbell', 'barbell', 'split', 'push pull', 'leg day', 'protein', 'creatine', 'bulking', 'cutting', 'reps'],
        related: ['fitness', 'nutrition', 'health'],
        synonyms: ['weight training', 'bodybuilding'],
        intents: ['building a program', 'improving form', 'understanding nutrition'],
        starters: ['How do I structure a workout split?', 'Free weights vs machines?', 'How much protein do I need to build muscle?', 'What is the difference between bulking and cutting?'],
      },
      'Martial Arts': {
        expertise: ['martial arts styles', 'techniques', 'training', 'self-defense', 'belt ranks'],
        welcome: 'Martial arts question? Ask about styles, techniques, or training.',
        allowed: ['martial arts', 'karate', 'taekwondo', 'judo', 'jiu-jitsu', 'bjj', 'muay thai', 'boxing', 'kickboxing', 'wrestling', 'kung fu', 'self-defense', 'belt', 'sparring', 'pad work', 'guard', 'mount', 'striking', 'grappling'],
        related: ['sports', 'fitness', 'self-defense'],
        synonyms: ['combat sports', 'mma'],
        intents: ['choosing a style', 'learning techniques', 'training for self-defense'],
        starters: ['Which martial art should I start with?', 'What is the difference between BJJ and judo?', 'How do I improve my footwork in boxing?', 'How long does it take to get a black belt?'],
      },
      Cycling: {
        expertise: ['cycling training', 'road vs mountain', 'gear', 'maintenance', 'races'],
        welcome: 'Cycling question? Ask about training, gear, or maintenance.',
        allowed: ['cycling', 'bike', 'bicycle', 'road bike', 'mountain bike', 'gravel', 'cadence', 'power', 'training', 'group ride', 'sprint', 'climbing', 'aero', 'gears', 'shift', 'chain', 'tire', 'tubeless', 'helmet', 'tour de france', 'peloton'],
        related: ['sports', 'fitness', 'automotive'],
        synonyms: ['biking', 'spinning'],
        intents: ['training for cycling', 'buying a bike', 'fixing a bike'],
        starters: ['How do I choose my first road bike?', 'How do I train for a century ride?', 'How do I fix a flat tire?', 'What is the difference between aero and climbing bikes?'],
      },
    },
  },

  Entertainment: {
    themes: ['Sunset', 'Crimson', 'Mono'],
    specialties: {
      Movies: {
        expertise: ['film genres', 'directors', 'film analysis', 'classics', 'streaming'],
        welcome: 'Movie question? Ask about genres, directors, or what to watch.',
        allowed: ['movie', 'movies', 'film', 'films', 'cinema', 'director', 'oscar', 'genre', 'documentary', 'thriller', 'horror', 'comedy', 'drama', 'action', 'sci-fi', 'netflix', 'streaming', 'screenplay', 'editing', 'cinematography', 'sequel', 'trailer'],
        related: ['entertainment', 'tv', 'art'],
        synonyms: ['cinema', 'motion pictures'],
        intents: ['finding a movie to watch', 'understanding a director', 'analyzing a film'],
        starters: ['What should I watch tonight?', 'Explain the difference between hard and soft sci-fi', 'Who are the greatest directors of all time?', 'How do I analyze a film?'],
      },
      Music: {
        expertise: ['genres', 'artists', 'albums', 'music theory basics', 'playlists'],
        welcome: 'Music question? Ask about genres, artists, or albums.',
        allowed: ['music', 'song', 'album', 'artist', 'genre', 'rock', 'pop', 'jazz', 'hip-hop', 'classical', 'electronic', 'indie', 'band', 'singer', 'lyrics', 'concert', 'playlist', 'spotify', 'vinyl', 'music video', 'chart'],
        related: ['entertainment', 'culture', 'arts'],
        synonyms: ['melody', 'tunes'],
        intents: ['discovering new music', 'understanding a genre', 'building a playlist'],
        starters: ['How do I get into jazz?', 'What is the difference between pop and indie?', 'Build me a workout playlist', 'What are the best concept albums?'],
      },
      Gaming: {
        expertise: ['video games', 'consoles', 'game reviews', 'genres', 'gaming culture'],
        welcome: 'Gaming question? Ask about games, consoles, or genres.',
        allowed: ['video game', 'video games', 'gaming', 'console', 'playstation', 'xbox', 'nintendo', 'switch', 'steam', 'pc gaming', 'genre', 'rpg', 'shooter', 'indie', 'triple-a', 'aaa', 'game review', 'story', 'multiplayer', 'co-op', 'esports', 'retro'],
        related: ['entertainment', 'technology', 'culture'],
        synonyms: ['gaming culture', 'playing games'],
        intents: ['finding a game', 'comparing consoles', 'understanding genres'],
        starters: ['What games should I play if I love RPGs?', 'PS5 vs Xbox Series X?', 'What are the best indie games?', 'How do I get into retro gaming?'],
      },
      Books: {
        expertise: ['book genres', 'reading recommendations', 'authors', 'book clubs', 'bestsellers'],
        welcome: 'Book question? Ask for recommendations or reading tips.',
        allowed: ['book', 'books', 'novel', 'fiction', 'nonfiction', 'genre', 'author', 'bestseller', 'book club', 'reading', 'page-turner', 'fantasy', 'mystery', 'romance', 'biography', 'self-help', 'paperback', 'kindle', 'audiobook', 'library'],
        related: ['entertainment', 'literature', 'culture'],
        synonyms: ['reading', 'literature'],
        intents: ['getting recommendations', 'choosing a book', 'joining a book club'],
        starters: ['What should I read if I like thrillers?', 'What is the best fantasy series for beginners?', 'How do I start reading more?', 'Paperbacks vs audiobooks?'],
      },
      'TV Shows': {
        expertise: ['tv series', 'streaming shows', 'binge-worthy', 'episodes', 'finales'],
        welcome: 'TV question? Ask about series, streaming, or what to binge.',
        allowed: ['tv show', 'tv shows', 'series', 'episode', 'season', 'finale', 'netflix', 'hulu', 'hbo', 'disney plus', 'amazon prime', 'bingewatch', 'binge', 'sitcom', 'drama series', 'miniseries', 'reality tv', 'premiere', 'recap'],
        related: ['entertainment', 'movies', 'culture'],
        synonyms: ['television', 'streaming series'],
        intents: ['finding a series', 'binge-watching', 'discussing episodes'],
        starters: ['What is the best show on Netflix right now?', 'What are the greatest TV finales ever?', 'Recommend a miniseries under 10 episodes', 'What is a good sitcom to relax to?'],
      },
      Anime: {
        expertise: ['anime series', 'manga', 'studios', 'genres', 'beginner recommendations'],
        welcome: 'Anime question? Ask about series, manga, or where to start.',
        allowed: ['anime', 'manga', 'series', 'episode', 'studio ghibli', 'shonen', 'shounen', 'slice of life', 'mecha', 'isekai', 'crunchyroll', 'manga', 'light novel', 'waifu', 'opening', 'dub', 'sub', 'cosplay', 'fandom'],
        related: ['entertainment', 'japan', 'art'],
        synonyms: ['japanese animation', 'cartoons'],
        intents: ['finding an anime', 'understanding genres', 'starting manga'],
        starters: ['Where should I start with anime?', 'What is the difference between shonen and seinen?', 'Best Studio Ghibli movies?', 'Dub or sub — which should I choose?'],
      },
      Comedy: {
        expertise: ['stand-up', 'comedians', 'comedy specials', 'sketch comedy', 'improv'],
        welcome: 'Want a laugh? Ask about stand-up, specials, or comedians.',
        allowed: ['comedy', 'comedian', 'stand-up', 'standup', 'special', 'joke', 'jokes', 'sketch', 'improv', 'netflix special', 'roast', 'sitcom', 'funny', 'humor', 'punchline', 'open mic', 'laugh'],
        related: ['entertainment', 'performing arts', 'culture'],
        synonyms: ['humor', 'comedy shows'],
        intents: ['finding a comedian', 'understanding comedy styles', 'getting into stand-up'],
        starters: ['Who are the best modern comedians?', 'How do I start doing stand-up?', 'What are the best comedy specials on Netflix?', 'What is the difference between sketch and improv?'],
      },
      Theater: {
        expertise: ['plays', 'musicals', 'broadway', 'acting', 'stagecraft'],
        welcome: 'Theater question? Ask about plays, musicals, or acting.',
        allowed: ['theater', 'theatre', 'play', 'plays', 'musical', 'broadway', 'west end', 'acting', 'actor', 'director', 'stage', 'curtain', 'audition', 'monologue', 'scene', 'script', 'blocking', 'costume', 'set design', 'ticket'],
        related: ['entertainment', 'performing arts', 'culture'],
        synonyms: ['drama', 'stage'],
        intents: ['choosing a show', 'getting into acting', 'understanding theater'],
        starters: ['What is the best Broadway musical right now?', 'How do I prepare for an acting audition?', 'What is the difference between a play and a musical?', 'How do I start a career in theater?'],
      },
      Dance: {
        expertise: ['dance styles', 'choreography', 'technique', 'performance', 'dance fitness'],
        welcome: 'Dance question? Ask about styles, technique, or choreography.',
        allowed: ['dance', 'dancing', 'ballet', 'hip-hop', 'salsa', 'tango', 'jazz', 'contemporary', 'choreography', 'routine', 'freestyle', 'footwork', 'body wave', 'breakdance', 'ballroom', 'fitness', 'dancer'],
        related: ['entertainment', 'fitness', 'music'],
        synonyms: ['dancing', 'movement'],
        intents: ['learning a style', 'improving technique', 'building a routine'],
        starters: ['What dance style should I start with?', 'How do I improve my footwork?', 'How do I choreograph a routine?', 'What is the difference between jazz and contemporary?'],
      },
      Photography: {
        expertise: ['photography basics', 'cameras', 'composition', 'editing', 'genres'],
        welcome: 'Photography question? Ask about technique, gear, or editing.',
        allowed: ['photography', 'camera', 'lens', 'portrait', 'landscape', 'aperture', 'shutter', 'iso', 'exposure', 'composition', 'rule of thirds', 'lighting', 'editing', 'lightroom', 'photoshop', 'raw', 'jpeg', 'focal length', 'bokeh', 'street photography'],
        related: ['art', 'technology', 'travel'],
        synonyms: ['photo', 'shooting'],
        intents: ['improving photos', 'choosing a camera', 'learning editing'],
        starters: ['What camera should a beginner buy?', 'How does the exposure triangle work?', 'How do I take better portraits?', 'What is the difference between RAW and JPEG?'],
      },
    },
  },

  Business: {
    themes: ['Royal', 'Slate', 'Mono'],
    specialties: {
      Marketing: {
        expertise: ['marketing strategy', 'campaigns', 'branding', 'positioning', 'funnel'],
        welcome: 'Marketing question? Ask about strategy, campaigns, or branding.',
        allowed: ['marketing', 'campaign', 'strategy', 'brand', 'branding', 'positioning', 'funnel', 'target audience', 'customer', 'lead', 'awareness', 'conversion', 'loyalty', 'content', 'advertising', 'seo', 'social media', 'marketing plan'],
        related: ['sales', 'brand', 'strategy'],
        synonyms: ['advertising', 'brand building'],
        intents: ['building a marketing plan', 'understanding branding', 'running campaigns'],
        starters: ['How do I build a marketing plan?', 'What is brand positioning?', 'How do I create a marketing funnel?', 'What is the difference between marketing and advertising?'],
      },
      Sales: {
        expertise: ['sales process', 'negotiation', 'closing', 'pipeline', 'B2B and B2C'],
        welcome: 'Sales question? Ask about process, negotiation, or closing.',
        allowed: ['sales', 'selling', 'salesperson', 'pipeline', 'prospecting', 'lead', 'negotiation', 'closing', 'deal', 'objection', 'quote', 'proposal', 'follow-up', 'b2b', 'b2c', 'upsell', 'cross-sell', 'cold call', 'email outreach', 'crm'],
        related: ['marketing', 'business', 'communication'],
        synonyms: ['selling', 'revenue'],
        intents: ['improving closing', 'handling objections', 'building a pipeline'],
        starters: ['How do I handle price objections?', 'What is a good sales pitch structure?', 'How do I build a sales pipeline?', 'Cold calling — any tips?'],
      },
      HR: {
        expertise: ['hiring', 'onboarding', 'employee relations', 'performance management', 'compensation'],
        welcome: 'HR question? Ask about hiring, onboarding, or workplace culture.',
        allowed: ['hr', 'human resources', 'hiring', 'recruiting', 'interview', 'resume', 'onboarding', 'employee', 'performance review', 'culture', 'compensation', 'benefits', 'retention', 'training', 'policy', 'termination', 'engagement', 'remote work'],
        related: ['business', 'management', 'law'],
        synonyms: ['people ops', 'talent'],
        intents: ['improving hiring', 'managing performance', 'building culture'],
        starters: ['How do I write a great job description?', 'What are good interview questions?', 'How do I run a performance review?', 'How do I improve employee retention?'],
      },
      Leadership: {
        expertise: ['leadership styles', 'team building', 'decision making', 'communication', 'management'],
        welcome: 'Leadership question? Ask about styles, teams, or decisions.',
        allowed: ['leadership', 'leader', 'team', 'management', 'delegation', 'motivation', 'feedback', 'decision making', 'vision', 'coaching', 'mentoring', 'conflict', 'culture', 'accountability', 'agile', '1-on-1', 'strategy'],
        related: ['business', 'management', 'psychology'],
        synonyms: ['management', 'people leadership'],
        intents: ['improving leadership', 'building teams', 'making decisions'],
        starters: ['What are the main leadership styles?', 'How do I give effective feedback?', 'How do I delegate better?', 'How do I run a good 1-on-1?'],
      },
      Entrepreneurship: {
        expertise: ['startups', 'business plans', 'fundraising', 'pitching', 'scaling'],
        welcome: 'Startup question? Ask about ideas, plans, or fundraising.',
        allowed: ['startup', 'startups', 'entrepreneur', 'entrepreneurship', 'business plan', 'fundraising', 'pitch', 'investor', 'venture capital', 'seed', 'incubator', 'accelerator', 'mvp', 'prototype', 'scaling', 'burn rate', 'runway', 'co-founder', 'lean startup'],
        related: ['business', 'finance', 'strategy'],
        synonyms: ['founding', 'startups'],
        intents: ['validating an idea', 'building a plan', 'raising money'],
        starters: ['How do I validate a startup idea?', 'What goes in a business plan?', 'How do I pitch to investors?', 'What is a lean startup approach?'],
      },
      'Project Management': {
        expertise: ['project planning', 'agile and scrum', 'scheduling', 'risk management', 'tools'],
        welcome: 'Project management question? Ask about planning, agile, or risk.',
        allowed: ['project management', 'project', 'agile', 'scrum', 'sprint', 'kanban', 'timeline', 'schedule', 'milestone', 'deadline', 'stakeholder', 'risk', 'budget', 'scope', 'deliverable', 'gantt', 'jira', 'trello', 'waterfall', 'retrospective'],
        related: ['business', 'operations', 'strategy'],
        synonyms: ['pm', 'program management'],
        intents: ['planning a project', 'running sprints', 'managing risk'],
        starters: ['What is the difference between Agile and Waterfall?', 'How do I run a sprint?', 'How do I manage project risk?', 'What is a Gantt chart?'],
      },
      Consulting: {
        expertise: ['consulting frameworks', 'client work', 'analysis', 'presentations', 'problem solving'],
        welcome: 'Consulting question? Ask about frameworks, analysis, or client work.',
        allowed: ['consulting', 'consultant', 'consultancy', 'framework', 'mckinsey', 'bain', 'boston consulting group', 'bcg', 'case interview', 'analysis', 'client', 'engagement', 'deliverable', 'presentation', 'deck', 'strategy', 'hypothesis', 'market sizing'],
        related: ['business', 'strategy', 'analytics'],
        synonyms: ['advisory', 'consultancy'],
        intents: ['using frameworks', 'doing analysis', 'preparing a deck'],
        starters: ['What are the key consulting frameworks?', 'How do I structure a case interview?', 'How do I create an executive deck?', 'What is market sizing?'],
      },
      Strategy: {
        expertise: ['business strategy', 'competitive analysis', 'SWOT', 'growth strategy', 'business model'],
        welcome: 'Strategy question? Ask about analysis, models, or growth.',
        allowed: ['strategy', 'strategic', 'swot', 'pestel', 'competitive analysis', 'porter', 'five forces', 'business model', 'growth', 'market', 'moat', 'differentiation', 'cost leadership', 'blue ocean', 'value chain', 'scenario'],
        related: ['business', 'consulting', 'economics'],
        synonyms: ['strategic planning', 'corporate strategy'],
        intents: ['building a strategy', 'doing competitive analysis', 'finding growth'],
        starters: ['What is a SWOT analysis?', 'How do Porter’s Five Forces work?', 'What is a business moat?', 'How do I build a growth strategy?'],
      },
      Operations: {
        expertise: ['process improvement', 'efficiency', 'supply chain ops', 'quality', 'KPIs'],
        welcome: 'Operations question? Ask about processes, efficiency, or KPIs.',
        allowed: ['operations', 'operations management', 'process', 'efficiency', 'optimization', 'workflow', 'kpi', 'metric', 'sla', 'lean', 'six sigma', 'quality', 'inventory', 'supply chain', 'fulfillment', 'bottleneck', 'throughput', 'automation'],
        related: ['business', 'logistics', 'management'],
        synonyms: ['ops', 'process management'],
        intents: ['improving processes', 'measuring performance', 'reducing waste'],
        starters: ['How do I optimize a business process?', 'What are the key operations KPIs?', 'What is lean operations?', 'How do I find bottlenecks in a workflow?'],
      },
      'Customer Service': {
        expertise: ['support best practices', 'communication', 'ticketing', 'customer experience', 'feedback'],
        welcome: 'Customer service question? Ask about support, tone, or experience.',
        allowed: ['customer service', 'customer support', 'support', 'ticket', 'helpdesk', 'zendesk', 'email support', 'chat', 'phone support', 'satisfaction', 'csat', 'nps', 'complaint', 'resolution', 'escalation', 'empathy', 'response time', 'knowledge base'],
        related: ['business', 'communication', 'marketing'],
        synonyms: ['support', 'client services'],
        intents: ['improving support', 'handling complaints', 'measuring satisfaction'],
        starters: ['How do I handle an angry customer?', 'What makes great customer service?', 'How do I measure CSAT and NPS?', 'How do I build a knowledge base?'],
      },
    },
  },

  Science: {
    themes: ['Slate', 'Ocean', 'Forest', 'Space'],
    specialties: {
      Astronomy: {
        expertise: ['planets', 'stars', 'galaxies', 'telescopes', 'space'],
        welcome: 'Astronomy question? Ask about planets, stars, or the cosmos.',
        allowed: ['astronomy', 'planet', 'star', 'galaxy', 'nebula', 'telescope', 'moon', 'solar system', 'orbit', 'eclipse', 'constellation', 'space', 'comet', 'asteroid', 'universe', 'light year'],
        related: ['astrophysics', 'space', 'physics'],
        synonyms: ['astronomical', 'celestial'],
        intents: ['learning about a planet', 'understanding stars', 'using a telescope'],
        starters: ['What is the largest planet?', 'How do stars form?', 'When is the next full moon?', 'How does a telescope work?'],
      },
      Physics: {
        expertise: ['mechanics', 'thermodynamics', 'electromagnetism', 'quantum', 'relativity'],
        welcome: 'Physics question? Ask about mechanics, energy, or the quantum world.',
        allowed: ['physics', 'force', 'energy', 'momentum', 'velocity', 'acceleration', 'electricity', 'magnetism', 'quantum', 'relativity', 'thermodynamics', 'wave', 'particle', 'newton', 'einstein', 'friction', 'gravity'],
        related: ['science', 'mathematics', 'astronomy'],
        synonyms: ['physical science'],
        intents: ['understanding a law', 'solving a physics problem', 'learning quantum ideas'],
        starters: ['Explain Einstein’s theory of relativity', 'What is quantum entanglement?', 'How do magnets work?', 'What is the second law of thermodynamics?'],
      },
      Chemistry: {
        expertise: ['elements', 'reactions', 'bonding', 'acids and bases', 'organic chemistry'],
        welcome: 'Chemistry question? Ask about elements, reactions, or bonding.',
        allowed: ['chemistry', 'element', 'atom', 'molecule', 'reaction', 'bond', 'acid', 'base', 'ph', 'compound', 'periodic table', 'organic', 'inorganic', 'catalyst', 'solution', 'mole', 'chemical'],
        related: ['science', 'biology', 'physics'],
        synonyms: ['chemical science'],
        intents: ['understanding an element', 'balancing reactions', 'learning bonding'],
        starters: ['What is the periodic table?', 'How do chemical bonds form?', 'What is the pH scale?', 'What is organic chemistry?'],
      },
      Biology: {
        expertise: ['cells', 'genetics', 'evolution', 'ecology', 'anatomy'],
        welcome: 'Biology question? Ask about cells, genes, or ecosystems.',
        allowed: ['biology', 'cell', 'gene', 'dna', 'evolution', 'ecosystem', 'species', 'anatomy', 'organism', 'photosynthesis', 'microbe', 'virus', 'bacteria', 'protein', 'chromosome', 'natural selection'],
        related: ['science', 'medicine', 'chemistry'],
        synonyms: ['life science', 'biological science'],
        intents: ['understanding genetics', 'learning about cells', 'understanding ecosystems'],
        starters: ['How does evolution work?', 'What is DNA?', 'How do ecosystems function?', 'What is a virus?'],
      },
      Geology: {
        expertise: ['rocks', 'minerals', 'plate tectonics', 'volcanoes', 'earthquakes'],
        welcome: 'Geology question? Ask about rocks, volcanoes, or the earth.',
        allowed: ['geology', 'rock', 'mineral', 'plate tectonics', 'volcano', 'earthquake', 'magma', 'lava', 'fault', 'erosion', 'sediment', 'fossil', 'earth', 'crust', 'mantle', 'gemstone'],
        related: ['science', 'geography', 'environment'],
        synonyms: ['earth science'],
        intents: ['identifying rocks', 'understanding volcanoes', 'learning plate tectonics'],
        starters: ['How do volcanoes form?', 'What causes earthquakes?', 'How are fossils made?', 'What is the rock cycle?'],
      },
      'Ocean Science': {
        expertise: ['oceans', 'marine life', 'currents', 'tides', 'oceanography'],
        welcome: 'Ocean question? Ask about marine life, currents, or the deep sea.',
        allowed: ['ocean', 'oceans', 'sea', 'marine', 'coral', 'reef', 'whale', 'fish', 'current', 'tide', 'deep sea', 'plankton', 'salinity', 'oceanography', 'tsunami', 'waves', 'pollution'],
        related: ['science', 'environment', 'biology'],
        synonyms: ['marine science', 'oceanography'],
        intents: ['learning about marine life', 'understanding currents', 'protecting oceans'],
        starters: ['Why is the ocean blue?', 'How do tides work?', 'What lives in the deep sea?', 'How do ocean currents affect climate?'],
      },
      Climate: {
        expertise: ['climate change', 'global warming', 'weather vs climate', 'emissions', 'solutions'],
        welcome: 'Climate question? Ask about change, warming, or solutions.',
        allowed: ['climate', 'climate change', 'global warming', 'greenhouse', 'emission', 'carbon', 'temperature', 'weather', 'extreme weather', 'sea level', 'melting', 'glacier', 'renewable', 'mitigation', 'adaptation', 'ipcc'],
        related: ['environment', 'science', 'geography'],
        synonyms: ['climate science'],
        intents: ['understanding climate change', 'learning about emissions', 'finding solutions'],
        starters: ['What is the difference between weather and climate?', 'How does the greenhouse effect work?', 'What are the main causes of global warming?', 'How can individuals reduce emissions?'],
      },
      Genetics: {
        expertise: ['genes', 'inheritance', 'mutations', 'genomics', 'genetic testing'],
        welcome: 'Genetics question? Ask about genes, inheritance, or genomics.',
        allowed: ['genetics', 'gene', 'dna', 'inheritance', 'mutation', 'chromosome', 'allele', 'dominant', 'recessive', 'genome', 'genomics', 'crispr', 'genetic testing', 'hereditary', 'trait', 'phenotype', 'genotype'],
        related: ['biology', 'medicine', 'science'],
        synonyms: ['genomics', 'heredity'],
        intents: ['understanding inheritance', 'learning about mutations', 'understanding genetic testing'],
        starters: ['How do dominant and recessive genes work?', 'What is CRISPR?', 'How does genetic testing work?', 'What is a mutation?'],
      },
      Neuroscience: {
        expertise: ['brain', 'neurons', 'synapses', 'memory', 'neurotransmitters'],
        welcome: 'Neuroscience question? Ask about the brain, neurons, or memory.',
        allowed: ['neuroscience', 'brain', 'neuron', 'synapse', 'memory', 'neurotransmitter', 'cortex', 'hippocampus', 'amygdala', 'plasticity', 'cognition', 'dopamine', 'serotonin', 'neural', 'mind'],
        related: ['science', 'psychology', 'medicine'],
        synonyms: ['neural science'],
        intents: ['understanding the brain', 'learning about memory', 'understanding neurons'],
        starters: ['How do neurons communicate?', 'What is neuroplasticity?', 'Where do memories live?', 'What do neurotransmitters do?'],
      },
      Quantum: {
        expertise: ['quantum mechanics', 'superposition', 'entanglement', 'quantum computing', 'uncertainty'],
        welcome: 'Quantum question? Ask about mechanics, computing, or the weirdness.',
        allowed: ['quantum', 'quantum mechanics', 'superposition', 'entanglement', 'qubit', 'quantum computing', 'uncertainty', 'schrodinger', 'wave function', 'photon', 'quantum field', 'observer', 'measurement', 'interference'],
        related: ['physics', 'science', 'computing'],
        synonyms: ['quantum physics'],
        intents: ['understanding quantum ideas', 'learning quantum computing', 'decoding the math'],
        starters: ['What is superposition in simple terms?', 'How does quantum computing differ from classical?', 'What is quantum entanglement?', 'What is the uncertainty principle?'],
      },
    },
  },

  Creative: {
    themes: ['Sunset', 'Grape', 'Mono'],
    specialties: {
      Writing: {
        expertise: ['creative writing', 'fiction', 'style', 'editing', 'voice'],
        welcome: 'Creative writing question? Ask about craft, style, or editing.',
        allowed: ['writing', 'creative writing', 'fiction', 'story', 'novel', 'short story', 'writer', 'voice', 'style', 'plot', 'character', 'dialogue', 'editing', 'rewrite', 'show don\'t tell', 'draft', 'publishing'],
        related: ['literature', 'art', 'communication'],
        synonyms: ['authorship', 'storytelling'],
        intents: ['improving writing', 'developing a voice', 'editing a draft'],
        starters: ['How do I develop a writer\'s voice?', 'What is "show, don\'t tell"?', 'How do I outline a novel?', 'How do I write better dialogue?'],
      },
      Painting: {
        expertise: ['painting techniques', 'mediums', 'color theory', 'brushwork', 'styles'],
        welcome: 'Painting question? Ask about technique, medium, or style.',
        allowed: ['painting', 'paint', 'artist', 'canvas', 'brush', 'oil', 'acrylic', 'watercolor', 'gouache', 'palette', 'color theory', 'composition', 'stroke', 'glazing', 'impasto', 'canvas', 'easel'],
        related: ['art', 'design', 'creative'],
        synonyms: ['fine art', 'painterly'],
        intents: ['learning a technique', 'choosing a medium', 'improving composition'],
        starters: ['Oil vs acrylic — which should I use?', 'How do I mix skin tones?', 'What is color theory?', 'How do I paint water in watercolor?'],
      },
      'Music Production': {
        expertise: ['DAWs', 'mixing', 'mastering', 'recording', 'synths', 'arrangement'],
        welcome: 'Music production question? Ask about DAWs, mixing, or arrangement.',
        allowed: ['music production', 'producer', 'daw', 'ableton', 'logic', 'fl studio', 'pro tools', 'mixing', 'mastering', 'track', 'beat', 'bass', 'synth', 'sample', 'vst', 'plugin', 'compression', 'eq', 'reverb', 'sidechain', 'arrangement', 'song', 'songs', 'arrange', 'composition'],
        related: ['music', 'technology', 'audio'],
        synonyms: ['producing', 'audio production'],
        intents: ['setting up a daw', 'learning mixing', 'building a track'],
        starters: ['Which DAW should I start with?', 'How do I mix vocals?', 'What is sidechain compression?', 'How do I arrange a song?'],
      },
      'Film Making': {
        expertise: ['filmmaking', 'directing', 'cinematography', 'editing', 'screenwriting'],
        welcome: 'Filmmaking question? Ask about directing, camera, or editing.',
        allowed: ['film making', 'filmmaking', 'director', 'cinematography', 'camera', 'shot', 'editing', 'screenplay', 'script', 'storyboard', 'lighting', 'sound', 'montage', 'framing', 'blocking', 'short film', 'camera movement'],
        related: ['movies', 'art', 'technology'],
        synonyms: ['cinema', 'movie making'],
        intents: ['planning a short film', 'learning camera work', 'editing footage'],
        starters: ['How do I start making short films?', 'What is the 180-degree rule?', 'How do I light a scene?', 'What is the best editing software for beginners?'],
      },
      'Graphic Design': {
        expertise: ['graphic design', 'layout', 'branding', 'typography', 'software'],
        welcome: 'Graphic design question? Ask about layout, branding, or tools.',
        allowed: ['graphic design', 'design', 'layout', 'poster', 'logo', 'branding', 'illustrator', 'photoshop', 'figma', 'indesign', 'composition', 'hierarchy', 'grid', 'white space', 'mockup', 'vector', 'raster', 'portfolio'],
        related: ['design', 'art', 'marketing'],
        synonyms: ['visual design', 'graphics'],
        intents: ['learning design', 'making a poster', 'building a portfolio'],
        starters: ['What is the difference between vector and raster?', 'How do I design a poster?', 'What is typographic hierarchy?', 'How do I build a design portfolio?'],
      },
      'UX Design': {
        expertise: ['user experience', 'user research', 'wireframing', 'prototyping', 'usability'],
        welcome: 'UX design question? Ask about research, wireframes, or usability.',
        allowed: ['ux', 'user experience', 'user research', 'wireframe', 'prototype', 'usability', 'persona', 'user flow', 'heuristic', 'information architecture', 'a/b testing', 'accessibility', 'figma', 'journey map', 'interaction', 'onboarding'],
        related: ['design', 'product', 'technology'],
        synonyms: ['product design', 'interaction design'],
        intents: ['doing user research', 'creating wireframes', 'testing usability'],
        starters: ['What is the UX design process?', 'How do I create a user persona?', 'What are the Nielsen heuristics?', 'How do I run a usability test?'],
      },
      'Fashion Design': {
        expertise: ['fashion design', 'sketching', 'garment construction', 'patterns', 'collections'],
        welcome: 'Fashion design question? Ask about sketching, patterns, or construction.',
        allowed: ['fashion design', 'fashion designer', 'sketch', 'pattern', 'sewing', 'garment', 'fabric', 'collection', 'runway', 'draping', 'silk', 'couture', 'textile', 'mood board', 'lookbook', 'wardrobe'],
        related: ['fashion', 'design', 'textiles'],
        synonyms: ['apparel design', 'fashion'],
        intents: ['learning to sketch', 'making patterns', 'building a collection'],
        starters: ['How do I learn fashion design?', 'What is the difference between tailoring and couture?', 'How do I create a fashion collection?', 'What tools do I need for sketching?'],
      },
      'Interior Design': {
        expertise: ['interior design', 'space planning', 'color', 'furniture', 'lighting'],
        welcome: 'Interior design question? Ask about space, color, or style.',
        allowed: ['interior design', 'interior', 'space planning', 'furniture', 'lighting', 'color scheme', 'layout', 'rug', 'curtain', 'minimalism', 'scandinavian', 'industrial', 'bohemian', 'mood board', 'styling', 'room'],
        related: ['design', 'home', 'art'],
        synonyms: ['interior decorating', 'home design'],
        intents: ['designing a room', 'choosing a style', 'planning space'],
        starters: ['How do I design a small living room?', 'What are the main interior design styles?', 'How do I choose a color palette?', 'How do I light a room well?'],
      },
      Crafts: {
        expertise: ['crafts', 'diy', 'knitting', 'ceramics', 'jewelry making'],
        welcome: 'Craft question? Ask about DIY projects, materials, or techniques.',
        allowed: ['craft', 'crafts', 'diy', 'knitting', 'crochet', 'ceramics', 'pottery', 'clay', 'jewelry', 'beading', 'woodworking', 'paper craft', 'sewing', 'embroidery', 'scrapbook', 'resin', 'macrame', 'handmade'],
        related: ['creative', 'home', 'art'],
        synonyms: ['handicraft', 'maker'],
        intents: ['starting a craft', 'learning a technique', 'finding project ideas'],
        starters: ['How do I start knitting?', 'What is the difference between ceramics and pottery?', 'Easy DIY projects for beginners?', 'How do I get into jewelry making?'],
      },
      Poetry: {
        expertise: ['poetry forms', 'meter', 'rhyme', 'imagery', 'poetic devices'],
        welcome: 'Poetry question? Ask about forms, meter, or imagery.',
        allowed: ['poetry', 'poem', 'poet', 'sonnet', 'haiku', 'free verse', 'meter', 'rhyme', 'imagery', 'metaphor', 'simile', 'alliteration', 'stanza', 'line', 'verse', 'iambic', 'limerick'],
        related: ['literature', 'writing', 'art'],
        synonyms: ['verse', 'poesy'],
        intents: ['writing a poem', 'learning forms', 'analyzing poetry'],
        starters: ['How do I write a haiku?', 'What is iambic pentameter?', 'What is the difference between metaphor and simile?', 'How do I start writing poetry?'],
      },
    },
  },

  'Home & Garden': {
    themes: ['Forest', 'Sunset', 'Amber'],
    specialties: {
      Gardening: {
        expertise: ['plant care', 'vegetables', 'flowers', 'soil', 'seasonal gardening'],
        welcome: 'Gardening question? Ask about plants, soil, or the seasons.',
        allowed: ['gardening', 'garden', 'plant', 'plants', 'soil', 'compost', 'fertilizer', 'watering', 'sunlight', 'seed', 'seedling', 'vegetable', 'tomato', 'herb', 'flower', 'perennial', 'annual', 'pruning', 'mulch', 'potting'],
        related: ['home', 'nature', 'food'],
        synonyms: ['horticulture', 'growing'],
        intents: ['caring for plants', 'starting a garden', 'fixing plant problems'],
        starters: ['How do I start a vegetable garden?', 'Why are my plant leaves turning yellow?', 'How often should I water indoor plants?', 'What is compost and how do I make it?'],
      },
      'Home Repair': {
        expertise: ['basic repairs', 'tools', 'drywall', 'paint', 'fixing fixtures'],
        welcome: 'Home repair question? Ask about tools, fixes, or maintenance.',
        allowed: ['home repair', 'repair', 'fix', 'drywall', 'paint', 'painting', 'plumbing', 'leak', 'electrical', 'switch', 'outlet', 'door', 'hinge', 'caulk', 'screw', 'drill', 'hammer', 'wrench', 'putty', 'patch', 'wall'],
        related: ['home', 'construction', 'tools'],
        synonyms: ['handyman', 'DIY repair'],
        intents: ['fixing a leak', 'painting a room', 'hanging a shelf'],
        starters: ['How do I patch a drywall hole?', 'How do I fix a leaky faucet?', 'What tools should a beginner own?', 'How do I paint a room properly?'],
      },
      'Interior Decorating': {
        expertise: ['decorating', 'styling', 'accessories', 'color', 'arrangement'],
        welcome: 'Decorating question? Ask about style, color, or arrangement.',
        allowed: ['decorating', 'decor', 'decoration', 'style', 'accessory', 'vase', 'throw pillow', 'wall art', 'mirror', 'centerpiece', 'color', 'theme', 'arrangement', 'focal point', 'texture', 'layering', 'seasonal decor'],
        related: ['home', 'design', 'interior design'],
        synonyms: ['styling', 'home decor'],
        intents: ['decorating a room', 'choosing accessories', 'styling shelves'],
        starters: ['How do I style a bookshelf?', 'How do I choose throw pillows?', 'What is a focal point in a room?', 'How do I decorate for a new season?'],
      },
      Cleaning: {
        expertise: ['cleaning routines', 'products', 'stain removal', 'deep cleaning', 'organization'],
        welcome: 'Cleaning question? Ask about routines, products, or stains.',
        allowed: ['cleaning', 'clean', 'stain', 'spill', 'vacuum', 'mop', 'bathroom', 'kitchen', 'counter', 'tile', 'grout', 'dust', 'degreaser', 'bleach', 'vinegar', 'baking soda', 'deep clean', 'routine', 'laundry'],
        related: ['home', 'organization', 'health'],
        synonyms: ['housekeeping', 'tidying'],
        intents: ['removing a stain', 'building a routine', 'deep cleaning'],
        starters: ['How do I remove red wine stains?', 'How often should I deep clean?', 'What is the best all-purpose cleaner?', 'How do I clean grout?'],
      },
      Organization: {
        expertise: ['decluttering', 'storage', 'systems', 'rooms', 'minimalism'],
        welcome: 'Organization question? Ask about decluttering or storage.',
        allowed: ['organization', 'organizing', 'declutter', 'decluttering', 'storage', 'closet', 'garage', 'bins', 'labels', 'systems', 'minimalism', 'konmari', 'filing', 'shelf', 'drawer', 'capsule', 'tidying'],
        related: ['home', 'productivity', 'lifestyle'],
        synonyms: ['decluttering', 'tidying up'],
        intents: ['decluttering a room', 'organizing storage', 'building systems'],
        starters: ['How do I declutter my home?', 'What is the KonMari method?', 'How do I organize a small closet?', 'How do I set up a home filing system?'],
      },
      'DIY Projects': {
        expertise: ['DIY', 'woodworking', 'crafts', 'upcycling', 'home projects'],
        welcome: 'DIY project question? Ask about builds, materials, or ideas.',
        allowed: ['diy', 'project', 'woodworking', 'wood', 'pallet', 'upcycle', 'upcycling', 'build', 'craft', 'paint', 'glue', 'saw', 'measure', 'cut', 'reuse', 'repurpose', 'furniture', 'shelf', 'planter'],
        related: ['home', 'crafts', 'tools'],
        synonyms: ['do it yourself', 'maker projects'],
        intents: ['finding project ideas', 'learning woodworking', 'upcycling furniture'],
        starters: ['Easy DIY projects for beginners?', 'How do I build a pallet shelf?', 'What tools do I need for woodworking?', 'How do I upcycle old furniture?'],
      },
      Landscaping: {
        expertise: ['lawn care', 'plants', 'hardscaping', 'design', 'outdoor spaces'],
        welcome: 'Landscaping question? Ask about lawns, plants, or outdoor design.',
        allowed: ['landscaping', 'landscape', 'lawn', 'grass', 'mow', 'hedge', 'shrub', 'tree', 'mulch', 'paver', 'patio', 'walkway', 'irrigation', 'sprinkler', 'flower bed', 'perennial', 'outdoor lighting', 'drainage'],
        related: ['garden', 'home', 'environment'],
        synonyms: ['lawn care', 'groundskeeping'],
        intents: ['designing a yard', 'caring for a lawn', 'planning hardscape'],
        starters: ['How do I fix a patchy lawn?', 'What plants are good for shade?', 'How do I lay pavers?', 'How do I plan a backyard landscape?'],
      },
      'Pest Control': {
        expertise: ['pest prevention', 'common pests', 'natural remedies', 'treatment', 'extermination'],
        welcome: 'Pest question? Ask about prevention or treatment.',
        allowed: ['pest', 'pests', 'ants', 'roaches', 'termite', 'mosquito', 'mice', 'rats', 'spider', 'bed bug', 'fly', 'insecticide', 'trap', 'repellent', 'natural', 'boric acid', 'seal', 'infestation', 'exterminator'],
        related: ['home', 'health', 'environment'],
        synonyms: ['bug control', 'extermination'],
        intents: ['preventing pests', 'treating an infestation', 'choosing a remedy'],
        starters: ['How do I get rid of ants naturally?', 'How do I prevent cockroaches?', 'What attracts termites?', 'How do I handle a bed bug problem?'],
      },
      'Smart Home': {
        expertise: ['smart devices', 'automation', 'voice assistants', 'wifi', 'hubs'],
        welcome: 'Smart home question? Ask about devices, setup, or automation.',
        allowed: ['smart home', 'smart', 'device', 'alexa', 'google home', 'siri', 'hub', 'automation', 'routine', 'thermostat', 'nest', 'ring', 'camera', 'doorbell', 'lights', 'switch', 'plug', 'speaker', 'app', 'wifi', 'z-wave', 'zigbee'],
        related: ['technology', 'home', 'security'],
        synonyms: ['home automation', 'connected home'],
        intents: ['setting up devices', 'building automations', 'choosing a hub'],
        starters: ['How do I set up a smart home?', 'What is the difference between Zigbee and Z-Wave?', 'How do I create smart home routines?', 'Which smart speaker should I buy?'],
      },
      Furniture: {
        expertise: ['furniture selection', 'assembly', 'materials', 'layout', 'refinishing'],
        welcome: 'Furniture question? Ask about selection, assembly, or refinishing.',
        allowed: ['furniture', 'sofa', 'couch', 'table', 'chair', 'bed', 'wardrobe', 'bookshelf', 'desk', 'assembly', 'ikea', 'wood', 'particleboard', 'solid wood', 'refinish', 'stain', 'varnish', 'upholstery', 'measurements', 'delivery'],
        related: ['home', 'interior design', 'woodworking'],
        synonyms: ['furnishings', 'fixtures'],
        intents: ['choosing furniture', 'assembling furniture', 'refinishing'],
        starters: ['How do I choose a sofa?', 'How do I assemble flat-pack furniture well?', 'How do I refinish a wooden table?', 'How do I measure furniture for a room?'],
      },
    },
  },

  Automotive: {
    themes: ['Midnight', 'Slate', 'Mono'],
    specialties: {
      'Car Maintenance': {
        expertise: ['regular maintenance', 'oil changes', 'brakes', 'tires', 'engine basics'],
        welcome: 'Car maintenance question? Ask about service, fluids, or care.',
        allowed: ['car maintenance', 'car', 'vehicle', 'oil change', 'oil', 'brake', 'brakes', 'tire', 'tires', 'battery', 'coolant', 'filter', 'spark plug', 'mileage', 'service', 'check engine', 'fluid', 'rotation', 'alignment', 'inspection'],
        related: ['automotive', 'repair', 'driving'],
        synonyms: ['vehicle care', 'servicing'],
        intents: ['following a maintenance schedule', 'checking fluids', 'understanding warning lights'],
        starters: ['How often should I change my oil?', 'What does the check engine light mean?', 'How do I check my tire pressure?', 'What is a tune-up?'],
      },
      'Electric Vehicles': {
        expertise: ['EVs', 'charging', 'battery', 'range', 'hybrids'],
        welcome: 'EV question? Ask about charging, range, or ownership.',
        allowed: ['ev', 'electric vehicle', 'electric car', 'tesla', 'charging', 'charger', 'battery', 'range', 'kwh', 'level 2', 'dc fast', 'supercharger', 'hybrid', 'plug-in', 'regenerative', 'long range', 'depreciation', 'incentive'],
        related: ['automotive', 'environment', 'technology'],
        synonyms: ['electric cars', 'bev'],
        intents: ['buying an ev', 'understanding charging', 'comparing range'],
        starters: ['How long does charging an EV take?', 'EV vs hybrid — which is right for me?', 'How far can an EV actually go?', 'What is regenerative braking?'],
      },
      Motorcycles: {
        expertise: ['motorcycles', 'riding', 'gear', 'maintenance', 'types'],
        welcome: 'Motorcycle question? Ask about bikes, riding, or gear.',
        allowed: ['motorcycle', 'bike', 'riding', 'rider', 'helmet', 'gear', 'leather', 'cruiser', 'sport bike', 'adventure', 'touring', 'cc', 'engine', 'clutch', 'cornering', 'lane', 'license', 'moto', 'exhaust'],
        related: ['automotive', 'sports', 'safety'],
        synonyms: ['moto', 'two wheels'],
        intents: ['choosing a bike', 'improving riding', 'buying gear'],
        starters: ['Which motorcycle should a beginner buy?', 'How do I take a corner safely?', 'What gear do I need for riding?', 'How do I maintain my chain?'],
      },
      Racing: {
        expertise: ['racing', 'track days', 'formula 1', 'lines', 'car setup'],
        welcome: 'Racing question? Ask about track days, lines, or the sport.',
        allowed: ['racing', 'race', 'track day', 'formula 1', 'f1', 'nascar', 'le mans', 'laps', 'racing line', 'apex', 'braking', 'downforce', 'slicks', 'setup', 'corner', 'grid', 'pit stop', 'drag'],
        related: ['automotive', 'sports', 'engineering'],
        synonyms: ['motorsport', 'track driving'],
        intents: ['learning racing lines', 'attending a track day', 'understanding f1'],
        starters: ['What is the ideal racing line?', 'How do I prepare for my first track day?', 'How does a pit stop work?', 'What is downforce?'],
      },
      'Car Buying': {
        expertise: ['new vs used', 'negotiation', 'financing', 'inspection', 'dealerships'],
        welcome: 'Car buying question? Ask about new vs used, deals, or financing.',
        allowed: ['car buying', 'buy', 'new car', 'used car', 'dealer', 'dealership', 'negotiate', 'price', 'test drive', 'inspection', 'financing', 'lease', 'loan', 'trade-in', 'warranty', 'certified', 'vin', 'history report'],
        related: ['automotive', 'finance', 'consumer'],
        synonyms: ['purchasing a car', 'auto buying'],
        intents: ['choosing new vs used', 'negotiating price', 'getting financing'],
        starters: ['New vs used car — which is better?', 'How do I negotiate car price?', 'What should I check on a test drive?', 'Lease vs buy — what should I choose?'],
      },
      'Driving Tips': {
        expertise: ['driving techniques', 'highway', 'parking', 'defensive driving', 'winter driving'],
        welcome: 'Driving question? Ask about technique, safety, or tricky situations.',
        allowed: ['driving', 'driver', 'highway', 'parking', 'parallel parking', 'defensive', 'lane change', 'merge', 'roundabout', 'winter driving', 'rain', 'fog', 'night driving', 'speed', 'blind spot', 'mirrors', 'manual', 'stick shift'],
        related: ['automotive', 'safety', 'transport'],
        synonyms: ['roadcraft', 'motoring'],
        intents: ['learning to drive', 'improving technique', 'driving in bad weather'],
        starters: ['How do I parallel park?', 'How do I drive safely in rain?', 'How do I drive a manual transmission?', 'What is defensive driving?'],
      },
      'Classic Cars': {
        expertise: ['classic cars', 'restoration', 'collecting', 'value', 'preservation'],
        welcome: 'Classic car question? Ask about restoration, collecting, or values.',
        allowed: ['classic car', 'classic cars', 'vintage', 'restoration', 'restore', 'collector', 'collecting', 'auction', 'value', 'original', 'matching numbers', 'muscle car', 'mustang', 'porsche 911', 'concours', 'patina', 'parts'],
        related: ['automotive', 'history', 'collecting'],
        synonyms: ['antique cars', 'collectors'],
        intents: ['buying a classic', 'starting a restoration', 'appraising value'],
        starters: ['What classic car should I buy?', 'How do I start a restoration project?', 'What determines a classic car\'s value?', 'What is a matching numbers car?'],
      },
      Trucking: {
        expertise: ['trucking', 'logistics', 'driving a truck', 'CDL', 'routes'],
        welcome: 'Trucking question? Ask about driving, licensing, or the industry.',
        allowed: ['trucking', 'truck', 'truck driver', 'cdl', 'hazmat', 'freight', 'load', 'logistics', 'long haul', 'delivery', 'diesel', 'trailer', 'hours of service', 'log book', 'toll', 'shipping'],
        related: ['automotive', 'logistics', 'transport'],
        synonyms: ['freight driving', 'haulage'],
        intents: ['getting a cdl', 'understanding trucking', 'planning routes'],
        starters: ['How do I get a CDL?', 'What is it like being a long-haul trucker?', 'How do truckers manage hours of service?', 'What is the difference between LTL and FTL?'],
      },
      'Auto Repair': {
        expertise: ['diagnostics', 'repairs', 'engines', 'electrical', 'tools'],
        welcome: 'Auto repair question? Ask about diagnostics, repairs, or tools.',
        allowed: ['auto repair', 'repair', 'engine', 'transmission', 'diagnostics', 'obd', 'scanner', 'codes', 'clutch', 'alternator', 'starter', 'radiator', 'suspension', 'shocks', 'struts', 'gasket', 'timing belt', 'wrench', 'jack', 'brake', 'brakes', 'brake pads', 'pads', 'rotor', 'caliper'],
        related: ['automotive', 'mechanics', 'tools'],
        synonyms: ['mechanic work', 'auto maintenance'],
        intents: ['diagnosing a problem', 'learning repairs', 'choosing tools'],
        starters: ['How do I read OBD codes?', 'What does a timing belt do?', 'How do I replace brake pads?', 'How do I jump-start a car?'],
      },
      Detailing: {
        expertise: ['detailing', 'washing', 'waxing', 'interior care', 'paint correction'],
        welcome: 'Detailing question? Ask about washing, waxing, or interior care.',
        allowed: ['detailing', 'detail', 'wash', 'wax', 'polish', 'ceramic coating', 'clay bar', 'interior', 'leather', 'seats', 'carpet', 'dashboard', 'tires', 'shampoo', 'microfiber', 'two bucket', 'paint', 'swirl'],
        related: ['automotive', 'home', 'maintenance'],
        synonyms: ['car care', 'auto detailing'],
        intents: ['washing properly', 'applying wax', 'cleaning the interior'],
        starters: ['How do I wash my car without scratches?', 'Wax vs ceramic coating?', 'How do I clean leather seats?', 'What is paint correction?'],
      },
    },
  },
};
