/**
 * Ship pipeline routes — export zip, GitHub repo, Render deploy + status +
 * sleep/wake + unpublish. Mounted under /api/bots (all actions org-scoped).
 *
 * Robustness contract:
 *   - Every handler runs through asyncHandler, so no raw stack trace ever
 *     reaches the page — failures surface as friendly { error } JSON with the
 *     right status, and the Ship UI renders them as per-card error states.
 *   - All remote deletes (Render service, GitHub repo) are idempotent:
 *     404 = already gone = success, so retrying a failed unpublish finishes
 *     the job instead of erroring out.
 *   - Batch endpoints tolerate per-bot failures: one bad bot never fails the
 *     whole batch (partial results + per-item status).
 *
 * Bulk shipping (10–30 bots at once) is handled by:
 *   - shipLimiter sized at 600/min (30 bots × several calls each),
 *   - GitHub + Render services retry throttled writes internally with
 *     backoff, so bursts queue up instead of 403/429'ing the UI.
 */
import { Router } from 'express';
import * as botService from '../services/bot.service.js';
import { buildBotBundle, bundleFilename, repoNameFor } from '../services/export.service.js';
import * as github from '../services/github.service.js';
import * as render from '../services/render.service.js';
import { zipFiles } from '../services/zip.js';
import db from '../db.js';
import { logActivity } from '../services/audit.service.js';
import { ApiError, asyncHandler } from '../middleware/errorHandler.js';
import { shipLimiter } from '../middleware/rateLimits.js';
import { enqueue as queueEnqueue, enqueueDelete as queueEnqueueDelete, queueStatus, dequeue as queueDequeue, resumePersistedQueues } from '../services/shipQueue.service.js';

const router = Router();
router.use(shipLimiter);

/** Parse "owner/repo" out of the stored repoName or repoUrl (both are kept). */
function ghParts(state) {
  if (state?.repoName && state.repoName.includes('/')) {
    const [owner, repo] = state.repoName.split('/');
    if (owner && repo) return { owner, repo };
  }
  const m = String(state?.repoUrl || '').match(/github\.com\/([^/]+)\/([^/#?]+)/);
  return m ? { owner: m[1], repo: m[2] } : null;
}

// ---- ZIP export (demo fallback — needs no external service) ----
router.get('/export/:botId/zip', asyncHandler(async (req, res) => {
  const bot = await botService.getBotOrThrow(req.params.botId, req.org.id);
  const bundle = buildBotBundle(bot);
  const buf = zipFiles(bundle);
  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${bundleFilename(bot)}"`);
  res.send(buf);
}));

// ---- Ship to GitHub: private repo + push bundle (idempotent re-ship) ----
router.post('/ship/github/:botId', asyncHandler(async (req, res) => {
  const bot = await botService.getBotOrThrow(req.params.botId, req.org.id);
  const bundle = buildBotBundle(bot);
  const domainLine = [bot.domain, bot.subdomain].filter(Boolean).join(' · ');
  const { owner, repo, url } = await github.ensureRepo({
    name: repoNameFor(bot),
    description: `${bot.name} — ${domainLine} chatbot generated by Scarlet Chatbot Factory`,
  });
  await github.pushRepoFiles({ owner, repo }, bundle);
  await db.updateBotShip(bot.id, req.org.id, {
    repoUrl: url,
    repoName: `${owner}/${repo}`,
    shippedAt: new Date(),
  });
  await logActivity({
    orgId: req.org.id, actorId: req.user.id, actorName: req.user.email,
    eventType: 'bot.shipped_github', data: { repo: `${owner}/${repo}` }, botId: bot.id,
  });
  res.json({ success: true, repoUrl: url });
}));

// ---- Deploy to Render (auto-deploy wired) ----
router.post('/ship/render/:botId', asyncHandler(async (req, res) => {
  const bot = await botService.getBotOrThrow(req.params.botId, req.org.id);
  const state = await db.getBotShipState(bot.id, req.org.id);
  if (!state?.repoUrl) throw new ApiError(400, 'Deploy to Render needs the bot on GitHub first — use "Ship to GitHub".');

  const geminiKey = process.env.GEMINI_API_KEY;
  if (!geminiKey || geminiKey.startsWith('your_')) {
    throw new ApiError(503, 'No GEMINI_API_KEY found in the Factory .env — deployed bots need it to answer questions.');
  }

  const baseName = render.renderName((state.repoName || repoNameFor(bot)).replace('/', '-'), bot.id);

  // Re-deploy an existing service instead of creating a second one.
  if (state.renderServiceId && state.deployUrl) {
    await render.resumeService(state.renderServiceId).catch(() => {});
    await new Promise((r) => setTimeout(r, 2000));
    await render.triggerDeploy(state.renderServiceId);
    await db.updateBotShip(bot.id, req.org.id, { deployStatus: 'queued' });
    return res.json({ success: true, deployUrl: state.deployUrl, deployStatus: 'queued', reused: true });
  }

  let service = null;
  for (const candidate of [baseName, `${baseName}-${Math.random().toString(36).slice(2, 5)}`]) {
    try {
      service = await render.createWebService({ name: candidate, repoUrl: state.repoUrl, geminiKey });
      break;
    } catch (err) {
      if (err.message === 'render_name_taken') continue;
      throw err;
    }
  }
  if (!service) throw new ApiError(502, 'Render could not allocate a unique service name — retry deploying.');

  // (Render starts the first deploy automatically on create — no extra write op)
  await db.updateBotShip(bot.id, req.org.id, {
    renderServiceId: service.id,
    deployUrl: service.url,
    deployStatus: 'building',
  });
  await logActivity({
    orgId: req.org.id, actorId: req.user.id, actorName: req.user.email,
    eventType: 'bot.shipped_render', data: { service: service.id, url: service.url }, botId: bot.id,
  });
  res.json({ success: true, deployUrl: service.url, deployStatus: 'building', reused: false });
}));

// ---- Live deploy status (polls Render and persists changes) ----
router.get('/ship/status/:botId', asyncHandler(async (req, res) => {
  const bot = await botService.getBotOrThrow(req.params.botId, req.org.id);
  const state = await db.getBotShipState(bot.id, req.org.id);
  if (!state?.renderServiceId) return res.json({ deployStatus: bot.deployStatus || null, deployUrl: bot.deployUrl || null });
  try {
    const { deployStatus } = await render.latestDeployStatus(state.renderServiceId);
    if (deployStatus !== (state.deployStatus || '')) {
      await db.updateBotShip(bot.id, req.org.id, { deployStatus });
    }
    res.json({ deployStatus, deployUrl: state.deployUrl || bot.deployUrl || null });
  } catch (err) {
    if (err.code === 'render_gone') {
      // deleted on Render's side — clear stale links so the UI tells the truth
      await db.updateBotShip(bot.id, req.org.id, { renderServiceId: null, deployUrl: null, deployStatus: null, shipStage: null });
      return res.json({ deployStatus: null, deployUrl: null, renderGone: true });
    }
    throw err;
  }
}));

/**
 * GET /ship/status-batch?ids=a,b,c,...  (up to 60)
 * One round trip replaces 30 individual polls during bulk deployments.
 * Best-effort by design: a Render hiccup on one bot falls back to that bot's
 * stored status — the batch itself never fails.
 */
router.get('/ship/status-batch', asyncHandler(async (req, res) => {
  const ids = String(req.query.ids || '').split(',').map((s) => s.trim()).filter(Boolean).slice(0, 120);
  const out = {};
  // Fan out in small parallel chunks — a 50-bot page refresh finishes in ~2s,
  // not the 20+ a serial loop would take. Best-effort per bot as before.
  const CH = 8;
  for (let c = 0; c < ids.length; c += CH) {
    await Promise.all(ids.slice(c, c + CH).map(async (id) => {
    try {
      const state = await db.getBotShipState(id, req.org.id);
      if (!state) { out[id] = { deployStatus: null, deployUrl: null, error: 'not found' }; return; }
      if (!state.renderServiceId) { out[id] = { deployStatus: state.deployStatus || null, deployUrl: null }; return; }
      let deployStatus = state.deployStatus || null;
      try {
        ({ deployStatus } = await render.latestDeployStatus(state.renderServiceId));
        if (deployStatus !== (state.deployStatus || '')) {
          await db.updateBotShip(id, req.org.id, { deployStatus }).catch(() => {});
        }
      } catch (err) {
        if (err.code === 'render_gone') {
          await db.updateBotShip(id, req.org.id, { renderServiceId: null, deployUrl: null, deployStatus: null, shipStage: null }).catch(() => {});
          out[id] = { deployStatus: null, deployUrl: null, renderGone: true };
          return;
        }
        /* keep stored status */
      }
      out[id] = { deployStatus, deployUrl: state.deployUrl || null };
    } catch (err) {
      out[id] = { deployStatus: null, deployUrl: null, error: err.message || 'lookup failed' };
    }
    }));
  }
  res.json(out);
}));

// ---- Sleep: suspend to reclaim free instance hours ----
/** Sleep = a Render write. If the write window is cooling down, don't hang the
 * click for half an hour: schedule it server-side and tell the row honestly. */
router.post('/ship/sleep/:botId', asyncHandler(async (req, res) => {
  const bot = await botService.getBotOrThrow(req.params.botId, req.org.id);
  const state = await db.getBotShipState(bot.id, req.org.id);
  if (!state?.renderServiceId) throw new ApiError(400, 'This bot has no Render deployment to sleep.');
  const load = render.renderWriteLoad();
  if (load && load.paused > 8000) {
    setTimeout(async () => {
      try {
        await render.suspendService(state.renderServiceId);
        await db.updateBotShip(bot.id, req.org.id, { deployStatus: 'suspended' });
        console.log(`[ship] deferred sleep applied: ${bot.name}`);
      } catch { /* user can retry; instance sleeps itself eventually */ }
    }, load.paused + 800).unref?.();
    return res.json({ success: true, deferred: true, waitMin: Math.ceil(load.paused / 60000) });
  }
  await render.suspendService(state.renderServiceId);
  await db.updateBotShip(bot.id, req.org.id, { deployStatus: 'suspended' });
  res.json({ success: true, deployStatus: 'suspended' });
}));

// ---- Wake: resume service + hit the health endpoint ----
router.post('/ship/wake/:botId', asyncHandler(async (req, res) => {
  const bot = await botService.getBotOrThrow(req.params.botId, req.org.id);
  const state = await db.getBotShipState(bot.id, req.org.id);
  const url = state?.deployUrl || bot.deployUrl;
  if (!url) throw new ApiError(400, 'This bot is not deployed yet.');
  if (state?.renderServiceId) await render.resumeService(state.renderServiceId).catch(() => {});
  const { awake } = await render.wakeService(url);
  if (awake) await db.updateBotShip(bot.id, req.org.id, { deployStatus: 'live' });
  res.json({ awake });
}));

// ---- Reset local ship bookkeeping (remotes are kept; re-ship reuses them) ----
router.delete('/ship/:botId', asyncHandler(async (req, res) => {
  const bot = await botService.getBotOrThrow(req.params.botId, req.org.id);
  await db.clearBotShip(bot.id, req.org.id);
  res.json({ success: true });
}));

/**
 * POST /ship/unpublish-queue { botIds: [..] } — bulk teardown through the
 * self-pacing engine: 30 deletes never surface a write-limit popup; the UI
 * just watches the queue bar drain.
 */
router.post('/ship/unpublish-queue', asyncHandler(async (req, res) => {
  const ids = Array.isArray(req.body?.botIds) ? req.body.botIds.map(String).filter(Boolean).slice(0, 100) : [];
  if (!ids.length) throw new ApiError(400, 'Pick at least one bot to delete.');
  const bots = await db.getBotsByIds(ids, req.org.id);
  const found = new Set(bots.map((b) => b.id));
  const r = queueEnqueueDelete({ orgId: req.org.id, botIds: [...found] });
  res.json({ success: true, accepted: r.accepted, notFound: ids.filter((i) => !found.has(i)) });
}));

/**
 * POST /ship/unpublish/:botId
 * Full teardown from the Ship page delete popup: deletes the Render service
 * AND the GitHub repo, then clears local ship state. Render first (frees the
 * account slot), GitHub second. Each provider's failure is reported
 * separately ({ github: {ok,error}, render: {ok,error} }) and local state is
 * only cleared when BOTH are gone — so the UI keeps the Delete button and the
 * user can retry to finish the job.
 */
router.post('/ship/unpublish/:botId', asyncHandler(async (req, res) => {
  const bot = await botService.getBotOrThrow(req.params.botId, req.org.id);
  queueDequeue(bot.id);
  const state = await db.getBotShipState(bot.id, req.org.id);
  const parts = ghParts(state);
  if (!state?.renderServiceId && !parts) {
    throw new ApiError(400, 'This bot is not published anywhere — nothing to delete.');
  }

  const result = {
    render: { ok: !state.renderServiceId, error: null },
    github: { ok: !parts, error: null },
  };

  // ---- 1. Render service delete ----
  if (state.renderServiceId) {
    try {
      await render.deleteService(state.renderServiceId);
      result.render.ok = true;
    } catch (err) {
      result.render.error = err.message || 'Render could not delete the service.';
    }
  }

  // ---- 2. GitHub repo delete ----
  if (parts) {
    try {
      await github.deleteRepo(parts.owner, parts.repo);
      result.github.ok = true;
    } catch (err) {
      result.github.error = err.message || 'GitHub could not delete the repository.';
    }
  }

  // ---- 3. Local state: only clear when both providers are gone ----
  const fullyClean = result.render.ok && result.github.ok;
  if (fullyClean) {
    await db.clearBotShip(bot.id, req.org.id);
    await logActivity({
      orgId: req.org.id, actorId: req.user.id, actorName: req.user.email,
      eventType: 'bot.unpublished', data: { repo: state.repoName || null }, botId: bot.id,
    });
  }

  res.json({ success: fullyClean, ...result });
}));

/**
 * ---- SHIP QUEUE (background pipeline — no error popups, ever) ----
 * POST /ship/queue { botIds: { [id]: optionalGeminiKey }, mode: 'github' | 'github+render' }
 *   → enqueues everything; the server-side engine paces GitHub/Render writes
 *     with automatic pacing + retries, so 50 bots at once just "go".
 * GET  /ship/queue            → live progress snapshot for the UI
 * DELETE /ship/queue/:botId   → pull a bot out of the queue
 */
router.post('/ship/queue', asyncHandler(async (req, res) => {
  const raw = req.body?.botIds;
  const entries = Array.isArray(raw)
    ? raw.map((id) => [id, ''])
    : Object.entries(raw || {});
  const botIds = entries.map(([id]) => String(id)).filter(Boolean).slice(0, 100);
  if (!botIds.length) throw new ApiError(400, 'Pick at least one bot to ship.');
  const keys = Object.fromEntries(entries.filter(([, k]) => String(k || '').trim()).map(([id, k]) => [String(id), String(k).trim()]));
  const mode = req.body?.mode === 'github' ? 'github' : 'github+render';

  // Validate every bot belongs to this org BEFORE enqueuing (fast, no rate limits).
  const bots = await db.getBotsByIds(botIds, req.org.id);
  const found = new Set(bots.map((b) => b.id));
  const missing = botIds.filter((id) => !found.has(id));

  // Store the per-bot keys in the DB too (encrypted at rest by SQLite placement,
  // never pushed to any repo) — so a server restart can still finish deploys.
  for (const [id, k] of Object.entries(keys)) {
    if (found.has(id)) await db.updateBotShip(id, req.org.id, { llmApiKey: k }).catch(() => {});
  }

  const r = queueEnqueue({ orgId: req.org.id, userId: req.user.id, userEmail: req.user.email, botIds: found ? [...found] : botIds, keys, mode });
  res.json({
    success: true,
    accepted: r.accepted.length,
    skipped: r.skipped.length,
    alreadyQueued: missing.length ? 0 : undefined,
    notFound: missing,
  });
}));

router.get('/ship/queue', asyncHandler(async (req, res) => {
  const snap = queueStatus();
  // filter by the job's own orgId — no DB sweep per poll
  const visible = snap.jobs.filter((j) => j.orgId === req.org.id).map(({ orgId, ...rest }) => rest);
  res.json({
    total: visible.length,
    working: visible.filter((j) => j.status === 'working').length,
    waiting: visible.filter((j) => j.status === 'waiting').length,
    done: visible.filter((j) => j.status === 'done').length,
    failed: visible.filter((j) => j.status === 'failed').length,
    jobs: visible,
  });
}));

router.delete('/ship/queue/:botId', asyncHandler(async (req, res) => {
  const ok = await db.botInOrg(req.params.botId, req.org.id);
  if (!ok) throw new ApiError(404, 'Bot not found.');
  queueDequeue(req.params.botId);
  res.json({ success: true });
}));

export default router;
