// ============================================================
// SCARLET DOMAIN KNOWLEDGE — PART 1
// (core legacy domains, expanded)
// Each specialty: expertise, welcome, allowed, related,
// synonyms, intents, starters (+ optional disclaimer).
// ============================================================

export const DOMAIN_PART1 = {
  Education: {
    themes: ['Slate', 'Royal', 'Mono', 'Forest'],
    specialties: {
      Languages: {
        expertise: ['grammar', 'vocabulary', 'translation', 'pronunciation', 'linguistics', 'writing', 'reading comprehension', 'conversation practice', 'idioms and phrasal verbs'],
        welcome: 'What would you like to learn — grammar, vocabulary, or translation?',
        allowed: ['language', 'languages', 'grammar', 'vocabulary', 'translation', 'translate', 'pronunciation', 'linguistics', 'english', 'spanish', 'french', 'german', 'sentence', 'word', 'phrase', 'tense', 'verb', 'noun', 'writing', 'reading', 'fluency', 'idiom', 'dialect', 'communication', 'syntax', 'accent', 'essay', 'conjugation', 'preposition', 'speaking'],
        related: ['literature', 'syntax', 'accent', 'conversation', 'essay'],
        synonyms: ['linguistic', 'speech', 'tongue'],
        intents: ['translating a sentence', 'learning a new language', 'fixing grammar', 'improving pronunciation', 'building vocabulary', 'practicing conversation'],
        starters: ['Explain the difference between "affect" and "effect"', 'Translate "Good morning, how are you?" into French', 'How can I improve my English pronunciation?', 'Give me 5 advanced vocabulary words with example sentences'],
      },
      Programming: {
        expertise: ['programming concepts', 'algorithms', 'data structures', 'debugging', 'languages like Python/Java/JS', 'best practices', 'object-oriented design', 'software testing'],
        welcome: 'What would you like to learn or build today?',
        allowed: ['programming', 'code', 'coding', 'python', 'java', 'javascript', 'c++', 'algorithm', 'data structure', 'function', 'variable', 'loop', 'recursion', 'debugging', 'bug', 'compiler', 'api', 'object', 'class', 'array', 'matplotlib', 'software', 'developer', 'programmer', 'syntax', 'framework', 'git', 'testing', 'typescript', 'react', 'node', 'language', 'languages', 'memory', 'memory leak', 'leak', 'learn coding'],
        related: ['computer science', 'development', 'syntax error', 'framework'],
        synonyms: ['program', 'developer', 'script'],
        intents: ['writing a program', 'understanding an algorithm', 'fixing a bug', 'learning a language feature', 'reviewing code'],
        starters: ['Explain recursion with a simple example', 'Write a Python function to reverse a string', 'What is the difference between a list and a tuple?', 'Give me a beginner coding exercise'],
      },
      Mathematics: {
        expertise: ['algebra', 'calculus', 'geometry', 'statistics', 'problem solving', 'proofs', 'trigonometry', 'probability'],
        welcome: 'What math topic can I help you with?',
        allowed: ['math', 'mathematics', 'algebra', 'calculus', 'geometry', 'statistics', 'equation', 'derivative', 'integral', 'probability', 'theorem', 'fraction', 'function', 'matrix', 'trigonometry', 'geometry', 'graph', 'linear', 'quadratic', 'polynomial', 'set theory', 'number theory', 'exponent', 'logarithm'],
        related: ['problem set', 'proof', 'number theory'],
        synonyms: ['mathematical', 'arithmetic'],
        intents: ['solving an equation', 'understanding a theorem', 'working a problem step by step', 'graphing a function'],
        starters: ['Explain the Pythagorean theorem', 'Solve 2x + 5 = 17 step by step', 'What is a derivative, intuitively?', 'Give me a probability practice problem'],
      },
      Physics: {
        expertise: ['mechanics', 'energy', 'electricity', 'thermodynamics', 'waves', 'modern physics', 'optics', 'kinematics'],
        welcome: 'What physics concept would you like to explore?',
        allowed: ['physics', 'force', 'energy', 'motion', 'velocity', 'acceleration', 'gravity', 'electricity', 'magnetism', 'thermodynamics', 'wave', 'quantum', 'relativity', 'momentum', 'newton', 'friction', 'work', 'power', 'kinematics', 'projectile', 'lens', 'optics', 'circuit', 'voltage', 'current'],
        related: ['experiment', 'formula', 'units'],
        synonyms: ['physical'],
        intents: ['understanding a law of physics', 'solving a mechanics problem', 'understanding circuits'],
        starters: ["Explain Newton's second law", 'Why do objects fall at the same rate in a vacuum?', 'What is kinetic vs potential energy?', 'Explain how a lever works'],
      },
      History: {
        expertise: ['world history', 'civilizations', 'wars', 'historical figures', 'timelines', 'ancient history', 'modern history'],
        welcome: 'Which period or event would you like to learn about?',
        allowed: ['history', 'historical', 'ancient', 'medieval', 'empire', 'war', 'revolution', 'civilization', 'dynasty', 'century', 'king', 'queen', 'treaty', 'era', 'renaissance', 'colonization', 'cold war', 'timeline', 'archaeology', 'artifact', 'historian'],
        related: ['culture', 'timeline', 'archaeology'],
        synonyms: ['historic'],
        intents: ['learning about an event', 'understanding a historical figure', 'understanding a timeline'],
        starters: ['What caused World War I?', 'Tell me about ancient Egypt', 'Who was Julius Caesar?', 'Explain the Industrial Revolution'],
      },
      Chemistry: {
        expertise: ['organic chemistry', 'inorganic chemistry', 'chemical reactions', 'periodic table', 'stoichiometry', 'acid-base chemistry', 'lab safety'],
        welcome: 'What chemistry topic shall we explore today?',
        allowed: ['chemistry', 'chemical', 'molecule', 'atom', 'element', 'periodic table', 'reaction', 'compound', 'bond', 'acid', 'base', 'ph', 'stoichiometry', 'mole', 'solution', 'concentration', 'organic', 'polymer', 'catalyst', 'electrolysis', 'oxidation'],
        related: ['experiment', 'laboratory', 'safety'],
        synonyms: ['chemical science'],
        intents: ['balancing an equation', 'understanding a reaction', 'learning about an element'],
        starters: ['What is the difference between an atom and a molecule?', 'How do I balance a chemical equation?', 'Explain acids and bases simply', 'What is the periodic table trend for electronegativity?'],
      },
      Biology: {
        expertise: ['cell biology', 'genetics', 'human anatomy', 'evolution', 'ecology', 'microbiology', 'physiology'],
        welcome: 'What area of biology would you like to dig into?',
        allowed: ['biology', 'cell', 'dna', 'rna', 'gene', 'genetics', 'evolution', 'species', 'ecosystem', 'anatomy', 'organ', 'tissue', 'photosynthesis', 'respiration', 'microbe', 'bacteria', 'virus', 'enzyme', 'protein', 'chromosome', 'mitosis', 'natural selection'],
        related: ['lab', 'microscope', 'ecology'],
        synonyms: ['biological', 'life science'],
        intents: ['understanding genetics', 'learning about cells', 'understanding evolution'],
        starters: ['Explain how DNA codes for proteins', 'What is the difference between mitosis and meiosis?', 'How does natural selection work?', 'What are the main parts of a cell?'],
      },
      Literature: {
        expertise: ['classic novels', 'poetry', 'literary analysis', 'authors and movements', 'themes and symbolism', 'critical theory'],
        welcome: 'Which book or author would you like to discuss?',
        allowed: ['literature', 'novel', 'book', 'author', 'poem', 'poetry', 'poet', 'story', 'fiction', 'nonfiction', 'essay', 'play', 'drama', 'shakespeare', 'theme', 'symbolism', 'narrative', 'genre', 'gothic', 'romanticism', 'modernism', 'classic', 'literary'],
        related: ['writing', 'criticism', 'history'],
        synonyms: ['literary', 'letters'],
        intents: ['analyzing a book', 'understanding a poem', 'learning about an author'],
        starters: ['What is the main theme of 1984?', 'Explain symbolism in The Great Gatsby', 'Who were the romantic poets?', 'How do I write a literary analysis?'],
      },
      Philosophy: {
        expertise: ['ethics', 'logic', 'metaphysics', 'epistemology', 'political philosophy', 'existentialism', 'stoicism', 'philosophers'],
        welcome: 'What philosophical question is on your mind today?',
        allowed: ['philosophy', 'philosopher', 'ethics', 'morality', 'logic', 'argument', 'metaphysics', 'epistemology', 'knowledge', 'existence', 'free will', 'determinism', 'consciousness', 'truth', 'justice', 'socrates', 'plato', 'aristotle', 'nietzsche', 'kant', 'stoicism', 'existentialism'],
        related: ['history of ideas', 'religion', 'science'],
        synonyms: ['philosophical', 'thought'],
        intents: ['understanding a philosophical concept', 'learning about a philosopher', 'debating an idea'],
        starters: ['What is the trolley problem?', 'Explain Stoicism in simple terms', 'What did Plato think about knowledge?', 'Is free will real?'],
      },
      Psychology: {
        expertise: ['cognitive psychology', 'learning theory', 'memory', 'motivation', 'social psychology', 'developmental psychology', 'study techniques'],
        welcome: 'Curious about how the mind works? Ask away.',
        allowed: ['psychology', 'cognitive', 'behavior', 'memory', 'learning', 'motivation', 'attention', 'perception', 'emotion', 'development', 'social psychology', 'brain', 'habit', 'focus', 'procrastination', 'study skills', 'intelligence', 'personality'],
        related: ['neuroscience', 'education', 'mental health'],
        synonyms: ['psychological', 'behavioral science'],
        intents: ['understanding memory', 'improving focus', 'learning study techniques'],
        starters: ['How does memory actually work?', 'What are the best evidence-based study techniques?', 'How do habits form?', 'What is cognitive load theory?'],
      },
    },
  },

  Gaming: {
    themes: ['Crimson', 'Midnight', 'Terminal', 'Royal'],
    specialties: {
      RPG: {
        expertise: ['RPG recommendations', 'character builds', 'classes', 'quests', 'game mechanics', 'party composition', 'tabletop RPGs'],
        welcome: 'What are we playing today — need a build, a recommendation, or a quest tip?',
        allowed: ['rpg', 'role-playing', 'role playing', 'character', 'build', 'class', 'quest', 'loot', 'level', 'leveling', 'skill tree', 'party', 'npc', 'open world', 'dungeon', 'stats', 'game', 'games', 'gaming', 'video game', 'playthrough', 'jrpg', 'crpg', 'mmorpg', 'tabletop', 'dungeons and dragons'],
        related: ['jrpg', 'crpg', 'mmorpg', 'tabletop', 'dungeons and dragons'],
        synonyms: ['gamer', 'gameplay', 'walkthrough'],
        intents: ['getting a game recommendation', 'building a character', 'understanding a mechanic', 'picking a class'],
        starters: ['Recommend an RPG for beginners', 'How do I build a mage character?', 'Which class should I choose for a solo playthrough?', 'Explain how experience and leveling work'],
      },
      Strategy: {
        expertise: ['strategy games', 'build orders', 'resource management', 'tactics', '4X and RTS', 'deck building'],
        welcome: 'Looking for tactics, a build order, or a game to try?',
        allowed: ['strategy', 'rts', '4x', 'turn-based', 'build order', 'tactics', 'resource', 'economy', 'units', 'base', 'civilization', 'tech tree', 'game', 'gaming', 'grand strategy', 'tower defense', 'deck building', 'roster'],
        related: ['grand strategy', 'tower defense'],
        synonyms: ['strategic', 'gamer'],
        intents: ['improving strategy', 'learning a build order', 'picking a strategy game'],
        starters: ['Recommend a strategy game for beginners', 'Explain a good opening build order', 'How do I manage economy vs military?', 'What is the difference between RTS and turn-based?'],
      },
      FPS: {
        expertise: ['aim', 'movement', 'loadouts', 'maps', 'competitive play', 'sensitivity settings'],
        welcome: 'Want to improve your aim, learn a map, or pick a shooter?',
        allowed: ['fps', 'shooter', 'aim', 'crosshair', 'loadout', 'weapon', 'map', 'recoil', 'movement', 'competitive', 'rank', 'game', 'gaming', 'sensitivity', 'esports', 'headshot', 'spray', 'grenade'],
        related: ['esports', 'sensitivity'],
        synonyms: ['gamer', 'gameplay'],
        intents: ['improving aim', 'choosing a loadout', 'learning a map'],
        starters: ['How can I improve my aim?', 'Recommend a good FPS to start with', 'How do I control recoil?', 'What sensitivity should I use?'],
      },
      Esports: {
        expertise: ['competitive play', 'teams and tournaments', 'meta analysis', 'scrimming', 'mental preparation'],
        welcome: 'Looking to go competitive? Ask about the scene, meta, or training.',
        allowed: ['esports', 'competitive', 'tournament', 'team', 'meta', 'scrim', 'ranked', 'lan', 'tournament', 'pro player', 'coaching', 'moba', 'league of legends', 'dota', 'valorant', 'csgo', 'counter-strike', 'overwatch', 'pick and ban'],
        related: ['fps', 'moba', 'streaming'],
        synonyms: ['e-sports', 'pro gaming'],
        intents: ['understanding the meta', 'getting into competitive play', 'learning pro strategies'],
        starters: ['What does "the meta" mean?', 'How do I break into esports?', 'How do pro teams train?', 'Explain pick and ban in MOBAs'],
      },
      Puzzle: {
        expertise: ['puzzle games', 'logic puzzles', 'walkthroughs', 'riddle solving', 'escape rooms'],
        welcome: 'Stuck on a puzzle or hunting a new brainteaser?',
        allowed: ['puzzle', 'puzzles', 'riddle', 'brain teaser', 'logic', 'escape room', 'walkthrough', 'solution', 'hint', 'clue', 'crossword', 'sudoku', 'tile', 'matching', 'game', 'gaming', 'portal', 'the witness', 'baba is you'],
        related: ['logic', 'riddles', 'mystery'],
        synonyms: ['brainteaser', 'headscratcher'],
        intents: ['getting a hint', 'solving a puzzle', 'finding a solution'],
        starters: ['Give me a hard logic puzzle', 'How do I solve this riddle?', 'Recommend a great puzzle game', 'What is the solution to the river crossing puzzle?'],
      },
    },
  },

  Astronomy: {
    themes: ['Space', 'Midnight'],
    specialties: {
      'Planetary Science': {
        expertise: ['planets', 'moons', 'the solar system', 'planetary geology', 'atmospheres', 'space missions'],
        welcome: 'What would you like to explore in the solar system?',
        allowed: ['planet', 'planets', 'mars', 'venus', 'jupiter', 'saturn', 'moon', 'solar system', 'orbit', 'atmosphere', 'crater', 'rings', 'asteroid', 'comet', 'dwarf planet', 'space', 'astronomy', 'gravity', 'telescope', 'eclipse', 'nasa', 'rover', 'mission', 'exoplanet'],
        related: ['nasa', 'rover', 'mission', 'geology'],
        synonyms: ['planetary', 'celestial', 'astronomical'],
        intents: ['learning about a planet', 'understanding orbits', 'understanding eclipses'],
        starters: ['Why is Mars red?', 'What is the difference between a planet and a dwarf planet?', 'How do lunar eclipses work?', 'Tell me about Saturn’s rings'],
      },
      Astrophysics: {
        expertise: ['stars', 'black holes', 'galaxies', 'cosmology', 'stellar life cycles', 'dark matter'],
        welcome: 'What corner of the universe are we exploring today?',
        allowed: ['star', 'stars', 'black hole', 'galaxy', 'nebula', 'supernova', 'cosmology', 'universe', 'big bang', 'light year', 'gravity', 'astrophysics', 'dark matter', 'redshift', 'space', 'astronomy', 'neutron star', 'quasar', 'dark energy'],
        related: ['telescope', 'spectrum', 'relativity'],
        synonyms: ['astrophysical', 'cosmic', 'stellar'],
        intents: ['understanding stars', 'understanding black holes', 'understanding the universe'],
        starters: ['How do black holes form?', 'What happens when a star dies?', 'What is dark matter?', 'How big is the observable universe?'],
      },
      Stargazing: {
        expertise: ['constellations', 'observing', 'telescopes', 'night sky events', 'light pollution'],
        welcome: 'Planning a night under the stars? Ask me what to look for.',
        allowed: ['stargazing', 'constellation', 'night sky', 'telescope', 'binoculars', 'planet', 'star', 'moon', 'meteor', 'shower', 'observing', 'light pollution', 'space', 'astronomy', 'aurora', 'eclipse', 'sky map', 'comet viewing'],
        related: ['aurora', 'eclipse', 'sky map'],
        synonyms: ['celestial', 'astronomical'],
        intents: ['finding constellations', 'choosing a telescope', 'planning observation'],
        starters: ['What can I see in the night sky tonight?', 'How do I find the North Star?', 'What telescope should a beginner buy?', 'When is the next meteor shower?'],
      },
      Cosmology: {
        expertise: ['origin of the universe', 'big bang theory', 'expansion', 'cosmic background radiation', 'dark energy', 'multiverse'],
        welcome: 'Ready to explore the origins and fate of the cosmos?',
        allowed: ['cosmology', 'big bang', 'universe', 'expansion', 'inflation', 'cosmic microwave background', 'dark energy', 'dark matter', 'multiverse', 'space-time', 'cosmological constant', 'singularity', 'entropy', 'arrow of time', 'astronomy', 'cosmos'],
        related: ['physics', 'relativity', 'astrophysics'],
        synonyms: ['cosmic', 'cosmological'],
        intents: ['understanding the big bang', 'understanding cosmic expansion', 'learning about dark energy'],
        starters: ['What happened before the Big Bang?', 'How do we know the universe is expanding?', 'What is the cosmic microwave background?', 'Explain dark energy simply'],
      },
      'Space Exploration': {
        expertise: ['rockets', 'space missions', 'ISS', 'spacecraft', 'space agencies', 'future missions'],
        welcome: 'Curious about how we explore space? Ask me about missions and rockets.',
        allowed: ['space', 'rocket', 'rockets', 'launch', 'mission', 'iss', 'space station', 'spacecraft', 'astronaut', 'nasa', 'spacex', 'satellite', 'orbital', 'lunar', 'mars mission', 'artemis', 'voyager', 'telescope', 'jwst', 'starship'],
        related: ['nasa', 'spacex', 'orbital mechanics'],
        synonyms: ['spaceflight', 'astronautics'],
        intents: ['learning about a mission', 'understanding rocket science', 'following space news'],
        starters: ['How does a rocket reach orbit?', 'What is the James Webb Space Telescope doing?', 'How do astronauts live on the ISS?', 'What is the Artemis mission?'],
      },
    },
  },

  Legal: {
    themes: ['Royal', 'Mono', 'Slate'],
    specialties: {
      Immigration: {
        expertise: ['immigration', 'visas', 'residency', 'citizenship', 'immigration procedures', 'immigration policy', 'work permits'],
        welcome: 'What would you like to know about immigration, visas, or residency?',
        allowed: ['immigration', 'immigrant', 'visa', 'visas', 'citizenship', 'residency', 'permanent residency', 'green card', 'work permit', 'student visa', 'asylum', 'naturalization', 'embassy', 'consulate', 'migrate', 'migration', 'relocate', 'move to', 'moving to', 'moving abroad', 'sponsorship', 'h-1b', 'h1b'],
        related: ['work authorization', 'study abroad', 'border', 'policy', 'application'],
        synonyms: ['relocating', 'emigrate'],
        intents: ['moving to another country', 'applying for a visa', 'getting residency', 'understanding immigration requirements', 'visa interviews'],
        starters: ['How can I move to the USA from India?', 'Which visa should I apply for to work abroad?', 'How does the green card process work?', 'What are common reasons visa applications get rejected?'],
        disclaimer: true,
      },
      'Family Law': {
        expertise: ['marriage', 'divorce', 'custody', 'adoption', 'family disputes', 'prenuptial agreements'],
        welcome: 'How can I help with a family law question today?',
        allowed: ['family law', 'divorce', 'marriage', 'custody', 'child support', 'alimony', 'adoption', 'prenup', 'guardianship', 'separation', 'annulment', 'domestic', 'paternity', 'visitation'],
        related: ['court', 'mediation', 'settlement'],
        synonyms: ['matrimonial'],
        intents: ['understanding divorce', 'understanding custody', 'understanding adoption'],
        starters: ['How does child custody get decided?', 'What is the difference between separation and divorce?', 'What is a prenuptial agreement?', 'How does the adoption process generally work?'],
        disclaimer: true,
      },
      'Corporate Law': {
        expertise: ['business formation', 'contracts', 'compliance', 'intellectual property basics', 'corporate governance', 'mergers and acquisitions'],
        welcome: 'What corporate or business-law question can I help with?',
        allowed: ['corporate law', 'business', 'company', 'contract', 'agreement', 'llc', 'incorporation', 'shareholder', 'compliance', 'merger', 'acquisition', 'liability', 'governance', 'startup', 'board', 'articles of incorporation', 'operating agreement', 'non-disclosure', 'nda', 'fiduciary'],
        related: ['trademark', 'patent', 'regulation'],
        synonyms: ['commercial law'],
        intents: ['forming a company', 'understanding a contract', 'understanding compliance'],
        starters: ['What is the difference between an LLC and a corporation?', 'What should a basic contract include?', 'How do I protect my startup’s idea?', 'What is a shareholder agreement?'],
        disclaimer: true,
      },
      'Contract Law': {
        expertise: ['contract formation', 'breach of contract', 'terms and conditions', 'remedies', 'negotiation basics'],
        welcome: 'What contract question can I help you understand?',
        allowed: ['contract', 'contracts', 'breach', 'agreement', 'terms', 'conditions', 'clause', 'liability', 'warranty', 'indemnity', 'signature', 'enforce', 'void', 'consideration', 'offer', 'acceptance', 'termination', 'remedy', 'damages'],
        related: ['corporate law', 'negotiation', 'legal'],
        synonyms: ['contractual'],
        intents: ['understanding a contract clause', 'dealing with a breach', 'learning contract basics'],
        starters: ['What makes a contract legally binding?', 'What is a breach of contract?', 'Explain indemnity clauses', 'What are liquidated damages?'],
        disclaimer: true,
      },
      'Intellectual Property': {
        expertise: ['copyright', 'trademarks', 'patents', 'trade secrets', 'licensing', 'fair use'],
        welcome: 'Need help navigating IP? Ask about copyright, patents, or trademarks.',
        allowed: ['intellectual property', 'copyright', 'trademark', 'patent', 'trade secret', 'licensing', 'license', 'royalty', 'fair use', 'infringement', 'ip', 'brand', 'logo', 'invention', 'provisional patent', 'cease and desist'],
        related: ['corporate law', 'tech law', 'legal'],
        synonyms: ['ip law', 'industrial property'],
        intents: ['understanding copyright', 'protecting an idea', 'learning about patents'],
        starters: ['What is the difference between copyright and trademark?', 'How do I patent an invention?', 'What is fair use?', 'How do I protect my brand name?'],
        disclaimer: true,
      },
      'Employment Law': {
        expertise: ['employment contracts', 'wages and hours', 'termination', 'discrimination', 'workplace rights', 'leaves'],
        welcome: 'What workplace or employment question can I help with?',
        allowed: ['employment law', 'employee', 'employer', 'contract', 'wages', 'salary', 'overtime', 'termination', 'fired', 'layoff', 'discrimination', 'harassment', 'minimum wage', 'benefits', 'leave', 'vacation', 'non-compete', 'severance', 'resignation', 'notice period'],
        related: ['labor law', 'human resources', 'legal'],
        synonyms: ['labor law', 'workplace law'],
        intents: ['understanding my rights', 'dealing with termination', 'understanding a non-compete'],
        starters: ['Can my employer fire me without notice?', 'What is a non-compete clause?', 'What are my rights around overtime pay?', 'What counts as workplace discrimination?'],
        disclaimer: true,
      },
      'Real Estate Law': {
        expertise: ['property purchase', 'leases', 'title and deeds', 'zoning', 'landlord-tenant law'],
        welcome: 'What property or tenancy question can I help with?',
        allowed: ['real estate law', 'property', 'lease', 'rental', 'tenant', 'landlord', 'deed', 'title', 'closing', 'mortgage', 'zoning', 'eviction', 'security deposit', 'homeowners', 'hoa', 'escrow', 'easement', 'foreclosure'],
        related: ['real estate', 'finance', 'legal'],
        synonyms: ['property law', 'land law'],
        intents: ['understanding a lease', 'buying property', 'dealing with a landlord'],
        starters: ['What should I check in a lease agreement?', 'Can a landlord evict without notice?', 'What is the difference between title and deed?', 'What does zoning mean for a property?'],
        disclaimer: true,
      },
      'Consumer Rights': {
        expertise: ['consumer protection', 'returns and refunds', 'warranties', 'deceptive practices', 'complaints'],
        welcome: 'Facing a consumer issue? Ask me about your rights.',
        allowed: ['consumer rights', 'consumer protection', 'refund', 'return', 'warranty', 'guarantee', 'defective', 'product', 'service', 'complaint', 'deceptive', 'false advertising', 'chargeback', 'billing', 'cancellation', 'privacy', 'data breach', 'customer'],
        related: ['contract law', 'retail', 'legal'],
        synonyms: ['buyer rights', 'customer rights'],
        intents: ['getting a refund', 'filing a complaint', 'understanding a warranty'],
        starters: ['Can I return an item without a receipt?', 'What is my warranty coverage?', 'How do I dispute a charge?', 'What counts as false advertising?'],
        disclaimer: true,
      },
    },
  },

  Healthcare: {
    themes: ['Slate', 'Ocean', 'Forest'],
    specialties: {
      'General Practice': {
        expertise: ['general health', 'common symptoms', 'wellness', 'prevention', 'when to see a doctor', 'understanding vitals'],
        welcome: 'What health topic can I help you understand today?',
        allowed: ['health', 'symptom', 'symptoms', 'illness', 'disease', 'doctor', 'medicine', 'treatment', 'wellness', 'prevention', 'fever', 'pain', 'infection', 'diet', 'sleep', 'exercise', 'blood pressure', 'vaccine', 'headache', 'cough', 'cold', 'flu', 'fatigue'],
        related: ['nutrition', 'fitness', 'recovery', 'clinic'],
        synonyms: ['medical', 'clinical'],
        intents: ['understanding symptoms', 'learning about a condition', 'general wellness advice'],
        starters: ['What are common causes of a headache?', 'How can I build a healthier sleep routine?', 'What does blood pressure actually measure?', 'When should I see a doctor for a fever?'],
        disclaimer: true,
      },
      'Mental Health': {
        expertise: ['stress', 'anxiety basics', 'mindfulness', 'healthy habits', 'emotional wellbeing', 'burnout'],
        welcome: 'I can share general wellbeing information — what’s on your mind?',
        allowed: ['mental health', 'stress', 'anxiety', 'mindfulness', 'meditation', 'wellbeing', 'mood', 'burnout', 'self-care', 'sleep', 'relaxation', 'breathing', 'depression', 'panic', 'therapy', 'journaling', 'habits', 'emotional'],
        related: ['therapy', 'journaling', 'habits'],
        synonyms: ['psychological', 'emotional'],
        intents: ['managing stress', 'building healthy habits', 'understanding wellbeing'],
        starters: ['What are some simple ways to manage stress?', 'Explain a basic breathing exercise', 'How does sleep affect mood?', 'What is mindfulness?'],
        disclaimer: true,
      },
      Nutrition: {
        expertise: ['macronutrients', 'micronutrients', 'balanced diet', 'meal planning', 'supplements', 'food labels'],
        welcome: 'What would you like to know about eating well?',
        allowed: ['nutrition', 'nutrient', 'protein', 'carbohydrate', 'fat', 'vitamin', 'mineral', 'calorie', 'diet', 'meal', 'food', 'eating', 'balanced', 'fiber', 'sugar', 'sodium', 'hydration', 'supplement', 'protein shake', 'macro', 'micro'],
        related: ['fitness', 'cooking', 'health'],
        synonyms: ['dietetics', 'dietary'],
        intents: ['planning a diet', 'understanding nutrients', 'reading food labels'],
        starters: ['How much protein do I actually need?', 'What is the difference between good and bad fats?', 'How do I read a nutrition label?', 'What is a balanced plate?'],
        disclaimer: true,
      },
      Fitness: {
        expertise: ['workout programming', 'strength training', 'cardio', 'mobility', 'recovery', 'form and technique'],
        welcome: 'Ready to get moving? Ask about workouts, form, or recovery.',
        allowed: ['fitness', 'workout', 'exercise', 'training', 'strength', 'cardio', 'hiit', 'muscle', 'reps', 'sets', 'gym', 'running', 'lifting', 'squat', 'deadlift', 'bench press', 'mobility', 'stretching', 'recovery', 'protein', 'rest day', 'plank', 'push-up'],
        related: ['nutrition', 'health', 'sports'],
        synonyms: ['exercise science', 'training'],
        intents: ['building a workout plan', 'improving form', 'understanding recovery'],
        starters: ['How do I start strength training?', 'What is the best cardio for fat loss?', 'How many rest days should I take?', 'Fix my squat form'],
        disclaimer: true,
      },
      Cardiology: {
        expertise: ['heart health', 'blood pressure', 'cholesterol', 'exercise for the heart', 'heart disease prevention'],
        welcome: 'What would you like to know about keeping your heart healthy?',
        allowed: ['heart', 'cardiac', 'cardiology', 'blood pressure', 'cholesterol', 'artery', 'palpitation', 'stroke', 'heart attack', 'ecg', 'heart rate', 'aerobic', 'exercise', 'sodium', 'hypertension', 'atrial', 'chest pain', 'cardio'],
        related: ['nutrition', 'fitness', 'health'],
        synonyms: ['heart health'],
        intents: ['understanding blood pressure', 'preventing heart disease', 'interpreting heart health'],
        starters: ['What is a healthy blood pressure?', 'How does cholesterol affect the heart?', 'What are the warning signs of a heart attack?', 'How can I improve my heart health?'],
        disclaimer: true,
      },
      Dermatology: {
        expertise: ['skin care basics', 'acne', 'eczema', 'sun protection', 'skin conditions', 'skincare routines'],
        welcome: 'Ask me anything about skin care and common skin conditions.',
        allowed: ['skin', 'dermatology', 'acne', 'eczema', 'psoriasis', 'rash', 'sunburn', 'sunscreen', 'spf', 'moisturizer', 'cleanser', 'skin care', 'skincare', 'wrinkles', 'pigmentation', 'dandruff', 'pores', 'exfoliate', 'retinol', 'serum'],
        related: ['beauty', 'nutrition', 'health'],
        synonyms: ['dermatological', 'skin health'],
        intents: ['building a skincare routine', 'understanding acne', 'choosing sunscreen'],
        starters: ['How do I build a simple skincare routine?', 'What actually causes acne?', 'How much SPF do I need?', 'What is the difference between a serum and a moisturizer?'],
        disclaimer: true,
      },
      Pediatrics: {
        expertise: ['child health', 'vaccinations', 'growth milestones', 'common childhood illnesses', 'child nutrition'],
        welcome: 'Questions about your child’s health? I can share general guidance.',
        allowed: ['pediatrics', 'child', 'children', 'baby', 'infant', 'toddler', 'vaccine', 'vaccination', 'growth', 'milestone', 'fever', 'rash', 'feeding', 'breastfeeding', 'formula', 'sleep training', 'teething', 'diaper', 'cry'],
        related: ['family health', 'nutrition', 'healthcare'],
        synonyms: ['pediatric', 'childrens health'],
        intents: ['understanding a milestone', 'childhood illness questions', 'feeding questions'],
        starters: ['What vaccines does a baby need?', 'When do babies reach common milestones?', 'Is a mild fever in a child concerning?', 'How much sleep does a toddler need?'],
        disclaimer: true,
      },
      Dental: {
        expertise: ['oral hygiene', 'brushing and flossing', 'cavities', 'gum health', 'dental procedures'],
        welcome: 'What dental or oral-care question can I help with?',
        allowed: ['dental', 'teeth', 'tooth', 'gum', 'gums', 'cavity', 'cavities', 'brush', 'brushing', 'floss', 'flossing', 'mouthwash', 'whitening', 'braces', 'root canal', 'wisdom tooth', 'plaque', 'tartar', 'bad breath', 'sensitivity', 'orthodontics'],
        related: ['health', 'nutrition', 'hygiene'],
        synonyms: ['oral health', 'dentistry'],
        intents: ['improving brushing technique', 'understanding a procedure', 'managing sensitivity'],
        starters: ['How often should I floss?', 'What causes cavities?', 'How does teeth whitening work?', 'What should I do for sensitive teeth?'],
        disclaimer: true,
      },
      Pharmacy: {
        expertise: ['medication basics', 'over-the-counter drugs', 'drug interactions', 'reading prescriptions', 'safe storage'],
        welcome: 'Have a medication question? Ask me (educational, not medical advice).',
        allowed: ['medication', 'medicine', 'drug', 'drugs', 'prescription', 'over-the-counter', 'otc', 'dosage', 'side effect', 'interaction', 'antibiotic', 'painkiller', 'ibuprofen', 'paracetamol', 'aspirin', 'pharmacist', 'pharmacy', 'expiry', 'tablet', 'capsule', 'syrup'],
        related: ['health', 'general practice', 'safety'],
        synonyms: ['pharmaceutical', 'drugs'],
        intents: ['understanding a medication', 'checking for interactions', 'reading a prescription'],
        starters: ['What is the difference between ibuprofen and paracetamol?', 'Can I take these two medicines together?', 'What are common side effects of antibiotics?', 'How should I store my medications?'],
        disclaimer: true,
      },
      'First Aid': {
        expertise: ['emergency response', 'CPR basics', 'wound care', 'burns', 'choking', 'sprains and fractures'],
        welcome: 'What first-aid situation would you like to learn to handle?',
        allowed: ['first aid', 'cpr', 'emergency', 'wound', 'bleeding', 'burn', 'choking', 'sprain', 'fracture', 'bandage', 'splint', 'resuscitation', 'unconscious', 'seizure', 'poisoning', 'shock', 'cut', 'scrape', 'heatstroke', 'hypothermia'],
        related: ['health', 'safety', 'emergency'],
        synonyms: ['emergency care', 'trauma care'],
        intents: ['learning cpr', 'treating a wound', 'responding to an emergency'],
        starters: ['How do I perform CPR?', 'What should I do if someone is choking?', 'How do I treat a minor burn?', 'What goes in a first aid kit?'],
        disclaimer: true,
      },
      Sleep: {
        expertise: ['sleep hygiene', 'insomnia basics', 'circadian rhythm', 'naps', 'night shift sleep'],
        welcome: 'Want better sleep? Ask me about routines, habits, and sleep science.',
        allowed: ['sleep', 'insomnia', 'dream', 'dreams', 'nap', 'bedtime', 'circadian', 'melatonin', 'sleep hygiene', 'rest', 'night', 'wake', 'tired', 'fatigue', 'blue light', 'caffeine', 'sleep apnea', 'snoring', 'paralysis'],
        related: ['health', 'psychology', 'wellness'],
        synonyms: ['sleep health'],
        intents: ['improving sleep', 'understanding insomnia', 'building a bedtime routine'],
        starters: ['How can I fall asleep faster?', 'What is sleep hygiene?', 'How much sleep do adults need?', 'What is sleep apnea?'],
        disclaimer: true,
      },
    },
  },

  Banking: {
    themes: ['Royal', 'Slate', 'Mono'],
    specialties: {
      'Retail Banking': {
        expertise: ['accounts', 'savings', 'deposits', 'cards', 'everyday banking', 'online banking'],
        welcome: 'How can I help with your everyday banking questions?',
        allowed: ['bank', 'banking', 'account', 'savings', 'checking', 'deposit', 'withdrawal', 'debit', 'atm', 'balance', 'transfer', 'statement', 'overdraft', 'interest', 'credit card', 'debit card', 'mobile banking', 'net banking', 'branch', 'cheque', 'check'],
        related: ['budgeting', 'fees', 'online banking'],
        synonyms: ['financial'],
        intents: ['opening an account', 'understanding fees', 'understanding interest'],
        starters: ['What is the difference between savings and checking?', 'How does compound interest work?', 'What is an overdraft fee?', 'How can I start budgeting my income?'],
      },
      Investment: {
        expertise: ['investing basics', 'stocks', 'bonds', 'funds', 'risk and diversification', 'retirement accounts'],
        welcome: 'Curious about investing basics? Ask away (educational, not advice).',
        allowed: ['investment', 'invest', 'investing', 'stock', 'stocks', 'bond', 'bonds', 'mutual fund', 'etf', 'portfolio', 'dividend', 'risk', 'diversification', 'return', 'market', 'compound', 'retirement', 'index fund', 'asset', 'allocation', 'sip'],
        related: ['retirement', 'index fund', 'asset'],
        synonyms: ['financial'],
        intents: ['understanding investing', 'understanding stocks vs bonds', 'understanding risk'],
        starters: ['What is the difference between stocks and bonds?', 'Explain diversification simply', 'What is an index fund?', 'How does compound growth help investors?'],
        disclaimer: true,
      },
      'Digital Banking': {
        expertise: ['mobile banking apps', 'online transfers', 'upi', 'payments', 'digital wallets', 'security online'],
        welcome: 'Questions about digital banking and payments? Ask away.',
        allowed: ['digital banking', 'online banking', 'mobile banking', 'app', 'transfer', 'upi', 'wallet', 'payment', 'payments', 'net banking', 'otp', 'qr code', 'scan', 'autopay', 'recurring', 'e-statements', 'online payment', 'digital wallet', 'paytm', 'gpay', 'phonepe'],
        related: ['retail banking', 'security', 'finance'],
        synonyms: ['fintech', 'e-banking'],
        intents: ['setting up online banking', 'making an online payment', 'staying safe online'],
        starters: ['How do I set up UPI?', 'What is the difference between a wallet and a bank account?', 'How safe is online banking?', 'What should I do if I get an OTP I did not request?'],
      },
      'Credit & Loans': {
        expertise: ['personal loans', 'home loans', 'car loans', 'credit scores', 'interest rates', 'EMI'],
        welcome: 'Thinking about a loan or credit? Ask me about the basics.',
        allowed: ['loan', 'loans', 'credit', 'credit score', 'cibil', 'emi', 'interest rate', 'personal loan', 'home loan', 'car loan', 'mortgage', 'borrow', 'lender', 'prepayment', 'foreclosure', 'loan tenure', 'principal', 'apr', 'debt'],
        related: ['retail banking', 'investment', 'finance'],
        synonyms: ['borrowing', 'financing'],
        intents: ['understanding loans', 'improving a credit score', 'comparing interest rates'],
        starters: ['What is a credit score and why does it matter?', 'How is EMI calculated?', 'Fixed vs floating interest rate?', 'How do I improve my credit score?'],
        disclaimer: true,
      },
    },
  },

  Technology: {
    themes: ['Midnight', 'Terminal', 'Slate'],
    specialties: {
      Hardware: {
        expertise: ['CPUs and GPUs', 'PC building and upgrades', 'component compatibility', 'cooling and thermals', 'benchmarks and real-world performance'],
        welcome: 'Building or upgrading? Ask me about parts, compatibility, or performance.',
        allowed: ['hardware', 'cpu', 'gpu', 'processor', 'graphics card', 'motherboard', 'ram', 'memory', 'ssd', 'hdd', 'storage', 'power supply', 'psu', 'cooling', 'cooler', 'thermal paste', 'overclock', 'overclocking', 'bios', 'chipset', 'socket', 'ddr4', 'ddr5', 'pcie', 'nvme', 'benchmark', 'bottleneck', 'intel', 'amd', 'ryzen', 'nvidia', 'geforce', 'radeon', 'rtx', 'laptop', 'desktop', 'pc build', 'monitor', 'keyboard'],
        related: ['upgrade path', 'compatibility', 'build budget', 'thermals', 'power draw'],
        synonyms: ['components', 'parts', 'rig', 'pc'],
        intents: ['choosing a CPU or GPU', 'building a PC', 'upgrading a component', 'comparing two products', 'fixing overheating'],
        starters: ['Which is better for gaming — Intel or AMD?', 'What parts do I need for a budget PC build?', 'How do I stop my CPU from overheating?', 'What is the difference between DDR4 and DDR5?'],
      },
      Networking: {
        expertise: ['home and office networks', 'routers and Wi-Fi', 'IP addressing', 'troubleshooting connectivity', 'bandwidth and latency'],
        welcome: 'Network trouble or setup question? Let’s sort it out.',
        allowed: ['network', 'networking', 'router', 'modem', 'wifi', 'wi-fi', 'ethernet', 'lan', 'wan', 'ip address', 'dns', 'dhcp', 'subnet', 'bandwidth', 'latency', 'ping', 'packet', 'firewall', 'vpn', 'broadband', 'fiber', '5g', 'signal', 'access point', 'mesh network'],
        related: ['speed test', 'port forwarding', 'network security'],
        synonyms: ['internet connection', 'connectivity'],
        intents: ['fixing slow internet', 'setting up a router', 'understanding IP addresses', 'improving wifi coverage'],
        starters: ['Why is my Wi-Fi slower than the speed I pay for?', 'What is the difference between a router and a modem?', 'How do I improve Wi-Fi coverage at home?', 'What does an IP address actually identify?'],
      },
      Cybersecurity: {
        expertise: ['security basics', 'passwords', 'phishing', 'encryption concepts', 'safe practices', 'incident response'],
        welcome: 'Want to lock things down? Ask me about staying secure.',
        allowed: ['security', 'cybersecurity', 'password', 'phishing', 'malware', 'encryption', 'firewall', 'vpn', 'hacker', 'breach', 'two-factor', 'authentication', 'privacy', 'vulnerability', 'antivirus', 'ransomware', 'zero-day', 'patching', 'backup', 'social engineering', 'mfa'],
        related: ['network security', 'data protection'],
        synonyms: ['infosec', 'cyber'],
        intents: ['staying secure online', 'understanding phishing', 'understanding encryption'],
        starters: ['How do I create a strong password?', 'What is phishing and how do I avoid it?', 'What does two-factor authentication do?', 'Explain encryption in simple terms'],
      },
      AI: {
        expertise: ['AI concepts', 'machine learning basics', 'neural networks', 'how models work', 'generative AI'],
        welcome: 'Curious about AI? Ask me how it works.',
        allowed: ['ai', 'artificial intelligence', 'machine learning', 'ml', 'neural network', 'model', 'training', 'dataset', 'algorithm', 'deep learning', 'llm', 'chatbot', 'prediction', 'gpt', 'transformer', 'token', 'prompt', 'hallucination', 'fine-tuning', 'agent'],
        related: ['data science', 'automation'],
        synonyms: ['intelligent systems'],
        intents: ['understanding AI', 'understanding machine learning', 'how models work'],
        starters: ['What is machine learning, simply?', 'How does a neural network work?', 'What is the difference between AI and ML?', 'How are chatbots trained?'],
      },
      Programming: {
        expertise: ['software development', 'languages', 'frameworks', 'debugging', 'code quality', 'APIs'],
        welcome: 'What would you like to build or debug today?',
        allowed: ['programming', 'software', 'code', 'coding', 'developer', 'python', 'javascript', 'typescript', 'java', 'go', 'rust', 'react', 'node', 'api', 'framework', 'library', 'debugging', 'bug', 'refactor', 'tests', 'deploy', 'git', 'github', 'open source', 'language', 'languages', 'memory', 'memory leak', 'leak', 'learn coding'],
        related: ['computer science', 'algorithms', 'web development'],
        synonyms: ['software development', 'coding'],
        intents: ['writing code', 'debugging', 'choosing a framework'],
        starters: ['What language should I learn first?', 'How do I debug a memory leak?', 'Explain REST vs GraphQL', 'How do I structure a large React app?'],
      },
      Cloud: {
        expertise: ['cloud computing', 'IaaS PaaS SaaS', 'AWS, Azure, GCP', 'containers', 'serverless', 'deployment'],
        welcome: 'Cloud architecture or deployment question? Let’s dig in.',
        allowed: ['cloud', 'aws', 'azure', 'gcp', 'google cloud', 'ec2', 's3', 'lambda', 'serverless', 'container', 'docker', 'kubernetes', 'k8s', 'deployment', 'scaling', 'load balancer', 'virtual machine', 'vm', 'instance', 'bucket', 'infrastructure', 'terraform', 'devops', 'ci', 'cd'],
        related: ['devops', 'networking', 'security'],
        synonyms: ['cloud computing', 'hosting'],
        intents: ['understanding cloud services', 'deploying an app', 'choosing a provider'],
        starters: ['What is the difference between IaaS, PaaS, and SaaS?', 'When should I use serverless?', 'What is Kubernetes in simple terms?', 'How do I choose between AWS, Azure, and GCP?'],
      },
      DevOps: {
        expertise: ['CI/CD', 'automation', 'monitoring', 'infrastructure as code', 'reliability', 'release management'],
        welcome: 'CI/CD, automation, or reliability question? Ask away.',
        allowed: ['devops', 'ci', 'cd', 'pipeline', 'jenkins', 'github actions', 'gitlab', 'automation', 'deploy', 'release', 'monitoring', 'observability', 'logging', 'alert', 'terraform', 'ansible', 'docker', 'kubernetes', 'sre', 'sla', 'incident', 'rollback', 'staging', 'production', 'monitor', 'web service', 'service health', 'uptime'],
        related: ['cloud', 'software', 'infrastructure'],
        synonyms: ['site reliability', 'platform engineering'],
        intents: ['setting up ci/cd', 'automating deploys', 'improving reliability'],
        starters: ['What is a CI/CD pipeline?', 'How do I monitor a web service?', 'What is infrastructure as code?', 'How do I handle a production incident?'],
      },
      Databases: {
        expertise: ['SQL', 'NoSQL', 'database design', 'query optimization', 'indexing', 'data modeling'],
        welcome: 'Database design or query question? Let’s get to the data.',
        allowed: ['database', 'databases', 'sql', 'nosql', 'mysql', 'postgres', 'postgresql', 'sqlite', 'mongodb', 'redis', 'query', 'table', 'index', 'schema', 'normalization', 'join', 'transaction', 'acid', 'primary key', 'foreign key', 'migration', 'etl', 'warehouse'],
        related: ['data science', 'backend', 'software'],
        synonyms: ['data store', 'db'],
        intents: ['designing a schema', 'optimizing a query', 'choosing a database'],
        starters: ['SQL vs NoSQL — which should I use?', 'How do I index a database table?', 'Explain JOINs in SQL', 'What is database normalization?'],
      },
      'Mobile Development': {
        expertise: ['iOS and Android', 'React Native', 'Flutter', 'app architecture', 'mobile UX', 'app store'],
        welcome: 'Building a mobile app? Ask me about tools, architecture, or stores.',
        allowed: ['mobile', 'app', 'apps', 'android', 'ios', 'iphone', 'flutter', 'react native', 'swift', 'kotlin', 'xcode', 'android studio', 'play store', 'app store', 'push notification', 'offline', 'api', 'sdk', 'native', 'cross-platform', 'mvvm', 'material design'],
        related: ['software', 'design', 'web development'],
        synonyms: ['app development', 'mobile dev'],
        intents: ['choosing a framework', 'building an app', 'publishing to a store'],
        starters: ['React Native or Flutter?', 'How do I publish an app to the App Store?', 'What is a good architecture for a mobile app?', 'How do push notifications work?'],
      },
      'Web Development': {
        expertise: ['frontend', 'backend', 'HTML CSS JS', 'frameworks', 'performance', 'accessibility'],
        welcome: 'Frontend, backend, or full-stack question? Ask away.',
        allowed: ['web', 'website', 'frontend', 'backend', 'full-stack', 'html', 'css', 'javascript', 'react', 'vue', 'angular', 'next', 'node', 'express', 'api', 'rest', 'graphql', 'responsive', 'seo', 'accessibility', 'performance', 'browser', 'ssr', 'spa'],
        related: ['software', 'design', 'databases'],
        synonyms: ['web dev', 'front-end'],
        intents: ['building a website', 'choosing a framework', 'improving performance'],
        starters: ['What is the difference between SSR and SPA?', 'How do I make a site accessible?', 'React vs Vue in 2026', 'How do I optimize page load speed?'],
      },
      'Data Science': {
        expertise: ['statistics', 'data analysis', 'visualization', 'pandas', 'machine learning', 'experimentation'],
        welcome: 'Data analysis or ML question? Let’s extract insight from data.',
        allowed: ['data science', 'data', 'analytics', 'statistics', 'pandas', 'numpy', 'jupyter', 'python', 'visualization', 'chart', 'regression', 'classification', 'clustering', 'feature', 'model', 'dataset', 'correlation', 'a/b testing', 'hypothesis', 'dashboard', 'sql', 'tableau', 'power bi'],
        related: ['machine learning', 'databases', 'statistics'],
        synonyms: ['data analytics', 'data analysis'],
        intents: ['analyzing data', 'building a model', 'making a visualization'],
        starters: ['What is the difference between correlation and causation?', 'How do I clean a messy dataset?', 'Explain A/B testing', 'When should I use regression vs classification?'],
      },
    },
  },

  Tourism: {
    themes: ['Ocean', 'Forest', 'Sunset'],
    specialties: {
      'Trip Planning': {
        expertise: ['itineraries', 'destinations', 'budgeting trips', 'travel tips', 'transport options'],
        welcome: 'Where are you headed? Let’s plan the trip.',
        allowed: ['travel', 'trip', 'vacation', 'holiday', 'itinerary', 'destination', 'flight', 'hotel', 'tour', 'sightseeing', 'packing', 'budget travel', 'backpacking', 'tourist', 'landmark', 'transport', 'train', 'bus', 'car rental', 'guide', 'map'],
        related: ['passport', 'visa requirements', 'local transport'],
        synonyms: ['traveling', 'journey'],
        intents: ['planning a trip', 'building an itinerary', 'finding destinations'],
        starters: ['Plan a 3-day itinerary for Paris', 'What should I pack for a beach vacation?', 'How do I travel on a tight budget?', 'Suggest destinations for a first international trip'],
      },
      Hotels: {
        expertise: ['accommodation', 'hotel types', 'booking tips', 'amenities', 'reviews'],
        welcome: 'Looking for the right place to stay? Ask me anything about hotels.',
        allowed: ['hotel', 'hostel', 'resort', 'accommodation', 'booking', 'room', 'check-in', 'amenities', 'stay', 'airbnb', 'lodging', 'suite', 'boutique', 'resort', 'villa', 'free cancellation', 'upgrade', 'reviews'],
        related: ['reviews', 'location', 'budget'],
        synonyms: ['lodging'],
        intents: ['choosing a hotel', 'understanding booking', 'finding amenities'],
        starters: ['How do I choose a good hotel?', 'What is the difference between a hostel and a hotel?', 'What amenities should I look for?', 'How can I find good deals on rooms?'],
      },
      'Budget Travel': {
        expertise: ['cheap flights', 'budget accommodation', 'money saving', 'free attractions', 'student travel'],
        welcome: 'Want to see the world without breaking the bank? Ask me how.',
        allowed: ['budget', 'cheap', 'deal', 'deals', 'discount', 'student', 'backpacking', 'hostel', 'couchsurfing', 'budget travel', 'low cost', 'saving', 'fare', 'sales', 'off-season', 'street food', 'free', 'walking tour'],
        related: ['trip planning', 'flights', 'money'],
        synonyms: ['affordable travel', 'backpacker'],
        intents: ['finding cheap flights', 'saving money', 'budget planning'],
        starters: ['How do I find cheap flights?', 'What are the cheapest destinations in Europe?', 'How do I travel the world on a budget?', 'When is the off-season in Southeast Asia?'],
      },
      'Cultural Travel': {
        expertise: ['heritage sites', 'museums', 'local customs', 'festivals', 'art and architecture'],
        welcome: 'Interested in culture, history, and local life? Ask me about it.',
        allowed: ['culture', 'cultural', 'heritage', 'museum', 'festival', 'tradition', 'customs', 'architecture', 'monument', 'art', 'gallery', 'temple', 'cathedral', 'historic', 'local', 'food tour', 'craft', 'ceremony', 'unesco'],
        related: ['history', 'art', 'trip planning'],
        synonyms: ['cultural tourism'],
        intents: ['planning a cultural trip', 'understanding local customs', 'finding museums'],
        starters: ['What are the top heritage sites in Rome?', 'How do I respect local customs when traveling?', 'Suggest a museum itinerary for London', 'What festivals happen in Japan in spring?'],
      },
    },
  },

  Restaurant: {
    themes: ['Sunset', 'Amber', 'Mono'],
    specialties: {
      Menu: {
        expertise: ['dishes', 'cuisines', 'ingredients', 'recommendations', 'dietary options'],
        welcome: 'Hungry for ideas? Ask me about dishes and cuisines.',
        allowed: ['menu', 'dish', 'food', 'cuisine', 'recipe', 'ingredient', 'meal', 'starter', 'dessert', 'vegetarian', 'vegan', 'gluten-free', 'flavor', 'pairing', 'dining', 'appetizer', 'entree', 'main course', 'side', 'plating'],
        related: ['nutrition', 'portion', 'allergen'],
        synonyms: ['culinary', 'eatery'],
        intents: ['choosing a dish', 'understanding a cuisine', 'finding dietary options'],
        starters: ['Suggest a 3-course Italian dinner', 'What is a good vegetarian main dish?', 'What wine pairs with grilled salmon?', 'Explain the difference between ramen and pho'],
      },
      'Cuisine & Chefs': {
        expertise: ['regional cuisines', 'signature dishes', 'cooking styles', 'famous chefs', 'restaurant trends'],
        welcome: 'Tell me your craving — I know cuisines, dishes, and dining trends.',
        allowed: ['cuisine', 'chef', 'restaurant', 'dining', 'signature dish', 'regional', 'french', 'italian', 'japanese', 'thai', 'indian', 'fusion', 'michelin', 'fine dining', 'street food', 'gastronomy', 'trend', 'flavor profile'],
        related: ['menu', 'cooking', 'food'],
        synonyms: ['gastronomy', 'culinary arts'],
        intents: ['learning about a cuisine', 'finding a restaurant type', 'understanding food trends'],
        starters: ['What makes French cuisine distinctive?', 'What is molecular gastronomy?', 'How do I pick a Michelin-starred restaurant?', 'What is the difference between Cajun and Creole?'],
      },
      'Wine & Pairing': {
        expertise: ['wine varieties', 'food and wine pairing', 'tasting notes', 'serving temperature', 'buying wine'],
        welcome: 'Wine question? Ask about varieties, pairings, or picking a bottle.',
        allowed: ['wine', 'wines', 'red wine', 'white wine', 'rosé', 'sparkling', 'champagne', 'pairing', 'tasting', 'notes', 'tannin', 'varietal', 'cabernet', 'merlot', 'chardonnay', 'pinot', 'sommelier', 'vintage', 'decant', 'cork'],
        related: ['menu', 'dining', 'food'],
        synonyms: ['oenology', 'viticulture'],
        intents: ['pairing wine with food', 'choosing a bottle', 'understanding tasting notes'],
        starters: ['What wine goes with steak?', 'What is the difference between a varietal and a blend?', 'How do I taste wine properly?', 'Should I decant red wine?'],
      },
      'Kitchen Techniques': {
        expertise: ['knife skills', 'cooking methods', 'sauces', 'dough and pastry', 'temperature control'],
        welcome: 'Level up your cooking — ask me about techniques and methods.',
        allowed: ['technique', 'knife', 'chopping', 'saute', 'braise', 'roast', 'grill', 'sear', 'poach', 'steam', 'sauce', 'roux', 'emulsion', 'dough', 'pastry', 'proof', 'knead', 'sous vide', 'temperature', 'rest', 'caramelize', 'blanch', 'shred'],
        related: ['cooking', 'menu', 'ingredients'],
        synonyms: ['culinary technique', 'cooking method'],
        intents: ['learning a technique', 'fixing a cooking problem', 'understanding methods'],
        starters: ['How do I make a roux?', 'What is the difference between braising and stewing?', 'How do I get a good sear?', 'What does "sous vide" mean?'],
      },
      'Food Safety': {
        expertise: ['food storage', 'cross-contamination', 'safe temperatures', 'expiry dates', 'kitchen hygiene'],
        welcome: 'Ask me about safe food handling, storage, and hygiene.',
        allowed: ['food safety', 'food poisoning', 'storage', 'refrigerate', 'freeze', 'thaw', 'cross-contamination', 'temperature', '165', 'expiry', 'expiration', 'best before', 'hygiene', 'sanitize', 'cutting board', 'raw', 'undercooked', 'shelf life', 'leftover', 'reheat'],
        related: ['kitchen', 'health', 'cooking'],
        synonyms: ['food hygiene'],
        intents: ['storing food safely', 'avoiding contamination', 'understanding expiry dates'],
        starters: ['How long can leftovers stay in the fridge?', 'What is the danger zone for food?', 'How do I thaw meat safely?', 'Can I eat food past its best-before date?'],
      },
    },
  },

  Fashion: {
    themes: ['Sunset', 'Mono', 'Amber'],
    specialties: {
      Styling: {
        expertise: ['outfits', 'color coordination', 'occasions', 'wardrobe basics', 'body types'],
        welcome: 'Let’s put a great look together. What’s the occasion?',
        allowed: ['fashion', 'style', 'outfit', 'clothing', 'wardrobe', 'color', 'accessory', 'trend', 'dress', 'shoes', 'look', 'styling', 'wear', 'apparel', 'occasion', 'formal', 'casual', 'business casual', 'interview', 'body type', 'proportion'],
        related: ['seasonal', 'capsule wardrobe', 'fabric'],
        synonyms: ['fashionable', 'trendy'],
        intents: ['building an outfit', 'coordinating colors', 'dressing for an occasion'],
        starters: ['What should I wear to a job interview?', 'How do I build a capsule wardrobe?', 'Which colors go well together?', 'How do I dress smart-casual?'],
      },
      'Wardrobe & Capsules': {
        expertise: ['capsule wardrobes', 'closet organization', 'essential pieces', 'versatility', 'buying smart'],
        welcome: 'Want a streamlined, versatile wardrobe? Ask me how to build one.',
        allowed: ['wardrobe', 'capsule', 'closet', 'clothes', 'essentials', 'basics', 'versatile', 'minimalist', 'declutter', 'organize', 'pieces', 'neutral', 'investment piece', 'timeless', 'seasonal rotation', 'shopping list'],
        related: ['styling', 'sustainability', 'fashion'],
        synonyms: ['closet', 'clothing collection'],
        intents: ['building a capsule wardrobe', 'decluttering the closet', 'choosing essentials'],
        starters: ['What is a capsule wardrobe?', 'What are the 10 essential pieces every wardrobe needs?', 'How do I declutter my closet?', 'How do I shop for versatile basics?'],
      },
      'Textiles & Fabrics': {
        expertise: ['fabric types', 'care and washing', 'natural vs synthetic', 'quality and durability', 'fabric properties'],
        welcome: 'Ask me about fabrics — types, care, and how to spot quality.',
        allowed: ['fabric', 'fabrics', 'cotton', 'linen', 'wool', 'silk', 'polyester', 'nylon', 'viscose', 'denim', 'leather', 'suede', 'knit', 'woven', 'thread count', 'wash', 'dry clean', 'shrink', 'pilling', 'breathable', 'waterproof', 'textile'],
        related: ['fashion', 'care', 'quality'],
        synonyms: ['material', 'textiles'],
        intents: ['understanding a fabric', 'caring for clothes', 'choosing quality fabrics'],
        starters: ['What is the difference between cotton and linen?', 'How do I wash silk?', 'What does thread count mean?', 'How do I stop my sweater from pilling?'],
      },
      'Sustainable Fashion': {
        expertise: ['slow fashion', 'ethical brands', 'secondhand shopping', 'repair and care', 'environmental impact'],
        welcome: 'Want a greener wardrobe? Ask me about sustainable fashion.',
        allowed: ['sustainable', 'sustainability', 'slow fashion', 'ethical', 'eco-friendly', 'organic cotton', 'recycled', 'secondhand', 'thrift', 'vintage', 'upcycle', 'repair', 'mend', 'fast fashion', 'carbon footprint', 'vegan leather', 'circular fashion', 'fashion waste'],
        related: ['textiles', 'environment', 'wardrobe'],
        synonyms: ['green fashion', 'ethical fashion'],
        intents: ['shopping sustainably', 'understanding impact', 'repairing clothes'],
        starters: ['What is fast fashion and why does it matter?', 'How do I shop more sustainably?', 'Is vegan leather actually better?', 'How do I make my clothes last longer?'],
      },
    },
  },
};
