// ============================================================
// SCARLET DOMAIN KNOWLEDGE — PART 5
// ============================================================

export const DOMAIN_PART5 = {
  Environment: {
    themes: ['Forest', 'Ocean', 'Emerald'],
    specialties: {
      'Climate Change': {
        expertise: ['climate science', 'global warming', 'emissions', 'mitigation', 'adaptation'],
        welcome: 'Climate question? Ask about change, emissions, or solutions.',
        allowed: ['climate change', 'climate', 'global warming', 'warming', 'greenhouse', 'emission', 'carbon', 'co2', 'methane', 'temperature', 'sea level', 'glacier', 'ipcc', 'mitigation', 'adaptation', 'net zero', 'carbon offset'],
        related: ['environment', 'science', 'energy'],
        synonyms: ['climate crisis', 'global heating'],
        intents: ['understanding climate change', 'reducing emissions', 'learning about solutions'],
        starters: ['What is the greenhouse effect?', 'How does climate change affect the oceans?', 'What is net zero?', 'How can I reduce my carbon footprint?'],
      },
      Conservation: {
        expertise: ['conservation', 'biodiversity', 'endangered species', 'protected areas', 'wildlife'],
        welcome: 'Conservation question? Ask about species, habitats, or protection.',
        allowed: ['conservation', 'biodiversity', 'endangered', 'species', 'habitat', 'wildlife', 'reserve', 'national park', 'protected', 'poaching', 'reintroduction', 'corridor', 'ecosystem', 'keystone', 'conservationist'],
        related: ['environment', 'biology', 'nature'],
        synonyms: ['preservation', 'environmental protection'],
        intents: ['understanding conservation', 'protecting species', 'learning about habitats'],
        starters: ['Why is biodiversity important?', 'How do national parks protect wildlife?', 'What is an endangered species?', 'How do I support conservation?'],
      },
      'Renewable Energy': {
        expertise: ['solar', 'wind', 'hydro', 'geothermal', 'bioenergy', 'grid storage'],
        welcome: 'Renewable energy question? Ask about solar, wind, or storage.',
        allowed: ['renewable', 'renewable energy', 'solar', 'solar panel', 'photovoltaic', 'pv', 'wind', 'turbine', 'hydro', 'geothermal', 'biomass', 'bioenergy', 'storage', 'battery', 'grid', 'inverter', 'net metering', 'off-grid'],
        related: ['environment', 'energy', 'technology'],
        synonyms: ['clean energy', 'green energy'],
        intents: ['going solar', 'understanding wind power', 'learning about storage'],
        starters: ['How do solar panels work?', 'How much does a solar system cost?', 'What is net metering?', 'Can renewable energy replace fossil fuels?'],
      },
      Recycling: {
        expertise: ['recycling', 'sorting', 'plastics', 'waste', 'recycling systems'],
        welcome: 'Recycling question? Ask about what to recycle, or systems.',
        allowed: ['recycling', 'recycle', 'recyclable', 'plastic', 'glass', 'paper', 'cardboard', 'metal', 'compost', 'single-stream', 'sorting', 'contamination', 'downcycle', 'upcycle', 'e-waste', 'landfill', 'waste'],
        related: ['environment', 'waste', 'sustainability'],
        synonyms: ['waste management', 'recycling programs'],
        intents: ['understanding recycling', 'sorting waste', 'reducing plastic'],
        starters: ['What can I actually recycle?', 'How does single-stream recycling work?', 'Why is plastic recycling hard?', 'How do I reduce waste at home?'],
      },
      Wildlife: {
        expertise: ['wildlife', 'animals', 'habitats', 'behavior', 'conservation status'],
        welcome: 'Wildlife question? Ask about animals, behavior, or habitats.',
        allowed: ['wildlife', 'animal', 'animals', 'mammal', 'bird', 'reptile', 'amphibian', 'insect', 'habitat', 'behavior', 'migration', 'hibernation', 'food chain', 'predator', 'prey', 'camouflage', 'endangered'],
        related: ['environment', 'biology', 'conservation'],
        synonyms: ['fauna', 'animal kingdom'],
        intents: ['learning about animals', 'understanding behavior', 'protecting wildlife'],
        starters: ['How do animals migrate?', 'What is a food chain?', 'Why do some animals hibernate?', 'How do animals adapt to the desert?'],
      },
      'Ocean Conservation': {
        expertise: ['oceans', 'coral reefs', 'plastic pollution', 'overfishing', 'marine reserves'],
        welcome: 'Ocean conservation question? Ask about reefs, pollution, or fishing.',
        allowed: ['ocean conservation', 'ocean', 'marine', 'coral', 'reef', 'bleaching', 'plastic', 'pollution', 'overfishing', 'trawling', 'marine reserve', 'sanctuary', 'bycatch', 'seagrass', 'mangrove', 'acidification'],
        related: ['environment', 'ocean science', 'conservation'],
        synonyms: ['marine conservation', 'sea protection'],
        intents: ['protecting reefs', 'reducing plastic', 'understanding overfishing'],
        starters: ['What is coral bleaching?', 'How does plastic pollution affect oceans?', 'What is overfishing?', 'How do marine reserves help?'],
      },
      Sustainability: {
        expertise: ['sustainability', 'sustainable living', 'circular economy', 'footprint', 'green choices'],
        welcome: 'Sustainability question? Ask about living greener or systems.',
        allowed: ['sustainability', 'sustainable', 'sustainable living', 'circular economy', 'footprint', 'carbon footprint', 'zero waste', 'minimalism', 'eco-friendly', 'green', 'sustainable choices', 'slow living', 'repair', 'reuse', 'sharing economy'],
        related: ['environment', 'lifestyle', 'business'],
        synonyms: ['sustainable living', 'green living'],
        intents: ['living sustainably', 'reducing footprint', 'making green choices'],
        starters: ['How do I start living sustainably?', 'What is the circular economy?', 'What is zero waste?', 'How do I calculate my carbon footprint?'],
      },
      Pollution: {
        expertise: ['air pollution', 'water pollution', 'soil pollution', 'noise', 'pollutants'],
        welcome: 'Pollution question? Ask about air, water, or soil.',
        allowed: ['pollution', 'air pollution', 'water pollution', 'soil pollution', 'noise pollution', 'smog', 'particulate', 'pm2.5', 'pm10', 'emission', 'contaminant', 'microplastic', 'runoff', 'eutrophication', 'acid rain', 'quality index', 'aqi'],
        related: ['environment', 'health', 'science'],
        synonyms: ['contamination', 'environmental pollution'],
        intents: ['understanding pollution', 'checking air quality', 'reducing pollution'],
        starters: ['What is PM2.5?', 'What causes acid rain?', 'How does water pollution happen?', 'How do I check air quality?'],
      },
      Ecology: {
        expertise: ['ecosystems', 'food webs', 'energy flow', 'succession', 'biomes'],
        welcome: 'Ecology question? Ask about ecosystems, food webs, or biomes.',
        allowed: ['ecology', 'ecosystem', 'food web', 'food chain', 'energy flow', 'succession', 'biome', 'tundra', 'rainforest', 'savanna', 'desert', 'decomposer', 'producer', 'consumer', 'carrying capacity', 'symbiosis'],
        related: ['environment', 'biology', 'science'],
        synonyms: ['ecosystem science'],
        intents: ['understanding ecosystems', 'learning food webs', 'studying biomes'],
        starters: ['What is an ecosystem?', 'How does energy flow through a food web?', 'What is ecological succession?', 'What are the major biomes?'],
      },
      'Green Living': {
        expertise: ['green lifestyle', 'eco products', 'energy saving', 'sustainable diet', 'transport'],
        welcome: 'Green living question? Ask about lifestyle changes or products.',
        allowed: ['green living', 'green', 'eco', 'eco-friendly', 'energy saving', 'efficient', 'led', 'reusable', 'sustainable diet', 'plant-based', 'public transport', 'bike', 'electric car', 'minimize', 'reduce', 'reuse', 'green products'],
        related: ['environment', 'home', 'lifestyle'],
        synonyms: ['eco-living', 'green lifestyle'],
        intents: ['going green at home', 'choosing eco products', 'reducing energy'],
        starters: ['How do I make my home more eco-friendly?', 'What are the easiest green swaps?', 'How do I save energy at home?', 'Is a plant-based diet better for the planet?'],
      },
    },
  },

  Geography: {
    themes: ['Forest', 'Ocean', 'Amber'],
    specialties: {
      'World Geography': {
        expertise: ['countries', 'continents', 'capitals', 'landforms', 'population'],
        welcome: 'World geography question? Ask about countries, capitals, or landforms.',
        allowed: ['geography', 'world', 'country', 'countries', 'continent', 'capital', 'map', 'mountain', 'river', 'desert', 'island', 'population', 'border', 'landmark', 'climate zone', 'equator', 'latitude', 'longitude'],
        related: ['geography', 'travel', 'history'],
        synonyms: ['geographical', 'world knowledge'],
        intents: ['learning about a country', 'memorizing capitals', 'understanding landforms'],
        starters: ['What is the largest country by area?', 'Name all the countries in Africa', 'What is the difference between latitude and longitude?', 'Where are the highest mountains?'],
      },
      Cartography: {
        expertise: ['maps', 'mapmaking', 'projections', 'gis', 'topography'],
        welcome: 'Cartography question? Ask about maps, projections, or GIS.',
        allowed: ['cartography', 'map', 'maps', 'mapmaking', 'projection', 'mercator', 'topographic', 'topography', 'gis', 'gps', 'coordinates', 'scale', 'legend', 'compass', 'contour', 'elevation', 'satellite'],
        related: ['geography', 'technology', 'data'],
        synonyms: ['mapmaking', 'mapping'],
        intents: ['making a map', 'understanding projections', 'using gis'],
        starters: ['What is the Mercator projection?', 'How do I read a topographic map?', 'What is GIS?', 'What are the different map projections?'],
      },
      Geopolitics: {
        expertise: ['geopolitics', 'borders', 'resources', 'power', 'conflicts'],
        welcome: 'Geopolitics question? Ask about borders, resources, or power.',
        allowed: ['geopolitics', 'geopolitical', 'borders', 'boundary', 'resource', 'oil', 'water', 'strategic', 'power', 'conflict', 'tension', 'alliance', 'nato', 'diplomacy', 'sanction', 'territory', 'region'],
        related: ['geography', 'politics', 'economics'],
        synonyms: ['international relations', 'geo-strategy'],
        intents: ['understanding conflicts', 'learning about resources', 'analyzing power'],
        starters: ['What is geopolitics?', 'Why is the Strait of Hormuz important?', 'How do resources shape conflicts?', 'What is a buffer state?'],
      },
      Demographics: {
        expertise: ['demographics', 'population', 'migration', 'urbanization', 'aging'],
        welcome: 'Demographics question? Ask about population, migration, or trends.',
        allowed: ['demographics', 'demographic', 'population', 'census', 'migration', 'immigration', 'emigration', 'urbanization', 'birth rate', 'death rate', 'life expectancy', 'aging', 'age structure', 'fertility', 'density', 'ethnicity'],
        related: ['geography', 'sociology', 'economics'],
        synonyms: ['population studies', 'population science'],
        intents: ['understanding population', 'learning about migration', 'analyzing trends'],
        starters: ['What is demographic transition?', 'How does urbanization affect society?', 'What is a population pyramid?', 'What drives migration?'],
      },
      'Urban Studies': {
        expertise: ['cities', 'urbanization', 'urban planning', 'housing', 'infrastructure'],
        welcome: 'Urban studies question? Ask about cities, planning, or housing.',
        allowed: ['urban', 'city', 'cities', 'urbanization', 'urban planning', 'housing', 'affordability', 'gentrification', 'transit', 'suburb', 'downtown', 'infrastructure', 'public space', 'urban design', 'slum', 'smart city'],
        related: ['geography', 'sociology', 'planning'],
        synonyms: ['urban geography', 'city studies'],
        intents: ['understanding cities', 'learning about gentrification', 'analyzing housing'],
        starters: ['What is gentrification?', 'How do cities grow?', 'What makes a city livable?', 'What is the urban heat island effect?'],
      },
      'Rural Development': {
        expertise: ['rural areas', 'development', 'agriculture', 'infrastructure', 'community'],
        welcome: 'Rural development question? Ask about communities, infrastructure, or projects.',
        allowed: ['rural', 'rural development', 'village', 'agriculture', 'farming', 'infrastructure', 'roads', 'electricity', 'water', 'healthcare', 'school', 'community', 'livelihood', 'microfinance', 'migration', 'cooperative'],
        related: ['geography', 'development', 'economics'],
        synonyms: ['village development', 'rural progress'],
        intents: ['understanding rural issues', 'planning projects', 'improving livelihoods'],
        starters: ['What is rural development?', 'How do rural communities access healthcare?', 'What is a farmer cooperative?', 'How does migration affect rural areas?'],
      },
      'Natural Disasters': {
        expertise: ['earthquakes', 'floods', 'hurricanes', 'wildfires', 'disaster response'],
        welcome: 'Natural disaster question? Ask about causes, preparedness, or response.',
        allowed: ['natural disaster', 'disaster', 'earthquake', 'flood', 'flooding', 'hurricane', 'typhoon', 'cyclone', 'wildfire', 'tsunami', 'tornado', 'volcano', 'drought', 'landslide', 'preparedness', 'evacuation', 'fema'],
        related: ['geography', 'environment', 'safety'],
        synonyms: ['hazards', 'catastrophes'],
        intents: ['understanding causes', 'preparing for disasters', 'learning response'],
        starters: ['How do hurricanes form?', 'What should I pack in an emergency kit?', 'How do floods happen?', 'How do I prepare for an earthquake?'],
      },
      'Rivers & Oceans': {
        expertise: ['rivers', 'oceans', 'currents', 'watersheds', 'water cycle'],
        welcome: 'Rivers and oceans question? Ask about waterways, currents, or cycles.',
        allowed: ['river', 'rivers', 'ocean', 'oceans', 'sea', 'current', 'tide', 'watershed', 'basin', 'delta', 'estuary', 'glacier', 'water cycle', 'evaporation', 'groundwater', 'freshwater', 'salinity'],
        related: ['geography', 'environment', 'science'],
        synonyms: ['hydrography', 'water bodies'],
        intents: ['learning about rivers', 'understanding currents', 'studying the water cycle'],
        starters: ['What is a watershed?', 'How do ocean currents move?', 'What is the water cycle?', 'How do rivers shape the land?'],
      },
      Mountains: {
        expertise: ['mountain ranges', 'peaks', 'geology', 'ecosystems', 'climbing'],
        welcome: 'Mountains question? Ask about ranges, peaks, or geology.',
        allowed: ['mountain', 'mountains', 'peak', 'range', 'himalaya', 'andes', 'alps', 'everest', 'summit', 'elevation', 'treeline', 'glacier', 'fault', 'uplift', 'plateau', 'valley', 'snow', 'avalanche', 'base camp'],
        related: ['geography', 'geology', 'adventure'],
        synonyms: ['alpine', 'highlands'],
        intents: ['learning about ranges', 'understanding formation', 'planning climbs'],
        starters: ['How are mountains formed?', 'What is the highest peak on each continent?', 'Why is it colder at higher elevations?', 'What lives above the treeline?'],
      },
      Deserts: {
        expertise: ['deserts', 'arid lands', 'adaptations', 'dunes', 'desertification'],
        welcome: 'Desert question? Ask about landscapes, life, or desertification.',
        allowed: ['desert', 'deserts', 'sahara', 'gobi', 'arid', 'dune', 'oasis', 'cactus', 'sandstorm', 'desertification', 'drought', 'adaptation', 'nomad', 'caravan', 'rain shadow', 'evaporation', 'dry'],
        related: ['geography', 'environment', 'biology'],
        synonyms: ['arid lands', 'wastelands'],
        intents: ['understanding deserts', 'learning adaptations', 'studying desertification'],
        starters: ['Why do deserts form?', 'How do animals survive in deserts?', 'What is desertification?', 'What is a rain shadow desert?'],
      },
    },
  },
};
