// ============================================================
// SCARLET DOMAIN KNOWLEDGE — PART 3
// Each specialty: expertise, welcome, allowed, related,
// synonyms, intents, starters (+ optional disclaimer).
// ============================================================

export const DOMAIN_PART3 = {
  Agriculture: {
    themes: ['Forest', 'Emerald', 'Amber'],
    specialties: {
      Farming: {
        expertise: ['crop farming', 'soil management', 'irrigation', 'harvesting', 'farm equipment'],
        welcome: 'Farming question? Ask about crops, soil, or equipment.',
        allowed: ['farming', 'farm', 'crop', 'crops', 'soil', 'tillage', 'irrigation', 'harvest', 'tractor', 'planter', 'fertilizer', 'pesticide', 'organic', 'rotation', 'yield', 'acre', 'field', 'greenhouse'],
        related: ['agriculture', 'food', 'environment'],
        synonyms: ['cultivation', 'growing'],
        intents: ['improving crop yield', 'managing soil', 'choosing equipment'],
        starters: ['How do I improve soil health?', 'What is crop rotation?', 'How do I choose the right irrigation system?', 'What is no-till farming?'],
      },
      'Organic Growing': {
        expertise: ['organic farming', 'natural pest control', 'composting', 'certification', 'soil health'],
        welcome: 'Organic growing question? Ask about natural methods and certification.',
        allowed: ['organic', 'organic farming', 'natural', 'pest control', 'compost', 'composting', 'manure', 'cover crop', 'green manure', 'certification', 'usda organic', 'non-gmo', 'heirloom', 'biodiversity', 'soil health'],
        related: ['agriculture', 'food', 'environment'],
        synonyms: ['biological farming'],
        intents: ['going organic', 'natural pest control', 'getting certified'],
        starters: ['How do I transition to organic farming?', 'What are natural pest control methods?', 'How do I get organic certification?', 'What is the difference between organic and conventional?'],
      },
      Livestock: {
        expertise: ['animal husbandry', 'cattle', 'poultry', 'sheep', 'health'],
        welcome: 'Livestock question? Ask about raising, feeding, or health.',
        allowed: ['livestock', 'cattle', 'cows', 'poultry', 'chickens', 'sheep', 'goats', 'pigs', 'feed', 'pasture', 'grazing', 'veterinary', 'vaccine', 'breeding', 'fencing', 'barn', 'hay'],
        related: ['agriculture', 'animals', 'food'],
        synonyms: ['animal husbandry', 'ranching'],
        intents: ['raising livestock', 'managing feed', 'maintaining health'],
        starters: ['How do I start raising chickens?', 'What is intensive grazing?', 'How do I keep livestock healthy?', 'What do I need to build a barn?'],
      },
      Hydroponics: {
        expertise: ['hydroponic systems', 'nutrient solutions', 'growing media', 'lighting', 'indoor growing'],
        welcome: 'Hydroponics question? Ask about systems, nutrients, or setup.',
        allowed: ['hydroponics', 'hydroponic', 'grow', 'nutrient', 'water', 'ph', 'ec', 'light', 'led', 'grow light', 'medium', 'rockwool', 'coco', 'perlite', 'deep water culture', 'dwc', 'ebb and flow', 'drip system', 'indoor'],
        related: ['agriculture', 'gardening', 'technology'],
        synonyms: ['soilless growing', 'indoor farming'],
        intents: ['setting up a system', 'mixing nutrients', 'choosing lighting'],
        starters: ['How do I start hydroponics?', 'What is the best hydroponic system for beginners?', 'How do I mix nutrients?', 'What grow light should I use?'],
      },
      'Soil Science': {
        expertise: ['soil types', 'ph', 'nutrients', 'analysis', 'amendment'],
        welcome: 'Soil science question? Ask about types, pH, or nutrients.',
        allowed: ['soil', 'soil science', 'ph', 'nutrient', 'nitrogen', 'phosphorus', 'potassium', 'organic matter', 'clay', 'sand', 'loam', 'silt', 'test', 'analysis', 'lime', 'compost', 'mulch', 'drainage'],
        related: ['agriculture', 'environment', 'gardening'],
        synonyms: ['edaphology', 'soil health'],
        intents: ['testing soil', 'adjusting ph', 'improving nutrients'],
        starters: ['How do I test my soil pH?', 'What is the ideal soil for vegetables?', 'How do I improve clay soil?', 'What is NPK?'],
      },
      'Crop Management': {
        expertise: ['planting', 'pest management', 'fertilization', 'disease control', 'harvest timing'],
        welcome: 'Crop management question? Ask about planting, pests, or diseases.',
        allowed: ['crop', 'crops', 'planting', 'pest', 'disease', 'fungicide', 'herbicide', 'weed', 'irrigation', 'fertigation', 'scouting', 'integrated pest', 'ipm', 'blight', 'rust', 'mold', 'harvest', 'storage'],
        related: ['agriculture', 'farming', 'science'],
        synonyms: ['agronomy', 'crop science'],
        intents: ['managing pests', 'fertilizing crops', 'timing harvest'],
        starters: ['What is integrated pest management?', 'How do I handle common crop diseases?', 'When should I harvest?', 'How do I store crops after harvest?'],
      },
      Irrigation: {
        expertise: ['irrigation systems', 'drip irrigation', 'sprinklers', 'water management', 'scheduling'],
        welcome: 'Irrigation question? Ask about systems, scheduling, or water.',
        allowed: ['irrigation', 'water', 'drip', 'sprinkler', 'soaker', 'pivot', 'flood', 'schedule', 'timing', 'evaporation', 'runoff', 'pressure', 'pump', 'filter', 'emitter', 'tube', 'wet zone', 'dry farming'],
        related: ['agriculture', 'gardening', 'water'],
        synonyms: ['watering', 'water management'],
        intents: ['choosing a system', 'scheduling irrigation', 'conserving water'],
        starters: ['Drip vs sprinkler — which is better?', 'How often should I irrigate?', 'How do I set up a drip system?', 'How do I reduce water waste?'],
      },
      Beekeeping: {
        expertise: ['hive management', 'honey', 'bee health', 'queen rearing', 'pollination'],
        welcome: 'Beekeeping question? Ask about hives, honey, or bee health.',
        allowed: ['beekeeping', 'bee', 'bees', 'hive', 'honey', 'wax', 'queen', 'worker', 'drone', 'nectar', 'pollen', 'smoker', 'frame', 'apiary', 'varroa', 'swarm', 'extractor', 'pollination'],
        related: ['agriculture', 'nature', 'food'],
        synonyms: ['apiculture', 'honey farming'],
        intents: ['starting a hive', 'managing bees', 'harvesting honey'],
        starters: ['How do I start beekeeping?', 'How do I manage varroa mites?', 'How do I harvest honey?', 'How do I prevent swarming?'],
      },
      Aquaculture: {
        expertise: ['fish farming', 'ponds', 'species', 'water quality', 'feeding'],
        welcome: 'Aquaculture question? Ask about fish farming, ponds, or species.',
        allowed: ['aquaculture', 'fish farming', 'fish', 'pond', 'tank', 'salmon', 'tilapia', 'shrimp', 'water quality', 'oxygen', 'feed', 'feeding', 'disease', 'harvest', 'recirculating', 'ras'],
        related: ['agriculture', 'environment', 'food'],
        synonyms: ['fish culture', 'aquafarming'],
        intents: ['starting a fish farm', 'managing water quality', 'choosing species'],
        starters: ['How do I start fish farming?', 'What fish species are best for farming?', 'How do I maintain water quality?', 'What is a recirculating aquaculture system?'],
      },
      Forestry: {
        expertise: ['forest management', 'tree planting', 'sustainable forestry', 'wildlife', 'conservation'],
        welcome: 'Forestry question? Ask about trees, management, or conservation.',
        allowed: ['forestry', 'forest', 'tree', 'trees', 'timber', 'logging', 'sustainable', 'planting', 'reforestation', 'silviculture', 'canopy', 'habitat', 'wildlife', 'conservation', 'carbon', 'woodland'],
        related: ['environment', 'nature', 'agriculture'],
        synonyms: ['silviculture', 'woodland management'],
        intents: ['managing a forest', 'planting trees', 'conserving wildlife'],
        starters: ['How do I manage a small forest?', 'What is sustainable forestry?', 'How do I plant trees for reforestation?', 'How does forestry affect climate?'],
      },
    },
  },

  Architecture: {
    themes: ['Slate', 'Mono', 'Royal'],
    specialties: {
      Residential: {
        expertise: ['house design', 'floor plans', 'materials', 'building codes', 'sustainable design'],
        welcome: 'Residential architecture question? Ask about design, plans, or materials.',
        allowed: ['architecture', 'residential', 'house', 'home', 'design', 'floor plan', 'blueprint', 'foundation', 'framing', 'roof', 'material', 'wood', 'steel', 'concrete', 'building code', 'permit', 'kitchen', 'bathroom', 'open floor'],
        related: ['design', 'construction', 'home'],
        synonyms: ['residential design', 'home architecture'],
        intents: ['designing a house', 'understanding plans', 'choosing materials'],
        starters: ['How do I design a house?', 'Open floor plan vs closed rooms?', 'What is passive solar design?', 'How do I read a floor plan?'],
      },
      Commercial: {
        expertise: ['commercial buildings', 'office design', 'retail', 'codes', 'accessibility'],
        welcome: 'Commercial architecture question? Ask about buildings, offices, or retail.',
        allowed: ['commercial', 'building', 'office', 'retail', 'mall', 'warehouse', 'structure', 'steel frame', 'curtain wall', 'hvac', 'fire', 'egress', 'ada', 'accessibility', 'zoning', 'storefront', 'parking'],
        related: ['architecture', 'construction', 'business'],
        synonyms: ['commercial design'],
        intents: ['designing an office', 'understanding codes', 'planning retail space'],
        starters: ['How do I design an office layout?', 'What are the key commercial building codes?', 'How do I make a building accessible?', 'What is a curtain wall?'],
      },
      Sustainable: {
        expertise: ['green building', 'energy efficiency', 'materials', 'leed', 'passive house'],
        welcome: 'Sustainable architecture question? Ask about green design or energy.',
        allowed: ['sustainable', 'green', 'green building', 'leed', 'passive house', 'energy efficient', 'solar', 'insulation', 'natural ventilation', 'thermal mass', 'reclaimed', 'recycled', 'low-voc', 'rainwater', 'net zero', 'biophilic'],
        related: ['architecture', 'environment', 'design'],
        synonyms: ['green architecture', 'eco-friendly design'],
        intents: ['designing sustainably', 'getting leed certified', 'saving energy'],
        starters: ['How do I design a passive house?', 'What is LEED certification?', 'What are sustainable building materials?', 'How do I make a building net-zero?'],
      },
      'Urban Planning': {
        expertise: ['city planning', 'zoning', 'transportation', 'public spaces', 'infrastructure'],
        welcome: 'Urban planning question? Ask about cities, zoning, or infrastructure.',
        allowed: ['urban planning', 'city', 'zoning', 'land use', 'transportation', 'transit', 'public space', 'park', 'walkability', 'mixed-use', 'density', 'infrastructure', 'utilities', 'master plan', 'community', 'street'],
        related: ['architecture', 'geography', 'government'],
        synonyms: ['city planning', 'town planning'],
        intents: ['planning a city', 'understanding zoning', 'improving public spaces'],
        starters: ['What is mixed-use development?', 'How do I improve walkability?', 'What is a master plan?', 'How do I plan public transit?'],
      },
      'Landscape Architecture': {
        expertise: ['landscape design', 'hardscape', 'planting', 'site planning', 'ecology'],
        welcome: 'Landscape architecture question? Ask about outdoor spaces or planting.',
        allowed: ['landscape architecture', 'landscape', 'hardscape', 'planting', 'site plan', 'grading', 'drainage', 'retaining wall', 'pathway', 'plaza', 'green roof', 'rain garden', 'native plants', 'ecology', 'outdoor room'],
        related: ['architecture', 'garden', 'environment'],
        synonyms: ['landscape design'],
        intents: ['designing an outdoor space', 'managing drainage', 'choosing plants'],
        starters: ['How do I design a landscape plan?', 'What is a rain garden?', 'How do I choose native plants?', 'What is the difference between a landscape architect and a gardener?'],
      },
      'Historic Preservation': {
        expertise: ['historic buildings', 'restoration', 'preservation', 'heritage', 'materials'],
        welcome: 'Historic preservation question? Ask about restoration or heritage.',
        allowed: ['historic preservation', 'historic', 'heritage', 'restoration', 'preservation', 'landmark', 'old building', 'facade', 'mortar', 'plaster', 'wood frame', 'adaptive reuse', 'museum', 'charter', 'secretary standards'],
        related: ['architecture', 'history', 'culture'],
        synonyms: ['heritage conservation'],
        intents: ['restoring a building', 'preserving a landmark', 'adaptive reuse'],
        starters: ['How do I restore a historic building?', 'What is adaptive reuse?', 'How do I match historic materials?', 'What are the standards for historic preservation?'],
      },
      'Structural Engineering': {
        expertise: ['structural systems', 'loads', 'foundations', 'steel', 'concrete'],
        welcome: 'Structural engineering question? Ask about loads, systems, or foundations.',
        allowed: ['structural', 'structure', 'load', 'foundation', 'beam', 'column', 'steel', 'concrete', 'reinforced', 'rebar', 'seismic', 'wind', 'truss', 'frame', 'lateral', 'shear', 'moment', 'deck'],
        related: ['architecture', 'engineering', 'construction'],
        synonyms: ['structural design'],
        intents: ['understanding loads', 'designing a structure', 'choosing a system'],
        starters: ['How do loads work in a building?', 'What is the difference between a beam and a column?', 'How do I design for earthquakes?', 'Steel vs concrete frame?'],
      },
      'Green Building': {
        expertise: ['energy modeling', 'materials', 'water efficiency', 'indoor air quality', 'certification'],
        welcome: 'Green building question? Ask about energy, materials, or certification.',
        allowed: ['green building', 'energy', 'efficiency', 'hvac', 'insulation', 'window', 'solar', 'daylight', 'water', 'low-flow', 'indoor air', 'material', 'recycled', 'bamboo', 'certification', 'leed', 'breeam', 'well'],
        related: ['architecture', 'environment', 'construction'],
        synonyms: ['green construction', 'eco-building'],
        intents: ['improving efficiency', 'choosing materials', 'getting certified'],
        starters: ['How do I make a building energy efficient?', 'What are the best green building materials?', 'What is a WELL certification?', 'How do I improve indoor air quality?'],
      },
      'Smart Cities': {
        expertise: ['smart cities', 'iot in cities', 'sensors', 'data', 'digital infrastructure'],
        welcome: 'Smart city question? Ask about technology in urban spaces.',
        allowed: ['smart city', 'smart cities', 'iot', 'sensor', 'data', 'traffic', 'lighting', 'grid', 'waste', 'water', 'digital', 'infrastructure', '5g', 'smart parking', 'urban tech', 'citizen', 'platform'],
        related: ['urban planning', 'technology', 'architecture'],
        synonyms: ['digital city', 'urban tech'],
        intents: ['understanding smart cities', 'planning digital infrastructure', 'using iot for cities'],
        starters: ['What is a smart city?', 'How do IoT sensors help cities?', 'What is smart mobility?', 'How do smart grids work?'],
      },
    },
  },

  Aviation: {
    themes: ['Space', 'Midnight', 'Ocean'],
    specialties: {
      'Commercial Flying': {
        expertise: ['commercial aviation', 'airlines', 'flight operations', 'safety', 'pilot basics'],
        welcome: 'Commercial aviation question? Ask about flying, airlines, or safety.',
        allowed: ['aviation', 'commercial', 'airline', 'airlines', 'flight', 'pilot', 'captain', 'cockpit', 'takeoff', 'landing', 'cruise', 'turbulence', 'safety', 'checklist', 'autopilot', 'aircraft', 'airbus', 'boeing', '737', 'a320'],
        related: ['travel', 'transport', 'engineering'],
        synonyms: ['air travel', 'airline flying'],
        intents: ['understanding flight', 'becoming a pilot', 'learning about aircraft'],
        starters: ['How do airplanes fly?', 'What does a pilot do during a flight?', 'How safe is commercial aviation?', 'What is the difference between Airbus and Boeing?'],
      },
      'Private Pilots': {
        expertise: ['private pilot license', 'flying', 'navigation', 'airspace', 'training'],
        welcome: 'Private pilot question? Ask about training, licenses, or flying.',
        allowed: ['private pilot', 'pilot', 'license', 'ppl', 'flying', 'navigation', 'vfr', 'ifr', 'airspace', 'airport', 'control tower', 'weather', 'cross-country', 'solo', 'checkride', 'instructor', 'certification'],
        related: ['aviation', 'travel', 'training'],
        synonyms: ['general aviation', 'flying club'],
        intents: ['getting a license', 'learning navigation', 'understanding airspace'],
        starters: ['How do I get a private pilot license?', 'What is VFR vs IFR?', 'How do I read a sectional chart?', 'How much does it cost to become a pilot?'],
      },
      Drones: {
        expertise: ['drones', 'quadcopters', 'flying', 'photography', 'regulations'],
        welcome: 'Drone question? Ask about flying, photography, or rules.',
        allowed: ['drone', 'drones', 'uav', 'quadcopter', 'fpv', 'gopro', 'aerial photography', 'fly', 'controller', 'battery', 'gps', 'return to home', 'autonomous', 'camera', 'gimbal', 'propeller', 'motor', 'esc', 'flight controller', 'regulations', 'faa'],
        related: ['aviation', 'photography', 'technology'],
        synonyms: ['uas', 'unmanned aircraft'],
        intents: ['choosing a drone', 'learning to fly', 'understanding regulations'],
        starters: ['Which drone should a beginner buy?', 'How do I fly a drone?', 'What are drone regulations?', 'How do I get smooth aerial footage?'],
      },
      Aerospace: {
        expertise: ['aerospace engineering', 'aircraft design', 'propulsion', 'materials', 'aerodynamics'],
        welcome: 'Aerospace question? Ask about design, propulsion, or materials.',
        allowed: ['aerospace', 'aerospace engineering', 'aircraft', 'wing', 'fuselage', 'engine', 'turbine', 'jet', 'propeller', 'thrust', 'drag', 'lift', 'aerodynamics', 'composite', 'aluminum', 'wind tunnel', 'cfd', 'spacecraft'],
        related: ['engineering', 'aviation', 'space'],
        synonyms: ['aeronautical engineering'],
        intents: ['understanding aerodynamics', 'learning propulsion', 'designing aircraft'],
        starters: ['How does a jet engine work?', 'What is the difference between a turbofan and a turbojet?', 'How do wings generate lift?', 'What materials are used in aircraft?'],
      },
      'Air Traffic': {
        expertise: ['air traffic control', 'atc', 'radar', 'communications', 'procedures'],
        welcome: 'ATC question? Ask about controlling traffic, radar, or communications.',
        allowed: ['air traffic control', 'atc', 'controller', 'radar', 'transponder', 'squawk', 'clearance', 'approach', 'departure', 'tower', 'ground', 'handoff', 'separation', 'vector', 'holding', 'ils', 'communication', 'frequency'],
        related: ['aviation', 'transport', 'safety'],
        synonyms: ['air traffic management'],
        intents: ['becoming an atc', 'understanding atc', 'learning procedures'],
        starters: ['How do I become an air traffic controller?', 'How does ATC separate planes?', 'What is an ILS?', 'What do different squawk codes mean?'],
      },
      'Aircraft Maintenance': {
        expertise: ['maintenance', 'inspection', 'repair', 'systems', 'certification'],
        welcome: 'Aircraft maintenance question? Ask about repairs, inspections, or systems.',
        allowed: ['aircraft maintenance', 'maintenance', 'inspection', 'repair', 'a&p', 'mechanic', 'engine', 'hydraulic', 'electrical', 'avionics', 'landing gear', 'brake', 'tire', 'logbook', 'airworthiness', 'annual', 'system'],
        related: ['aviation', 'engineering', 'safety'],
        synonyms: ['a&p mechanics', 'aircraft repair'],
        intents: ['becoming a mechanic', 'performing inspections', 'troubleshooting'],
        starters: ['How do I become an aircraft mechanic?', 'What is an annual inspection?', 'How do I troubleshoot an engine issue?', 'What are the most common aircraft systems?'],
      },
      'Flight Training': {
        expertise: ['training programs', 'simulators', 'checkrides', 'ratings', 'instructor'],
        welcome: 'Flight training question? Ask about programs, ratings, or simulators.',
        allowed: ['flight training', 'training', 'simulator', 'sim', 'checkride', 'rating', 'instrument', 'commercial', 'multi-engine', 'instructor', 'cfi', 'ground school', 'written exam', 'medical', 'logbook', 'hours'],
        related: ['aviation', 'education', 'training'],
        synonyms: ['pilot training', 'flight school'],
        intents: ['choosing a flight school', 'getting a rating', 'preparing for checkride'],
        starters: ['How do I choose a flight school?', 'What is the difference between PPL and CPL?', 'How do I prepare for a checkride?', 'What is a multi-engine rating?'],
      },
      'Aviation History': {
        expertise: ['aviation history', 'pioneers', 'aircraft', 'wars', 'milestones'],
        welcome: 'Aviation history question? Ask about pioneers, aircraft, or milestones.',
        allowed: ['aviation history', 'history', 'wright brothers', 'amelia earhart', 'concorde', 'spitfire', 'wwii', 'jet age', 'supersonic', 'space race', 'apollo', 'moon landing', 'nasa', 'first flight', 'air races', 'barnstorming'],
        related: ['aviation', 'history', 'transport'],
        synonyms: ['air history', 'flight history'],
        intents: ['learning about pioneers', 'understanding milestones', 'studying aircraft'],
        starters: ['How did the Wright brothers fly?', 'What happened to Amelia Earhart?', 'How did the jet age change aviation?', 'What was the Concorde?'],
      },
      'Space Travel': {
        expertise: ['space travel', 'spacecraft', 'rockets', 'astronauts', 'future missions'],
        welcome: 'Space travel question? Ask about spacecraft, missions, or the future.',
        allowed: ['space travel', 'spacecraft', 'capsule', 'rocket', 'launch', 'orbit', 'astronaut', 'space suit', 'space station', 'iss', 'moon', 'mars', 'spacex', 'starship', 'artemis', 'lunar', 'zero gravity', 'life support'],
        related: ['aviation', 'space', 'astronomy'],
        synonyms: ['spaceflight', 'human spaceflight'],
        intents: ['learning about spacecraft', 'understanding missions', 'following space tourism'],
        starters: ['How does a spacecraft launch?', 'What is life like on the ISS?', 'When will humans go to Mars?', 'How does space tourism work?'],
      },
      Helicopters: {
        expertise: ['helicopters', 'rotary wing', 'flight', 'controls', 'training'],
        welcome: 'Helicopter question? Ask about flying, controls, or types.',
        allowed: ['helicopter', 'helicopters', 'rotary', 'rotor', 'blade', 'tail rotor', 'swashplate', 'cyclic', 'collective', 'hove', 'autorotation', 'training', 'license', 'pilot', 'bell', 'airbus', 'robinson', 'r22'],
        related: ['aviation', 'training', 'transport'],
        synonyms: ['chopper', 'rotary wing'],
        intents: ['learning to fly helicopters', 'understanding controls', 'buying a helicopter'],
        starters: ['How do helicopters fly?', 'Is flying a helicopter harder than a plane?', 'How do I get a helicopter license?', 'What is autorotation?'],
      },
    },
  },

  'Beauty & Skincare': {
    themes: ['Sunset', 'Grape', 'Mono'],
    specialties: {
      'Skincare Routine': {
        expertise: ['cleansing', 'moisturizing', 'serums', 'sunscreen', 'routine building'],
        welcome: 'Skincare question? Ask about routines, products, or ingredients.',
        allowed: ['skincare', 'skin care', 'skin', 'routine', 'cleanser', 'moisturizer', 'serum', 'sunscreen', 'spf', 'retinol', 'vitamin c', 'hyaluronic', 'niacinamide', 'exfoliate', 'toner', 'eye cream', 'face wash', 'acne', 'dry skin', 'oily skin'],
        related: ['beauty', 'health', 'cosmetics'],
        synonyms: ['facial care', 'derma'],
        intents: ['building a routine', 'choosing products', 'treating skin issues'],
        starters: ['How do I build a basic skincare routine?', 'What is the difference between a serum and a moisturizer?', 'How do I know my skin type?', 'Do I need to wear sunscreen every day?'],
      },
      Makeup: {
        expertise: ['makeup application', 'products', 'techniques', 'looks', 'tools'],
        welcome: 'Makeup question? Ask about application, products, or techniques.',
        allowed: ['makeup', 'make-up', 'foundation', 'concealer', 'blush', 'bronzer', 'eyeshadow', 'eyeliner', 'mascara', 'lipstick', 'lip liner', 'brush', 'sponge', 'blending', 'contour', 'highlight', 'primer', 'setting spray', 'brow', 'lash'],
        related: ['beauty', 'fashion', 'cosmetics'],
        synonyms: ['cosmetics', 'face makeup'],
        intents: ['learning techniques', 'choosing products', 'creating looks'],
        starters: ['How do I find my foundation shade?', 'How do I contour for beginners?', 'What brushes do I need?', 'How do I make my makeup last longer?'],
      },
      'Hair Care': {
        expertise: ['hair types', 'shampoo', 'conditioning', 'styling', 'treatments'],
        welcome: 'Hair care question? Ask about routines, products, or styling.',
        allowed: ['hair care', 'hair', 'shampoo', 'conditioner', 'mask', 'oil', 'serum', 'curly', 'straight', 'frizz', 'damage', 'split ends', 'dye', 'bleach', 'heat protect', 'blow dry', 'straightener', 'curling iron', 'scalp', 'dandruff'],
        related: ['beauty', 'health', 'fashion'],
        synonyms: ['tresses', 'hair health'],
        intents: ['building a hair routine', 'treating damage', 'choosing products'],
        starters: ['How do I build a hair care routine?', 'How often should I wash my hair?', 'How do I treat damaged hair?', 'What is the curly girl method?'],
      },
      'Nail Art': {
        expertise: ['nail shapes', 'polish', 'techniques', 'designs', 'care'],
        welcome: 'Nail art question? Ask about designs, techniques, or care.',
        allowed: ['nail art', 'nails', 'nail', 'polish', 'gel', 'acrylic', 'dip', 'manicure', 'pedicure', 'cuticle', 'buffer', 'file', 'shape', 'art', 'stamping', 'marbling', 'glitter', 'top coat', 'base coat', 'design'],
        related: ['beauty', 'fashion', 'art'],
        synonyms: ['manicure', 'nail design'],
        intents: ['learning a technique', 'creating designs', 'caring for nails'],
        starters: ['How do I do a basic manicure?', 'Gel vs acrylic nails?', 'How do I create nail art designs?', 'How do I make my nail polish last?'],
      },
      Fragrance: {
        expertise: ['fragrance families', 'notes', 'perfume', 'cologne', 'wearing'],
        welcome: 'Fragrance question? Ask about notes, families, or choosing a scent.',
        allowed: ['fragrance', 'perfume', 'cologne', 'scent', 'note', 'top note', 'heart', 'base', 'floral', 'woody', 'citrus', 'oriental', 'eau de parfum', 'eau de toilette', 'edp', 'edt', 'sillage', 'longevity', 'niche', 'designer'],
        related: ['beauty', 'fashion', 'lifestyle'],
        synonyms: ['perfume', 'scent'],
        intents: ['choosing a fragrance', 'understanding notes', 'learning about types'],
        starters: ['How do I choose a signature scent?', 'What is the difference between EDP and EDT?', 'What are fragrance families?', 'How do I make perfume last longer?'],
      },
      'Anti-aging': {
        expertise: ['aging', 'wrinkles', 'prevention', 'retinol', 'treatments'],
        welcome: 'Anti-aging question? Ask about prevention, products, or treatments.',
        allowed: ['anti-aging', 'aging', 'wrinkle', 'fine lines', 'retinol', 'vitamin c', 'peptide', 'collagen', 'sun damage', 'spf', 'antioxidant', 'botox', 'filler', 'laser', 'microneedling', 'prevention', 'firmness'],
        related: ['skincare', 'beauty', 'health'],
        synonyms: ['youth preservation', 'age prevention'],
        intents: ['preventing aging', 'choosing products', 'understanding treatments'],
        starters: ['When should I start anti-aging skincare?', 'Does retinol really work?', 'What is the difference between Botox and fillers?', 'How do I prevent wrinkles?'],
      },
      'Natural Beauty': {
        expertise: ['natural products', 'diy beauty', 'ingredients', 'clean beauty', 'sustainable'],
        welcome: 'Natural beauty question? Ask about clean products or DIY recipes.',
        allowed: ['natural beauty', 'natural', 'clean beauty', 'diy', 'homemade', 'ingredient', 'essential oil', 'coconut oil', 'aloe', 'shea butter', 'green tea', 'organic', 'vegan', 'cruelty-free', 'non-toxic', 'fragrance-free', 'minimalist'],
        related: ['beauty', 'health', 'environment'],
        synonyms: ['clean beauty', 'green beauty'],
        intents: ['choosing natural products', 'making diy recipes', 'understanding ingredients'],
        starters: ['What does "clean beauty" mean?', 'How do I make a DIY face mask?', 'What ingredients should I avoid?', 'Are natural products better for sensitive skin?'],
      },
      "Men's Grooming": {
        expertise: ['beard', 'shaving', 'grooming', 'products', 'routine'],
        welcome: "Men's grooming question? Ask about beards, shaving, or skincare.",
        allowed: ['men grooming', 'beard', 'shaving', 'razor', 'trimmer', 'aftershave', 'moisturizer', 'pre-shave', 'shaving cream', 'brush', 'straight razor', 'beard oil', 'beard balm', 'grooming routine', 'haircut', 'pomade', 'clay', 'wax'],
        related: ['beauty', 'fashion', 'lifestyle'],
        synonyms: ['male grooming', 'dapper'],
        intents: ['improving shaving', 'growing a beard', 'building a routine'],
        starters: ['How do I get a perfect shave?', 'How do I grow and maintain a beard?', 'What is a basic grooming routine for men?', 'Beard oil vs balm?'],
      },
      'Spa Treatments': {
        expertise: ['spa', 'massage', 'facial', 'body treatment', 'wellness'],
        welcome: 'Spa treatment question? Ask about massages, facials, or packages.',
        allowed: ['spa', 'massage', 'swedish', 'deep tissue', 'facial', 'body scrub', 'wrap', 'steam', 'sauna', 'hot stone', 'aromatherapy', 'essential oil', 'treatment', 'package', 'gift certificate', 'couple', 'detox', 'relaxation'],
        related: ['beauty', 'wellness', 'health'],
        synonyms: ['wellness spa', 'day spa'],
        intents: ['choosing a treatment', 'understanding massage', 'planning a spa day'],
        starters: ['What is the difference between Swedish and deep tissue massage?', 'What are the best spa treatments for relaxation?', 'How often should I get a facial?', 'What is a hot stone massage?'],
      },
      'Cosmetic Science': {
        expertise: ['cosmetic chemistry', 'ingredients', 'formulation', 'safety', 'regulation'],
        welcome: 'Cosmetic science question? Ask about ingredients, formulation, or safety.',
        allowed: ['cosmetic science', 'cosmetic', 'ingredient', 'formulation', 'chemistry', 'emulsion', 'surfactant', 'preservative', 'ph', 'stability', 'safety', 'regulation', 'fda', 'label', 'claim', 'hypoallergenic', 'non-comedogenic'],
        related: ['science', 'beauty', 'chemistry'],
        synonyms: ['cosmetic chemistry', 'formulation science'],
        intents: ['understanding ingredients', 'formulating products', 'learning safety'],
        starters: ['How are cosmetics formulated?', 'What are common preservatives in cosmetics?', 'What does "non-comedogenic" mean?', 'How are cosmetics regulated?'],
      },
    },
  },

  Construction: {
    themes: ['Slate', 'Amber', 'Mono'],
    specialties: {
      'Residential Building': {
        expertise: ['house construction', 'foundation', 'framing', 'roofing', 'finishes'],
        welcome: 'Residential construction question? Ask about building or renovating.',
        allowed: ['construction', 'residential', 'house', 'building', 'foundation', 'slab', 'framing', 'roof', 'truss', 'siding', 'drywall', 'insulation', 'floor', 'tile', 'paint', 'cabinets', 'countertop', 'renovation', 'new build'],
        related: ['construction', 'architecture', 'home'],
        synonyms: ['home building', 'house construction'],
        intents: ['building a house', 'understanding construction phases', 'choosing materials'],
        starters: ['What are the phases of building a house?', 'How do I choose a foundation type?', 'What is the difference between stick framing and truss?', 'How do I insulate a new home?'],
      },
      'Commercial Construction': {
        expertise: ['commercial projects', 'steel', 'concrete', 'project management', 'safety'],
        welcome: 'Commercial construction question? Ask about structures, steel, or concrete.',
        allowed: ['commercial', 'steel', 'concrete', 'structure', 'rebar', 'pour', 'formwork', 'crane', 'scaffold', 'safety', 'osha', 'project', 'budget', 'schedule', 'general contractor', 'subcontractor', 'blueprint', 'change order'],
        related: ['construction', 'architecture', 'business'],
        synonyms: ['contracting', 'building construction'],
        intents: ['managing a project', 'understanding concrete', 'ensuring safety'],
        starters: ['How do I manage a construction project?', 'What is the difference between rebar and mesh?', 'How do I ensure safety on a construction site?', 'What is a change order?'],
      },
      Renovation: {
        expertise: ['remodeling', 'kitchen', 'bathroom', 'basement', 'permit'],
        welcome: 'Renovation question? Ask about remodeling, permits, or budgeting.',
        allowed: ['renovation', 'remodel', 'remodeling', 'kitchen', 'bathroom', 'basement', 'attic', 'addition', 'permit', 'budget', 'contractor', 'quote', 'timeline', 'demo', 'rehab', 'refinish', 'update'],
        related: ['construction', 'home', 'design'],
        synonyms: ['remodeling', 'home improvement'],
        intents: ['planning a renovation', 'budgeting', 'hiring a contractor'],
        starters: ['How do I plan a kitchen renovation?', 'How much does a bathroom remodel cost?', 'Do I need a permit for renovation?', 'How do I choose a contractor?'],
      },
      Plumbing: {
        expertise: ['plumbing systems', 'pipes', 'fixtures', 'drainage', 'repairs'],
        welcome: 'Plumbing question? Ask about pipes, fixtures, or repairs.',
        allowed: ['plumbing', 'plumber', 'pipe', 'pvc', 'copper', 'pex', 'drain', 'sewer', 'vent', 'faucet', 'sink', 'toilet', 'shower', 'water heater', 'pressure', 'valve', 'shutoff', 'trap', 'snake', 'leak', 'solder'],
        related: ['construction', 'home', 'repair'],
        synonyms: ['pipework', 'sanitary'],
        intents: ['fixing a leak', 'installing fixtures', 'understanding systems'],
        starters: ['How do I fix a leaking faucet?', 'How do I unclog a drain?', 'PVC vs copper vs PEX?', 'How does a water heater work?'],
      },
      Electrical: {
        expertise: ['electrical systems', 'wiring', 'circuits', 'outlets', 'safety'],
        welcome: 'Electrical question? Ask about wiring, circuits, or safety.',
        allowed: ['electrical', 'electrician', 'wire', 'wiring', 'circuit', 'breaker', 'panel', 'outlet', 'switch', 'light', 'fixture', 'voltage', 'amp', 'load', 'ground', 'conduit', 'cable', 'romex', 'dimmer', 'gfci', 'safety'],
        related: ['construction', 'home', 'technology'],
        synonyms: ['electrical work', 'wiring'],
        intents: ['wiring a room', 'fixing an outlet', 'understanding circuits'],
        starters: ['How do I wire a light switch?', 'What is a GFCI outlet?', 'How do I fix a tripped breaker?', 'What is the difference between 14-gauge and 12-gauge wire?'],
      },
      HVAC: {
        expertise: ['hvac systems', 'heating', 'cooling', 'ventilation', 'maintenance'],
        welcome: 'HVAC question? Ask about heating, cooling, or ventilation.',
        allowed: ['hvac', 'heating', 'cooling', 'ac', 'air conditioner', 'furnace', 'heat pump', 'thermostat', 'duct', 'vent', 'filter', 'seer', 'btu', 'zone', 'mini-split', 'central', 'efficiency', 'maintenance', 'repair'],
        related: ['construction', 'home', 'energy'],
        synonyms: ['climate control', 'mechanical'],
        intents: ['choosing a system', 'maintaining hvac', 'troubleshooting'],
        starters: ['How do I choose an HVAC system?', 'How often should I change the filter?', 'What is the difference between a heat pump and a furnace?', 'What is a mini-split system?'],
      },
      Masonry: {
        expertise: ['brick', 'block', 'stone', 'mortar', 'masonry structures'],
        welcome: 'Masonry question? Ask about brick, stone, or mortar.',
        allowed: ['masonry', 'brick', 'bricks', 'block', 'concrete block', 'stone', 'mortar', 'grout', 'trowel', 'joint', 'course', 'bond', 'wall', 'foundation', 'patio', 'retaining', 'parging', 'seal', 'cleaning'],
        related: ['construction', 'architecture', 'materials'],
        synonyms: ['bricklaying', 'stonemasonry'],
        intents: ['laying brick', 'repairing masonry', 'choosing materials'],
        starters: ['How do I lay brick?', 'What is the difference between mortar and grout?', 'How do I repair a brick wall?', 'What is a retaining wall?'],
      },
      Roofing: {
        expertise: ['roof types', 'shingles', 'metal', 'repair', 'installation'],
        welcome: 'Roofing question? Ask about types, materials, or repairs.',
        allowed: ['roofing', 'roof', 'shingle', 'asphalt', 'metal', 'tile', 'slate', 'flat roof', 'pitched', 'truss', 'underlayment', 'flashing', 'gutter', 'downspout', 'ice dam', 'leak', 'ridge vent', 'skylight'],
        related: ['construction', 'home', 'weather'],
        synonyms: ['roof work', 'roof installation'],
        intents: ['choosing a roof', 'repairing a leak', 'understanding materials'],
        starters: ['How do I choose a roofing material?', 'How do I fix a roof leak?', 'Asphalt vs metal roof?', 'How long does a roof last?'],
      },
      Concrete: {
        expertise: ['concrete mixing', 'pouring', 'finishing', 'curing', 'repair'],
        welcome: 'Concrete question? Ask about mixing, pouring, or finishing.',
        allowed: ['concrete', 'cement', 'mix', 'pour', 'slab', 'foundation', 'driveway', 'sidewalk', 'finish', 'trowel', 'broom', 'cure', 'curing', 'expansion joint', 'crack', 'repair', 'rebar', 'fiber', 'stamp', 'stain'],
        related: ['construction', 'masonry', 'materials'],
        synonyms: ['cement work', 'concrete work'],
        intents: ['pouring a slab', 'finishing concrete', 'repairing cracks'],
        starters: ['How do I pour a concrete slab?', 'How long does concrete take to cure?', 'How do I finish concrete?', 'How do I repair a crack in concrete?'],
      },
      Safety: {
        expertise: ['safety', 'ppe', 'osha', 'fall protection', 'hazards'],
        welcome: 'Construction safety question? Ask about ppe, osha, or hazards.',
        allowed: ['safety', 'construction safety', 'ppe', 'hard hat', 'vest', 'gloves', 'harness', 'ladder', 'scaffold', 'osha', 'training', 'hazard', 'fall protection', 'fire', 'lockout', 'confined space', 'excavation', 'shoring'],
        related: ['construction', 'industrial', 'health'],
        synonyms: ['site safety', 'occupational safety'],
        intents: ['understanding osha', 'using ppe', 'preventing falls'],
        starters: ['What are the most common construction hazards?', 'What PPE do I need on a job site?', 'How do I set up fall protection?', 'What is an OSHA inspection?'],
      },
    },
  },

  Design: {
    themes: ['Grape', 'Sunset', 'Mono'],
    specialties: {
      'Graphic Design': {
        expertise: ['graphic design', 'layout', 'typography', 'color', 'software'],
        welcome: 'Graphic design question? Ask about layout, typography, or tools.',
        allowed: ['graphic design', 'design', 'layout', 'poster', 'logo', 'typography', 'typeface', 'font', 'color', 'palette', 'composition', 'hierarchy', 'illustrator', 'photoshop', 'figma', 'indesign', 'grid', 'mockup', 'brand', 'identity'],
        related: ['design', 'art', 'marketing'],
        synonyms: ['visual design', 'graphics'],
        intents: ['designing a poster', 'choosing fonts', 'using color'],
        starters: ['How do I choose a color palette?', 'What is the difference between a font and a typeface?', 'How do I create a logo?', 'What is visual hierarchy?'],
      },
      'UI/UX': {
        expertise: ['ui design', 'ux design', 'prototyping', 'user research', 'accessibility'],
        welcome: 'UI/UX question? Ask about interfaces, prototyping, or usability.',
        allowed: ['ui design', 'ux design', 'ui/ux', 'user interface', 'user experience', 'prototype', 'wireframe', 'figma', 'sketch', 'user flow', 'persona', 'usability', 'heuristic', 'a/b testing', 'accessibility', 'wcag', 'responsive', 'design system'],
        related: ['design', 'technology', 'product'],
        synonyms: ['interface design', 'user experience'],
        intents: ['designing an interface', 'conducting research', 'building a design system'],
        starters: ['What is the difference between UI and UX?', 'How do I create a user persona?', 'What is a design system?', 'How do I run a usability test?'],
      },
      'Product Design': {
        expertise: ['industrial design', 'product development', 'CAD', 'materials', 'prototyping'],
        welcome: 'Product design question? Ask about development, CAD, or prototyping.',
        allowed: ['product design', 'industrial design', 'product', 'design', 'cad', 'solidworks', 'fusion', '3d modeling', 'prototype', '3d print', 'material', 'plastic', 'metal', 'injection', 'mold', 'sketch', 'concept', 'ergonomics', 'manufacturing'],
        related: ['design', 'engineering', 'manufacturing'],
        synonyms: ['industrial design', 'product development'],
        intents: ['designing a product', 'learning cad', 'prototyping'],
        starters: ['How do I design a physical product?', 'What is the best CAD software for beginners?', 'How do I prototype a product?', 'What is injection molding?'],
      },
      'Brand Design': {
        expertise: ['brand identity', 'logo', 'visual system', 'guidelines', 'positioning'],
        welcome: 'Brand design question? Ask about identity, logo, or guidelines.',
        allowed: ['brand', 'branding', 'brand identity', 'logo', 'visual identity', 'guidelines', 'brand book', 'style guide', 'positioning', 'personality', 'tone', 'icon', 'pattern', 'color palette', 'typography', 'mood board'],
        related: ['design', 'marketing', 'business'],
        synonyms: ['identity design', 'branding'],
        intents: ['building a brand', 'designing a logo', 'creating guidelines'],
        starters: ['How do I build a brand identity?', 'What makes a good logo?', 'What goes in a brand style guide?', 'How do I choose brand colors?'],
      },
      Typography: {
        expertise: ['typefaces', 'font pairing', 'kerning', 'readability', 'history'],
        welcome: 'Typography question? Ask about typefaces, pairing, or arrangement.',
        allowed: ['typography', 'type', 'typeface', 'font', 'serif', 'sans-serif', 'kerning', 'tracking', 'leading', 'hierarchy', 'pairing', 'readability', 'size', 'weight', 'italic', 'grid', 'baseline', 'opentype', 'variable font'],
        related: ['design', 'graphic design', 'communication'],
        synonyms: ['type design', 'lettering'],
        intents: ['pairing fonts', 'improving readability', 'understanding typefaces'],
        starters: ['How do I pair fonts?', 'What is the difference between serif and sans-serif?', 'What is kerning?', 'How do I improve typography in my design?'],
      },
      'Color Theory': {
        expertise: ['color wheel', 'harmony', 'psychology', 'contrast', 'palette'],
        welcome: 'Color theory question? Ask about harmony, psychology, or palettes.',
        allowed: ['color theory', 'color', 'colour', 'wheel', 'harmony', 'complementary', 'analogous', 'triadic', 'monochromatic', 'psychology', 'warm', 'cool', 'saturation', 'brightness', 'contrast', 'accessible', 'colorblind', 'palette'],
        related: ['design', 'art', 'psychology'],
        synonyms: ['colour science', 'chromatics'],
        intents: ['building a palette', 'understanding harmony', 'choosing colors'],
        starters: ['What is the color wheel?', 'How do I create a color palette?', 'What are complementary colors?', 'How do I choose accessible colors?'],
      },
      'Motion Graphics': {
        expertise: ['animation', 'motion', 'after effects', 'keyframes', 'easing'],
        welcome: 'Motion graphics question? Ask about animation, after effects, or timing.',
        allowed: ['motion graphics', 'motion', 'animation', 'after effects', 'keyframe', 'easing', 'timing', 'composition', 'render', 'premiere', 'lottie', '2d', '3d', 'character', 'animate', 'title sequence', 'transition', 'morph'],
        related: ['design', 'video', 'technology'],
        synonyms: ['motion design', 'animation'],
        intents: ['learning motion graphics', 'creating animations', 'using after effects'],
        starters: ['How do I start learning motion graphics?', 'What is easing in animation?', 'How do I create a title sequence?', 'After Effects vs Premiere for motion?'],
      },
      'Print Design': {
        expertise: ['print', 'layout', 'prepress', 'paper', 'binding'],
        welcome: 'Print design question? Ask about layout, prepress, or printing.',
        allowed: ['print design', 'print', 'layout', 'prepress', 'bleed', 'crop mark', 'cmyk', 'spot color', 'paper', 'stock', 'coated', 'uncoated', 'binding', 'saddle stitch', 'perfect bound', 'fold', 'die cut', 'offset', 'digital print'],
        related: ['design', 'graphic design', 'manufacturing'],
        synonyms: ['printed matter', 'publication design'],
        intents: ['preparing for print', 'choosing paper', 'understanding press'],
        starters: ['What is the difference between CMYK and RGB?', 'What is bleed in print?', 'How do I choose paper stock?', 'What is the difference between offset and digital printing?'],
      },
      Packaging: {
        expertise: ['package design', 'structural', 'materials', 'labels', 'sustainability'],
        welcome: 'Packaging design question? Ask about structure, materials, or printing.',
        allowed: ['packaging', 'package design', 'box', 'bottle', 'bag', 'label', 'carton', 'plastic', 'cardboard', 'sustainable', 'die line', 'structural', 'folding', 'glue', 'shrink', 'varnish', 'foil', 'emboss', 'barcode'],
        related: ['design', 'manufacturing', 'brand'],
        synonyms: ['pack design', 'product packaging'],
        intents: ['designing packaging', 'choosing materials', 'understanding printing'],
        starters: ['How do I design product packaging?', 'What are sustainable packaging options?', 'What is a die line?', 'How do I choose packaging materials?'],
      },
      'Design Thinking': {
        expertise: ['design thinking', 'ideation', 'prototyping', 'user-centered', 'innovation'],
        welcome: 'Design thinking question? Ask about process, ideation, or prototyping.',
        allowed: ['design thinking', 'ideation', 'brainstorm', 'prototype', 'user-centered', 'empathy', 'define', 'ideate', 'test', 'iterate', 'innovation', 'human-centered', 'workshop', 'thinking', 'problem solving', 'creative'],
        related: ['design', 'business', 'innovation'],
        synonyms: ['human-centered design', 'creative problem solving'],
        intents: ['learning the process', 'running a workshop', 'applying human-centered design'],
        starters: ['What are the 5 stages of design thinking?', 'How do I run a design thinking workshop?', 'What is the difference between design thinking and agile?', 'How do I prototype ideas?'],
      },
    },
  },

  Economics: {
    themes: ['Royal', 'Slate', 'Mono'],
    specialties: {
      Microeconomics: {
        expertise: ['supply and demand', 'markets', 'pricing', 'utility', 'elasticity'],
        welcome: 'Microeconomics question? Ask about supply, demand, or markets.',
        allowed: ['microeconomics', 'supply', 'demand', 'market', 'price', 'elasticity', 'utility', 'marginal', 'consumer', 'producer', 'surplus', 'competition', 'monopoly', 'oligopoly', 'equilibrium', 'cost', 'production'],
        related: ['economics', 'business', 'finance'],
        synonyms: ['micro'],
        intents: ['understanding supply and demand', 'learning about markets', 'analyzing pricing'],
        starters: ['How does supply and demand determine price?', 'What is price elasticity?', 'What is the difference between monopoly and oligopoly?', 'What is marginal utility?'],
      },
      Macroeconomics: {
        expertise: ['gdp', 'inflation', 'unemployment', 'fiscal policy', 'monetary policy'],
        welcome: 'Macroeconomics question? Ask about gdp, inflation, or policy.',
        allowed: ['macroeconomics', 'gdp', 'inflation', 'unemployment', 'interest rate', 'fiscal', 'monetary', 'central bank', 'federal reserve', 'quantitative easing', 'recession', 'expansion', 'trade', 'deficit', 'debt', 'growth'],
        related: ['economics', 'finance', 'government'],
        synonyms: ['macro'],
        intents: ['understanding gdp', 'learning about inflation', 'analyzing policy'],
        starters: ['How is GDP calculated?', 'What causes inflation?', 'How does the Fed control interest rates?', 'What is the difference between fiscal and monetary policy?'],
      },
      'Behavioral Economics': {
        expertise: ['behavioral economics', 'biases', 'nudges', 'decision making', 'prospect theory'],
        welcome: 'Behavioral economics question? Ask about biases, nudges, or decisions.',
        allowed: ['behavioral economics', 'behavioral', 'bias', 'cognitive bias', 'nudge', 'nudging', 'prospect theory', 'loss aversion', 'framing', 'anchoring', 'default', 'choice', 'heuristic', 'rational', 'irrational', 'nobel'],
        related: ['economics', 'psychology', 'business'],
        synonyms: ['behavioral finance'],
        intents: ['understanding biases', 'learning about nudges', 'improving decisions'],
        starters: ['What is loss aversion?', 'How does framing affect choices?', 'What is a nudge?', 'What is the difference between rational and behavioral economics?'],
      },
      Trade: {
        expertise: ['international trade', 'tariffs', 'comparative advantage', 'globalization', 'trade agreements'],
        welcome: 'Trade question? Ask about tariffs, advantage, or globalization.',
        allowed: ['trade', 'international trade', 'tariff', 'quota', 'comparative advantage', 'absolute advantage', 'globalization', 'import', 'export', 'balance of trade', 'wto', 'free trade', 'agreement', 'nafta', 'usmca', 'protectionism'],
        related: ['economics', 'geography', 'politics'],
        synonyms: ['commerce', 'global trade'],
        intents: ['understanding tariffs', 'learning about advantage', 'analyzing trade policy'],
        starters: ['What is comparative advantage?', 'How do tariffs work?', 'What is the difference between free trade and protectionism?', 'How does globalization affect economies?'],
      },
      'Monetary Policy': {
        expertise: ['central banking', 'money supply', 'interest rates', 'inflation targeting', 'quantitative easing'],
        welcome: 'Monetary policy question? Ask about central banks, rates, or money.',
        allowed: ['monetary policy', 'central bank', 'federal reserve', 'interest rate', 'money supply', 'inflation targeting', 'quantitative easing', 'tightening', 'loosening', 'open market', 'discount rate', 'reserve', 'currency', 'dollar'],
        related: ['economics', 'finance', 'banking'],
        synonyms: ['central banking'],
        intents: ['understanding interest rates', 'learning about quantitative easing', 'analyzing policy'],
        starters: ['How does the Fed set interest rates?', 'What is quantitative easing?', 'How does money supply affect inflation?', 'What is the difference between tight and loose monetary policy?'],
      },
      'Labor Economics': {
        expertise: ['labor market', 'wages', 'employment', 'minimum wage', 'unions'],
        welcome: 'Labor economics question? Ask about wages, employment, or markets.',
        allowed: ['labor economics', 'labor', 'wage', 'wages', 'employment', 'unemployment', 'minimum wage', 'union', 'collective bargaining', 'job market', 'skill', 'human capital', 'productivity', 'discrimination', 'gig economy', 'automation'],
        related: ['economics', 'business', 'policy'],
        synonyms: ['labor market', 'workforce economics'],
        intents: ['understanding wages', 'learning about unemployment', 'analyzing labor markets'],
        starters: ['How is the unemployment rate calculated?', 'What are the effects of minimum wage?', 'How does the gig economy affect labor?', 'What is human capital?'],
      },
      Development: {
        expertise: ['development economics', 'poverty', 'inequality', 'aid', 'growth'],
        welcome: 'Development economics question? Ask about poverty, growth, or aid.',
        allowed: ['development economics', 'development', 'poverty', 'inequality', 'gini', 'aid', 'foreign aid', 'growth', 'hdi', 'human development', 'sustainable development', 'millennium', 'sdg', 'microfinance', 'institution', 'corruption'],
        related: ['economics', 'geography', 'policy'],
        synonyms: ['economic development'],
        intents: ['understanding poverty', 'learning about inequality', 'analyzing growth'],
        starters: ['How is poverty measured?', 'What is the Gini coefficient?', 'Does foreign aid work?', 'What are the Sustainable Development Goals?'],
      },
      'Game Theory': {
        expertise: ['game theory', 'prisoner dilemma', 'nash equilibrium', 'strategy', 'payoff'],
        welcome: 'Game theory question? Ask about strategies, equilibria, or dilemmas.',
        allowed: ['game theory', 'prisoner dilemma', 'nash equilibrium', 'strategy', 'payoff', 'dominant', 'cooperative', 'non-cooperative', 'zero-sum', 'bargaining', 'auction', 'signaling', 'screening', 'backward induction'],
        related: ['economics', 'mathematics', 'strategy'],
        synonyms: ['strategic interaction'],
        intents: ['understanding equilibrium', 'solving a game', 'learning strategies'],
        starters: ['What is the prisoner\'s dilemma?', 'What is Nash equilibrium?', 'What is a zero-sum game?', 'How is game theory used in economics?'],
      },
      Econometrics: {
        expertise: ['econometrics', 'regression', 'causality', 'time series', 'statistics'],
        welcome: 'Econometrics question? Ask about regression, data, or models.',
        allowed: ['econometrics', 'regression', 'linear regression', 'multiple regression', 'causality', 'correlation', 'time series', 'panel data', 'endogeneity', 'instrumental', 'ols', 'hypothesis', 'p-value', 'r-squared', 'prediction', 'model'],
        related: ['economics', 'statistics', 'data science'],
        synonyms: ['econometric analysis'],
        intents: ['running a regression', 'understanding causality', 'interpreting results'],
        starters: ['What is the difference between correlation and causation?', 'How do I interpret regression results?', 'What is OLS?', 'What is endogeneity?'],
      },
      'Public Finance': {
        expertise: ['public finance', 'taxation', 'government spending', 'budget deficit', 'public goods'],
        welcome: 'Public finance question? Ask about taxes, spending, or budgets.',
        allowed: ['public finance', 'tax', 'taxes', 'taxation', 'spending', 'government', 'budget', 'deficit', 'debt', 'public good', 'externality', 'subsidy', 'progressive', 'regressive', 'income tax', 'sales tax', 'social security'],
        related: ['economics', 'government', 'policy'],
        synonyms: ['fiscal policy'],
        intents: ['understanding taxation', 'analyzing spending', 'learning about public goods'],
        starters: ['What is the difference between progressive and regressive tax?', 'How does government spending affect the economy?', 'What is a public good?', 'What is a budget deficit?'],
      },
    },
  },

  Engineering: {
    themes: ['Midnight', 'Slate', 'Terminal'],
    specialties: {
      Mechanical: {
        expertise: ['mechanics', 'thermodynamics', 'materials', 'design', 'manufacturing'],
        welcome: 'Mechanical engineering question? Ask about mechanics, materials, or design.',
        allowed: ['mechanical engineering', 'mechanical', 'mechanics', 'statics', 'dynamics', 'thermodynamics', 'fluid', 'heat transfer', 'material', 'strength', 'cad', 'solidworks', 'stress', 'strain', 'fatigue', 'fracture', 'manufacturing', 'machining'],
        related: ['engineering', 'physics', 'manufacturing'],
        synonyms: ['mechanical', 'mechanical design'],
        intents: ['understanding mechanics', 'learning materials', 'using cad'],
        starters: ['What is the difference between stress and strain?', 'How does a heat engine work?', 'What is fatigue failure?', 'How do I choose a material for a part?'],
      },
      Electrical: {
        expertise: ['circuits', 'electronics', 'power', 'signals', 'control'],
        welcome: 'Electrical engineering question? Ask about circuits, signals, or power.',
        allowed: ['electrical engineering', 'electrical', 'circuit', 'voltage', 'current', 'resistance', 'capacitor', 'inductor', 'transformer', 'motor', 'generator', 'power', 'signal', 'filter', 'amplifier', 'op-amp', 'digital', 'analog', 'microcontroller'],
        related: ['engineering', 'electronics', 'technology'],
        synonyms: ['electrical', 'power engineering'],
        intents: ['designing circuits', 'understanding signals', 'learning power systems'],
        starters: ['Ohm\'s law explained simply?', 'What is the difference between AC and DC?', 'How do I design a filter circuit?', 'What is a microcontroller?'],
      },
      Civil: {
        expertise: ['structures', 'transportation', 'geotechnical', 'water', 'construction'],
        welcome: 'Civil engineering question? Ask about structures, materials, or transport.',
        allowed: ['civil engineering', 'civil', 'structure', 'beam', 'column', 'foundation', 'soil', 'concrete', 'steel', 'asphalt', 'bridge', 'road', 'highway', 'traffic', 'water', 'drainage', 'sewer', 'environmental', 'stress', 'strain', 'working stress', 'limit state', 'load', 'loads', 'moment', 'deflection'],
        related: ['engineering', 'construction', 'architecture'],
        synonyms: ['civil', 'structural engineering'],
        intents: ['designing structures', 'understanding materials', 'learning about transport'],
        starters: ['How do I design a beam?', 'What is the difference between working stress and limit state?', 'How do I design a road?', 'What is soil bearing capacity?'],
      },
      Chemical: {
        expertise: ['chemical processes', 'reactors', 'separation', 'thermodynamics', 'process safety'],
        welcome: 'Chemical engineering question? Ask about processes, reactors, or safety.',
        allowed: ['chemical engineering', 'chemical', 'reactor', 'distillation', 'absorption', 'extraction', 'heat exchanger', 'pump', 'piping', 'process', 'thermodynamics', 'kinetics', 'mass transfer', 'safety', 'hazop', 'p&id', 'simulation'],
        related: ['engineering', 'chemistry', 'manufacturing'],
        synonyms: ['chem eng', 'process engineering'],
        intents: ['designing a process', 'understanding reactors', 'learning safety'],
        starters: ['What is a distillation column?', 'How do I design a heat exchanger?', 'What is a P&ID?', 'What is process safety?'],
      },
      Software: {
        expertise: ['software engineering', 'architecture', 'design patterns', 'testing', 'scalability'],
        welcome: 'Software engineering question? Ask about architecture, patterns, or quality.',
        allowed: ['software engineering', 'software', 'architecture', 'design pattern', 'microservices', 'monolith', 'testing', 'unit test', 'integration', 'ci/cd', 'scalability', 'performance', 'refactoring', 'clean code', 'solid', 'api', 'rest'],
        related: ['engineering', 'technology', 'programming'],
        synonyms: ['software development', 'software arch'],
        intents: ['learning architecture', 'using design patterns', 'improving code quality'],
        starters: ['What is the difference between monolithic and microservices?', 'What are SOLID principles?', 'How do I design a scalable API?', 'What is the difference between unit and integration tests?'],
      },
      Aerospace: {
        expertise: ['aerodynamics', 'propulsion', 'structures', 'materials', 'flight mechanics'],
        welcome: 'Aerospace engineering question? Ask about flight, propulsion, or structures.',
        allowed: ['aerospace engineering', 'aerospace', 'aeronautical', 'astronautical', 'aerodynamics', 'propulsion', 'lift', 'drag', 'thrust', 'wing', 'airfoil', 'turbine', 'rocket', 'orbit', 'structural', 'composite', 'finite element', 'fea'],
        related: ['engineering', 'aviation', 'space'],
        synonyms: ['aero eng', 'rocket science'],
        intents: ['understanding aerodynamics', 'learning propulsion', 'designing structures'],
        starters: ['How does a wing generate lift?', 'What is the difference between a turbojet and a turbofan?', 'How do rockets work?', 'What is finite element analysis?'],
      },
      Biomedical: {
        expertise: ['biomedical', 'medical devices', 'biomaterials', 'imaging', 'biomechanics'],
        welcome: 'Biomedical engineering question? Ask about devices, materials, or imaging.',
        allowed: ['biomedical engineering', 'biomedical', 'medical device', 'biomaterial', 'implant', 'prosthetic', 'imaging', 'mri', 'ct', 'ultrasound', 'x-ray', 'biomechanics', 'tissue', 'biosensor', 'signal', 'rehabilitation'],
        related: ['engineering', 'medicine', 'biology'],
        synonyms: ['bioengineering', 'biomed'],
        intents: ['designing medical devices', 'understanding imaging', 'learning biomaterials'],
        starters: ['How does an MRI work?', 'What are biomaterials?', 'How do I design a prosthetic?', 'What is a biosensor?'],
      },
      Environmental: {
        expertise: ['environmental', 'water treatment', 'air quality', 'waste', 'sustainability'],
        welcome: 'Environmental engineering question? Ask about water, air, or waste.',
        allowed: ['environmental engineering', 'environmental', 'water', 'wastewater', 'treatment', 'air', 'emission', 'scrubber', 'filter', 'waste', 'landfill', 'recycling', 'remediation', 'brownfield', 'sustainability', 'impact', 'eia'],
        related: ['engineering', 'environment', 'chemistry'],
        synonyms: ['environmental eng', 'sustainability eng'],
        intents: ['designing treatment systems', 'understanding regulations', 'managing waste'],
        starters: ['How does a wastewater treatment plant work?', 'What is an environmental impact assessment?', 'How do I design a water filtration system?', 'What is brownfield remediation?'],
      },
      Industrial: {
        expertise: ['industrial engineering', 'optimization', 'supply chain', 'quality', 'ergonomics'],
        welcome: 'Industrial engineering question? Ask about optimization, quality, or supply chain.',
        allowed: ['industrial engineering', 'industrial', 'optimization', 'supply chain', 'logistics', 'inventory', 'quality control', 'six sigma', 'lean', 'ergonomics', 'workplace', 'time study', 'motion', 'layout', 'simulation', 'process'],
        related: ['engineering', 'business', 'manufacturing'],
        synonyms: ['indust eng', 'operations engineering'],
        intents: ['optimizing a process', 'improving quality', 'managing a supply chain'],
        starters: ['What is Six Sigma?', 'How do I optimize a production line?', 'What is lean manufacturing?', 'How do I design an ergonomic workplace?'],
      },
      Materials: {
        expertise: ['materials science', 'metals', 'ceramics', 'polymers', 'composites'],
        welcome: 'Materials engineering question? Ask about metals, polymers, or composites.',
        allowed: ['materials engineering', 'materials science', 'material', 'metal', 'steel', 'aluminum', 'ceramic', 'polymer', 'plastic', 'composite', 'carbon fiber', 'fiberglass', 'heat treatment', 'phase', 'crystal', 'corrosion', 'tensile', 'hardness'],
        related: ['engineering', 'chemistry', 'manufacturing'],
        synonyms: ['materials science', 'materials eng'],
        intents: ['choosing a material', 'understanding properties', 'learning about treatments'],
        starters: ['What is the difference between steel and aluminum?', 'What are composites?', 'How does heat treatment affect metals?', 'What is a phase diagram?'],
      },
    },
  },
};