// ============================================================
// SCARLET DOMAIN KNOWLEDGE — PART 9
// ============================================================

export const DOMAIN_PART9 = {
  Music: {
    themes: ['Crimson', 'Sunset', 'Mono'],
    specialties: {
      Guitar: {
        expertise: ['guitar', 'chords', 'scales', 'technique', 'tabs'],
        welcome: 'Guitar question? Ask about chords, scales, or technique.',
        allowed: ['guitar', 'acoustic', 'electric', 'chord', 'chords', 'scale', 'scales', 'tab', 'tabs', 'strum', 'pick', 'bend', 'hammer-on', 'pull-off', 'barre', 'power chord', 'riff', 'fret', 'tuning'],
        related: ['music', 'instruments', 'theory'],
        synonyms: ['six string', 'guitar playing'],
        intents: ['learning chords', 'improving technique', 'reading tabs'],
        starters: ['What chords should I learn first?', 'How do I switch chords faster?', 'What is the difference between major and minor scales?', 'How do I read tabs?'],
      },
      Piano: {
        expertise: ['piano', 'keyboard', 'chords', 'technique', 'sight reading'],
        welcome: 'Piano question? Ask about technique, chords, or practice.',
        allowed: ['piano', 'keyboard', 'key', 'chord', 'chords', 'scale', 'scales', 'fingering', 'pedal', 'sight reading', 'arpeggio', 'inversion', 'crescendo', 'metronome', 'grand', 'upright', 'synth'],
        related: ['music', 'instruments', 'theory'],
        synonyms: ['keys', 'piano playing'],
        intents: ['learning piano', 'improving fingering', 'reading music'],
        starters: ['How do I start learning piano?', 'What are chord inversions?', 'How do I improve finger independence?', 'How do I sight read?'],
      },
      Vocals: {
        expertise: ['singing', 'vocal technique', 'breathing', 'range', 'warm-ups'],
        welcome: 'Singing question? Ask about technique, breath, or range.',
        allowed: ['singing', 'vocal', 'voice', 'singer', 'breath', 'breathing', 'diaphragm', 'range', 'pitch', 'vibrato', 'head voice', 'chest voice', 'falsetto', 'warm-up', 'warmups', 'vocal cords'],
        related: ['music', 'performance', 'health'],
        synonyms: ['vocals', 'singing technique'],
        intents: ['improving pitch', 'expanding range', 'warming up'],
        starters: ['How do I sing in tune?', 'How do I expand my vocal range?', 'What is the difference between chest and head voice?', 'How should I warm up?'],
      },
      'Music Theory': {
        expertise: ['theory', 'keys', 'scales', 'harmony', 'rhythm'],
        welcome: 'Music theory question? Ask about keys, scales, or harmony.',
        allowed: ['music theory', 'theory', 'key', 'keys', 'scale', 'scales', 'chord', 'chords', 'harmony', 'melody', 'rhythm', 'time signature', 'tempo', 'interval', 'cadence', 'progression', 'modulation'],
        related: ['music', 'education', 'composition'],
        synonyms: ['theory of music'],
        intents: ['learning theory', 'understanding chords', 'writing progressions'],
        starters: ['What is the circle of fifths?', 'How do chord progressions work?', 'What is a time signature?', 'What are intervals in music?'],
      },
      Production: {
        expertise: ['production', 'daw', 'mixing', 'samples', 'arrangement'],
        welcome: 'Music production question? Ask about DAWs, mixing, or arrangement.',
        allowed: ['music production', 'production', 'producer', 'daw', 'ableton', 'logic', 'fl studio', 'beat', 'sample', 'synth', 'mix', 'mixing', 'master', 'mastering', 'compression', 'eq', 'sidechain', 'arrangement'],
        related: ['music', 'technology', 'audio'],
        synonyms: ['producing', 'beat making'],
        intents: ['learning production', 'mixing a track', 'building beats'],
        starters: ['Which DAW should I use?', 'How do I make beats?', 'How do I mix vocals?', 'What is mastering?'],
      },
      DJing: {
        expertise: ['dj', 'mixing', 'beats', 'equipment', 'transitions'],
        welcome: 'DJ question? Ask about mixing, equipment, or transitions.',
        allowed: ['dj', 'djing', 'mixing', 'beatmatch', 'beat matching', 'transition', 'turntable', 'cdj', 'controller', 'serato', 'rekordbox', 'crossfade', 'loop', 'hot cue', 'bpm', 'set', 'drop'],
        related: ['music', 'performance', 'technology'],
        synonyms: ['deejaying', 'dj mixing'],
        intents: ['learning to dj', 'beatmatching', 'building a set'],
        starters: ['How do I beatmatch?', 'What DJ equipment do I need?', 'How do I build a DJ set?', 'What is a hot cue?'],
      },
      Songwriting: {
        expertise: ['songwriting', 'lyrics', 'hooks', 'structure', 'co-writing'],
        welcome: 'Songwriting question? Ask about lyrics, hooks, or structure.',
        allowed: ['songwriting', 'song', 'lyrics', 'lyric', 'hook', 'chorus', 'verse', 'bridge', 'structure', 'melody', 'co-write', 'co-writing', 'topic', 'rhyme', 'demo', 'songwriter'],
        related: ['music', 'writing', 'creative'],
        synonyms: ['writing songs', 'composition'],
        intents: ['writing lyrics', 'building structure', 'finding hooks'],
        starters: ['How do I write lyrics?', 'What is the structure of a pop song?', 'How do I write a catchy hook?', 'How do I overcome writer block?'],
      },
      'Music History': {
        expertise: ['music history', 'eras', 'composers', 'genres', 'movements'],
        welcome: 'Music history question? Ask about eras, composers, or movements.',
        allowed: ['music history', 'history', 'composer', 'mozart', 'beethoven', 'bach', 'classical', 'baroque', 'romantic', 'jazz age', 'rock and roll', 'beatles', 'motown', 'punk', 'grunge', 'musicology'],
        related: ['music', 'history', 'culture'],
        synonyms: ['musicology', 'musical history'],
        intents: ['learning about composers', 'understanding eras', 'studying genres'],
        starters: ['What is the difference between Baroque and Classical?', 'How did jazz start?', 'Who are the greatest composers?', 'How did rock and roll evolve?'],
      },
      'Audio Engineering': {
        expertise: ['audio engineering', 'recording', 'microphones', 'mixing', 'mastering'],
        welcome: 'Audio engineering question? Ask about mics, recording, or mixing.',
        allowed: ['audio engineering', 'audio', 'recording', 'studio', 'microphone', 'mic', 'condenser', 'dynamic', 'interface', 'preamp', 'mixer', 'monitor', 'headphones', 'acoustics', 'mixing', 'mastering', 'gain staging'],
        related: ['music', 'technology', 'engineering'],
        synonyms: ['sound engineering', 'recording engineer'],
        intents: ['recording vocals', 'setting up a studio', 'learning mixing'],
        starters: ['How do I set up a home studio?', 'What is the difference between condenser and dynamic mics?', 'How do I treat a room for recording?', 'What is gain staging?'],
      },
      'Music Business': {
        expertise: ['music business', 'royalties', 'streaming', 'contracts', 'distribution'],
        welcome: 'Music business question? Ask about royalties, contracts, or streaming.',
        allowed: ['music business', 'business', 'royalty', 'royalties', 'streaming', 'spotify', 'apple music', 'distribution', 'distributor', 'label', 'contract', 'publishing', 'sync', 'license', 'merch', 'touring'],
        related: ['music', 'business', 'law'],
        synonyms: ['music industry', 'music industry business'],
        intents: ['understanding royalties', 'signing contracts', 'distributing music'],
        starters: ['How do streaming royalties work?', 'What is music publishing?', 'Should I sign with a label?', 'How do I distribute my music?'],
        disclaimer: true,
      },
    },
  },

  Philosophy: {
    themes: ['Royal', 'Slate', 'Mono'],
    specialties: {
      Ethics: {
        expertise: ['ethics', 'morality', 'theories', 'dilemmas', 'applied ethics'],
        welcome: 'Ethics question? Ask about theories, dilemmas, or moral problems.',
        allowed: ['ethics', 'moral', 'morality', 'ethical', 'consequentialism', 'utilitarianism', 'deontology', 'virtue', 'kant', 'dilemma', 'right', 'wrong', 'good', 'evil', 'bioethics', 'applied ethics'],
        related: ['philosophy', 'society', 'law'],
        synonyms: ['moral philosophy'],
        intents: ['understanding theories', 'analyzing dilemmas', 'applying ethics'],
        starters: ['What is utilitarianism?', 'What is deontology?', 'What is the trolley problem?', 'What is virtue ethics?'],
      },
      Logic: {
        expertise: ['logic', 'arguments', 'fallacies', 'symbolic logic', 'reasoning'],
        welcome: 'Logic question? Ask about arguments, fallacies, or symbolic logic.',
        allowed: ['logic', 'logical', 'argument', 'premise', 'conclusion', 'fallacy', 'fallacies', 'syllogism', 'deduction', 'induction', 'valid', 'sound', 'proposition', 'modus ponens', 'symbolic logic', 'truth table'],
        related: ['philosophy', 'mathematics', 'science'],
        synonyms: ['logical reasoning', 'formal logic'],
        intents: ['analyzing arguments', 'learning logic', 'spotting fallacies'],
        starters: ['What is a logical fallacy?', 'What is the difference between deduction and induction?', 'How do I construct a valid argument?', 'What is a syllogism?'],
      },
      Metaphysics: {
        expertise: ['metaphysics', 'reality', 'existence', 'causation', 'time'],
        welcome: 'Metaphysics question? Ask about reality, existence, or causation.',
        allowed: ['metaphysics', 'reality', 'existence', 'being', 'ontology', 'causation', 'cause', 'time', 'space', 'identity', 'free will', 'determinism', 'soul', 'mind', 'universe'],
        related: ['philosophy', 'physics', 'religion'],
        synonyms: ['ontology', 'first philosophy'],
        intents: ['understanding reality', 'learning about causation', 'debating free will'],
        starters: ['What is metaphysics?', 'What is the nature of time?', 'Is free will compatible with determinism?', 'What is the mind-body problem?'],
      },
      Epistemology: {
        expertise: ['epistemology', 'knowledge', 'belief', 'justification', 'skepticism'],
        welcome: 'Epistemology question? Ask about knowledge, belief, or justification.',
        allowed: ['epistemology', 'knowledge', 'belief', 'justification', 'truth', 'evidence', 'skepticism', 'doubt', 'rationalism', 'empiricism', 'certainty', 'know', 'perception', 'reliability'],
        related: ['philosophy', 'science', 'psychology'],
        synonyms: ['theory of knowledge'],
        intents: ['understanding knowledge', 'debating skepticism', 'learning rationalism vs empiricism'],
        starters: ['What is justified true belief?', 'What is the difference between rationalism and empiricism?', 'Can we know anything for certain?', 'What is the problem of induction?'],
      },
      'Political Philosophy': {
        expertise: ['political philosophy', 'justice', 'liberty', 'state', 'legitimacy'],
        welcome: 'Political philosophy question? Ask about justice, liberty, or the state.',
        allowed: ['political philosophy', 'justice', 'liberty', 'freedom', 'state', 'government', 'legitimacy', 'contract', 'equality', 'rights', 'sovereignty', 'plato', 'hobbes', 'locke', 'rousseau', 'rawls'],
        related: ['philosophy', 'politics', 'law'],
        synonyms: ['political theory'],
        intents: ['understanding justice', 'learning about the state', 'analyzing rights'],
        starters: ['What is Rawls theory of justice?', 'Why do we need a state?', 'What is the difference between liberty and license?', 'What is the social contract?'],
      },
      Aesthetics: {
        expertise: ['aesthetics', 'beauty', 'art', 'taste', 'theories of art'],
        welcome: 'Aesthetics question? Ask about beauty, art, or taste.',
        allowed: ['aesthetics', 'aesthetic', 'beauty', 'beautiful', 'art', 'taste', 'sublime', 'kant', 'artwork', 'expression', 'representation', 'form', 'appreciation', 'ugly', 'design'],
        related: ['philosophy', 'art', 'design'],
        synonyms: ['philosophy of art'],
        intents: ['understanding beauty', 'analyzing art', 'debating taste'],
        starters: ['What is the philosophy of beauty?', 'What makes something art?', 'Is beauty objective or subjective?', 'What is the sublime?'],
      },
      Existentialism: {
        expertise: ['existentialism', 'meaning', 'freedom', 'angst', 'authenticity'],
        welcome: 'Existentialism question? Ask about meaning, freedom, or authenticity.',
        allowed: ['existentialism', 'existential', 'meaning', 'meaningless', 'freedom', 'choice', 'authenticity', 'angst', 'absurd', 'nothingness', 'sartre', 'camus', 'kierkegaard', 'nietzsche', 'abandonment'],
        related: ['philosophy', 'literature', 'psychology'],
        synonyms: ['existential philosophy'],
        intents: ['understanding existence', 'debating meaning', 'studying existentialists'],
        starters: ['What is existentialism?', 'What does "existence precedes essence" mean?', 'What is the absurd?', 'How do existentialists view freedom?'],
      },
      Stoicism: {
        expertise: ['stoicism', 'virtue', 'control', 'emotions', 'practice'],
        welcome: 'Stoicism question? Ask about virtues, control, or practices.',
        allowed: ['stoicism', 'stoic', 'stoics', 'virtue', 'wisdom', 'courage', 'justice', 'temperance', 'control', 'dichotomy of control', 'emotion', 'impression', 'judgment', 'marcus aurelius', 'seneca', 'epictetus', 'negative visualization'],
        related: ['philosophy', 'psychology', 'self-help'],
        synonyms: ['stoic philosophy'],
        intents: ['learning stoicism', 'practicing virtue', 'managing emotions'],
        starters: ['What is the dichotomy of control?', 'Who were the famous Stoics?', 'How do I practice Stoicism daily?', 'What is negative visualization?'],
      },
      'Eastern Philosophy': {
        expertise: ['eastern philosophy', 'buddhism', 'hinduism', 'taoism', 'confucianism'],
        welcome: 'Eastern philosophy question? Ask about Buddhism, Taoism, or Confucianism.',
        allowed: ['eastern philosophy', 'buddhism', 'buddhist', 'hinduism', 'hindu', 'taoism', 'tao', 'dao', 'confucianism', 'confucius', 'zen', 'karma', 'dharma', 'nirvana', 'samsara', 'wu wei', 'yin yang', 'meditation'],
        related: ['philosophy', 'religion', 'culture'],
        synonyms: ['oriental philosophy', 'asian philosophy'],
        intents: ['learning traditions', 'understanding concepts', 'practicing mindfulness'],
        starters: ['What is the Four Noble Truths?', 'What is Wu Wei?', 'What is the difference between karma and dharma?', 'What is Zen Buddhism?'],
      },
      'Philosophy of Mind': {
        expertise: ['philosophy of mind', 'consciousness', 'mind-body', 'qualia', 'intentionality'],
        welcome: 'Philosophy of mind question? Ask about consciousness, mind, or the self.',
        allowed: ['philosophy of mind', 'mind', 'consciousness', 'conscious', 'mind-body', 'dualism', 'materialism', 'qualia', 'intentionality', 'self', 'personhood', 'zombie', 'artificial intelligence', 'thought'],
        related: ['philosophy', 'psychology', 'neuroscience'],
        synonyms: ['philosophy of consciousness'],
        intents: ['understanding consciousness', 'debating dualism', 'analyzing the self'],
        starters: ['What is the hard problem of consciousness?', 'What is dualism vs materialism?', 'What is qualia?', 'Could an AI be conscious?'],
      },
    },
  },

  Photography: {
    themes: ['Mono', 'Slate', 'Sunset'],
    specialties: {
      Portrait: {
        expertise: ['portrait photography', 'posing', 'lighting', 'lenses', 'editing'],
        welcome: 'Portrait photography question? Ask about posing, lighting, or lenses.',
        allowed: ['portrait', 'portraits', 'portrait photography', 'posing', 'pose', 'headshot', 'lighting', 'rim light', 'key light', 'lens', '85mm', 'bokeh', 'eye contact', 'expression', 'retouch', 'backdrop'],
        related: ['photography', 'people', 'studio'],
        synonyms: ['people photography', 'headshots'],
        intents: ['improving portraits', 'posing subjects', 'lighting portraits'],
        starters: ['How do I pose a subject?', 'What lens is best for portraits?', 'How do I light a portrait?', 'How do I get creamy bokeh?'],
      },
      Landscape: {
        expertise: ['landscape photography', 'composition', 'filters', 'golden hour', 'editing'],
        welcome: 'Landscape photography question? Ask about composition, filters, or timing.',
        allowed: ['landscape', 'landscape photography', 'nature', 'golden hour', 'blue hour', 'sunrise', 'sunset', 'tripod', 'filter', 'nd filter', 'graduated', 'composition', 'foreground', 'leading lines', 'long exposure', 'panorama'],
        related: ['photography', 'nature', 'travel'],
        synonyms: ['nature photography', 'scenery'],
        intents: ['improving composition', 'using filters', 'planning shoots'],
        starters: ['When is the best time to shoot landscapes?', 'What ND filter should I use?', 'How do I compose a landscape?', 'How do I take long exposures?'],
      },
      Street: {
        expertise: ['street photography', 'candid', 'decisive moment', 'ethics', 'composition'],
        welcome: 'Street photography question? Ask about candid, composition, or ethics.',
        allowed: ['street', 'street photography', 'candid', 'decisive moment', 'documentary', 'city', 'people', 'public', 'ethics', 'permission', 'grain', 'bw', 'black and white', 'juxtaposition', 'minimal'],
        related: ['photography', 'society', 'art'],
        synonyms: ['candid photography'],
        intents: ['shooting street', 'overcoming fear', 'editing street photos'],
        starters: ['How do I get started with street photography?', 'How do I photograph strangers?', 'What makes a strong street photo?', 'Color or black and white for street?'],
      },
      Wildlife: {
        expertise: ['wildlife photography', 'telephoto', 'behavior', 'fieldcraft', 'safety'],
        welcome: 'Wildlife photography question? Ask about lenses, behavior, or fieldcraft.',
        allowed: ['wildlife', 'wildlife photography', 'animal', 'bird', 'telephoto', 'lens', 'camouflage', 'hide', 'blind', 'fieldcraft', 'behavior', 'burst', 'autofocus', 'eye', 'safari', 'national park'],
        related: ['photography', 'nature', 'conservation'],
        synonyms: ['animal photography'],
        intents: ['choosing gear', 'photographing birds', 'improving fieldcraft'],
        starters: ['What lens do I need for wildlife?', 'How do I photograph birds in flight?', 'What is fieldcraft?', 'How do I approach wild animals safely?'],
      },
      Product: {
        expertise: ['product photography', 'studio', 'lighting', 'props', 'editing'],
        welcome: 'Product photography question? Ask about lighting, setup, or editing.',
        allowed: ['product', 'product photography', 'ecommerce', 'studio', 'lightbox', 'lighting', 'softbox', 'reflector', 'prop', 'background', 'white background', 'shadow', 'cutout', '360', 'macro', 'tabletop'],
        related: ['photography', 'ecommerce', 'design'],
        synonyms: ['commercial photography', 'e-commerce photos'],
        intents: ['shooting products', 'setting up a studio', 'editing product shots'],
        starters: ['How do I photograph products with a white background?', 'What lighting do I need for product photography?', 'How do I do a 360 product shot?', 'How do I edit product photos?'],
      },
      Wedding: {
        expertise: ['wedding photography', 'coverage', 'timeline', 'portraits', 'gear'],
        welcome: 'Wedding photography question? Ask about coverage, timelines, or gear.',
        allowed: ['wedding', 'wedding photography', 'ceremony', 'reception', 'bride', 'groom', 'timeline', 'shot list', 'portrait', 'candid', 'flash', 'off-camera', 'second shooter', 'couple', 'album'],
        related: ['photography', 'events', 'business'],
        synonyms: ['wedding coverage', 'bridal photography'],
        intents: ['planning coverage', 'shooting weddings', 'building a portfolio'],
        starters: ['How do I start shooting weddings?', 'What is on a wedding shot list?', 'How do I handle low-light at receptions?', 'Should I hire a second shooter?'],
      },
      Astrophotography: {
        expertise: ['astrophotography', 'night sky', 'milky way', 'tracking', 'stacking'],
        welcome: 'Astrophotography question? Ask about night sky, tracking, or stacking.',
        allowed: ['astrophotography', 'astro', 'night sky', 'milky way', 'star', 'stars', 'tracking', 'tracker', 'stacking', 'stack', 'long exposure', 'star trails', 'moon', 'northern lights', 'aurora', 'dark sky'],
        related: ['photography', 'astronomy', 'space'],
        synonyms: ['night photography', 'sky photography'],
        intents: ['shooting the milky way', 'learning stacking', 'finding dark skies'],
        starters: ['How do I photograph the Milky Way?', 'What gear do I need for astrophotography?', 'What is stacking?', 'How do I find a dark sky site?'],
      },
      Editing: {
        expertise: ['photo editing', 'lightroom', 'photoshop', 'color', 'retouching'],
        welcome: 'Photo editing question? Ask about tools, color, or retouching.',
        allowed: ['editing', 'photo editing', 'lightroom', 'photoshop', 'capture one', 'color grading', 'white balance', 'exposure', 'curves', 'mask', 'retouch', 'heal', 'clone', 'preset', 'crop', 'sharpening'],
        related: ['photography', 'design', 'technology'],
        synonyms: ['post-processing', 'retouching'],
        intents: ['editing photos', 'learning lightroom', 'retouching portraits'],
        starters: ['How do I edit in Lightroom?', 'What is color grading?', 'How do I retouch a portrait?', 'What is the difference between layers and masks?'],
      },
      Composition: {
        expertise: ['composition', 'rule of thirds', 'framing', 'balance', 'perspective'],
        welcome: 'Composition question? Ask about rules, framing, or balance.',
        allowed: ['composition', 'rule of thirds', 'framing', 'balance', 'symmetry', 'leading lines', 'negative space', 'perspective', 'angle', 'depth', 'layering', 'golden ratio', 'diagonal', 'foreground', 'cropping'],
        related: ['photography', 'design', 'art'],
        synonyms: ['framing', 'photographic composition'],
        intents: ['learning rules', 'breaking rules', 'improving framing'],
        starters: ['What is the rule of thirds?', 'When should I break composition rules?', 'What is negative space?', 'How do I use leading lines?'],
      },
      Lighting: {
        expertise: ['photography lighting', 'natural light', 'flash', 'modifiers', 'ratio'],
        welcome: 'Lighting question? Ask about natural light, flash, or modifiers.',
        allowed: ['lighting', 'light', 'natural light', 'golden hour', 'flash', 'speedlight', 'strobes', 'softbox', 'umbrella', 'reflector', 'diffuser', 'hard light', 'soft light', 'ratio', 'key light', 'fill light', 'rim'],
        related: ['photography', 'studio', 'art'],
        synonyms: ['light science', 'photographic lighting'],
        intents: ['using natural light', 'learning flash', 'shaping light'],
        starters: ['How do I use natural light?', 'On-camera vs off-camera flash?', 'What is a softbox?', 'What is the light ratio?'],
      },
    },
  },

  Psychology: {
    themes: ['Royal', 'Ocean', 'Mono'],
    specialties: {
      Cognitive: {
        expertise: ['cognition', 'memory', 'attention', 'perception', 'problem solving'],
        welcome: 'Cognitive psychology question? Ask about memory, attention, or perception.',
        allowed: ['cognitive psychology', 'cognition', 'memory', 'attention', 'perception', 'language', 'thinking', 'problem solving', 'decision making', 'cognitive load', 'working memory', 'long-term', 'retrieval', 'bias'],
        related: ['psychology', 'neuroscience', 'education'],
        synonyms: ['cognitive science'],
        intents: ['understanding memory', 'improving attention', 'learning about bias'],
        starters: ['How does working memory work?', 'What is cognitive load?', 'How do cognitive biases affect decisions?', 'What is the primacy effect?'],
      },
      Clinical: {
        expertise: ['clinical psychology', 'disorders', 'assessment', 'therapy', 'diagnosis'],
        welcome: 'Clinical psychology question? Ask about assessment, therapy, or disorders.',
        allowed: ['clinical psychology', 'clinical', 'disorder', 'depression', 'anxiety', 'ptsd', 'ocd', 'bipolar', 'assessment', 'diagnosis', 'dsm', 'therapy', 'cbt', 'cognitive behavioral', 'psychotherapy', 'intervention'],
        related: ['psychology', 'mental health', 'medicine'],
        synonyms: ['mental health psychology'],
        intents: ['understanding disorders', 'learning therapies', 'knowing assessment'],
        starters: ['What is CBT?', 'What is the difference between OCD and anxiety?', 'How are psychological disorders diagnosed?', 'What is the DSM?'],
        disclaimer: true,
      },
      Social: {
        expertise: ['social psychology', 'attitudes', 'conformity', 'group dynamics', 'persuasion'],
        welcome: 'Social psychology question? Ask about attitudes, conformity, or groups.',
        allowed: ['social psychology', 'social', 'attitude', 'conformity', 'obedience', 'group', 'groupthink', 'prejudice', 'stereotype', 'persuasion', 'cognitive dissonance', 'bystander effect', 'attribution', 'norms'],
        related: ['psychology', 'society', 'sociology'],
        synonyms: ['group psychology'],
        intents: ['understanding conformity', 'learning about bias', 'analyzing groups'],
        starters: ['What is cognitive dissonance?', 'Why do people conform?', 'What is the bystander effect?', 'What is groupthink?'],
      },
      Developmental: {
        expertise: ['development', 'childhood', 'adolescence', 'aging', 'stages'],
        welcome: 'Developmental psychology question? Ask about stages, childhood, or aging.',
        allowed: ['developmental psychology', 'development', 'child', 'children', 'infant', 'adolescent', 'teen', 'aging', 'elderly', 'piaget', 'erikson', 'attachment', 'stage', 'milestone', 'language development', 'moral development'],
        related: ['psychology', 'education', 'family'],
        synonyms: ['human development'],
        intents: ['understanding stages', 'learning attachment', 'studying aging'],
        starters: ['What are Piaget stages?', 'What is attachment theory?', 'How does language develop?', 'What is Erikson theory?'],
      },
      Behavioral: {
        expertise: ['behaviorism', 'conditioning', 'reinforcement', 'habits', 'behavior change'],
        welcome: 'Behavioral psychology question? Ask about conditioning, habits, or change.',
        allowed: ['behavioral psychology', 'behavior', 'behaviorism', 'pavlov', 'skinner', 'classical conditioning', 'operant conditioning', 'reinforcement', 'punishment', 'habit', 'behavior change', 'extinction', 'stimulus', 'response'],
        related: ['psychology', 'education', 'fitness'],
        synonyms: ['behaviorism', 'learning theory'],
        intents: ['building habits', 'changing behavior', 'understanding conditioning'],
        starters: ['What is classical vs operant conditioning?', 'How do I build a habit?', 'What is reinforcement?', 'How do I break a bad habit?'],
      },
      Neuropsychology: {
        expertise: ['neuropsychology', 'brain', 'lesions', 'assessment', 'disorders'],
        welcome: 'Neuropsychology question? Ask about the brain, assessment, or disorders.',
        allowed: ['neuropsychology', 'neuro', 'brain', 'lobe', 'frontal', 'temporal', 'lesion', 'damage', 'assessment', 'cognitive test', 'aphasia', 'amnesia', 'neglect', 'stroke', 'dementia'],
        related: ['psychology', 'neuroscience', 'medicine'],
        synonyms: ['brain-behavior psychology'],
        intents: ['understanding the brain', 'learning assessments', 'studying brain damage'],
        starters: ['What is aphasia?', 'What does the frontal lobe do?', 'How is neuropsychology assessed?', 'What happens after a stroke?'],
        disclaimer: true,
      },
      'Positive Psychology': {
        expertise: ['positive psychology', 'happiness', 'flourishing', 'strengths', 'wellbeing'],
        welcome: 'Positive psychology question? Ask about happiness, strengths, or flourishing.',
        allowed: ['positive psychology', 'happiness', 'happy', 'flourishing', 'strengths', 'signature strengths', 'gratitude', 'optimism', 'resilience', 'flow', 'wellbeing', 'well-being', 'meaning', 'seligman'],
        related: ['psychology', 'wellness', 'self-help'],
        synonyms: ['science of happiness'],
        intents: ['increasing happiness', 'building resilience', 'finding strengths'],
        starters: ['What is positive psychology?', 'How do I build resilience?', 'What is the PERMA model?', 'How does gratitude work?'],
      },
      Therapy: {
        expertise: ['therapy', 'counseling', 'modalities', 'therapeutic relationship', 'techniques'],
        welcome: 'Therapy question? Ask about modalities, techniques, or finding a therapist.',
        allowed: ['therapy', 'therapist', 'counseling', 'counselling', 'cbt', 'dbt', 'psychodynamic', 'humanistic', 'gestalt', 'exposure', 'mindfulness-based', 'therapeutic', 'session', 'modality', 'telehealth'],
        related: ['psychology', 'mental health', 'wellness'],
        synonyms: ['psychotherapy', 'counseling'],
        intents: ['choosing a modality', 'finding a therapist', 'learning techniques'],
        starters: ['What is the difference between CBT and DBT?', 'How do I find a good therapist?', 'What happens in a first therapy session?', 'What is exposure therapy?'],
        disclaimer: true,
      },
      'Research Methods': {
        expertise: ['research methods', 'experiments', 'correlation', 'validity', 'statistics'],
        welcome: 'Psychology research question? Ask about methods, design, or statistics.',
        allowed: ['research methods', 'research', 'experiment', 'study', 'correlation', 'causation', 'independent variable', 'dependent variable', 'validity', 'reliability', 'random assignment', 'sample', 'effect size', 'meta-analysis', 'replication'],
        related: ['psychology', 'statistics', 'science'],
        synonyms: ['psychological research'],
        intents: ['designing a study', 'understanding statistics', 'evaluating research'],
        starters: ['What is the difference between correlation and causation?', 'How do I design an experiment?', 'What is effect size?', 'What is a meta-analysis?'],
      },
      'Emotional Intelligence': {
        expertise: ['emotional intelligence', 'emotions', 'self-awareness', 'empathy', 'regulation'],
        welcome: 'Emotional intelligence question? Ask about emotions, empathy, or regulation.',
        allowed: ['emotional intelligence', 'eq', 'emotion', 'emotions', 'self-awareness', 'empathy', 'regulation', 'managing emotions', 'social skills', 'motivation', 'recognize', 'express', 'goleman'],
        related: ['psychology', 'leadership', 'wellness'],
        synonyms: ['eq', 'emotional quotient'],
        intents: ['improving eq', 'managing emotions', 'building empathy'],
        starters: ['What is emotional intelligence?', 'How do I manage difficult emotions?', 'What is empathy vs sympathy?', 'How do I improve my EQ?'],
      },
    },
  },
};