// ============================================================
// SCARLET DOMAIN KNOWLEDGE — PART 7
// ============================================================

export const DOMAIN_PART7 = {
  Journalism: {
    themes: ['Mono', 'Slate', 'Royal'],
    specialties: {
      'News Writing': {
        expertise: ['news writing', 'inverted pyramid', 'lede', 'sourcing', 'accuracy'],
        welcome: 'News writing question? Ask about structure, sourcing, or style.',
        allowed: ['news', 'news writing', 'journalism', 'inverted pyramid', 'lede', 'headline', 'source', 'sourcing', 'fact', 'fact-checking', 'objectivity', 'bias', 'quote', 'attribution', 'wire', 'breaking'],
        related: ['journalism', 'media', 'writing'],
        synonyms: ['reporting', 'news reporting'],
        intents: ['writing a news article', 'understanding structure', 'practicing ethics'],
        starters: ['What is the inverted pyramid?', 'How do I write a strong lede?', 'How do I attribute quotes?', 'What makes a good headline?'],
      },
      'Investigative Journalism': {
        expertise: ['investigative journalism', 'interviews', 'documents', 'data', 'accountability'],
        welcome: 'Investigative journalism question? Ask about techniques, sources, or structure.',
        allowed: ['investigative', 'investigation', 'investigative journalism', 'document', 'foia', 'public records', 'whistleblower', 'source protection', 'interview', 'evidence', 'accountability', 'expose', 'deep dive', 'analysis'],
        related: ['journalism', 'law', 'media'],
        synonyms: ['watchdog journalism', 'muckraking'],
        intents: ['planning an investigation', 'protecting sources', 'structuring a story'],
        starters: ['How do I start an investigation?', 'How do I protect confidential sources?', 'What is a FOIA request?', 'How do I structure an investigative piece?'],
      },
      Broadcast: {
        expertise: ['broadcast journalism', 'tv news', 'packages', 'live reporting', 'production'],
        welcome: 'Broadcast journalism question? Ask about packages, live, or production.',
        allowed: ['broadcast', 'television', 'tv news', 'package', 'standup', 'live', 'anchor', 'reporter', 'script', 'soundbite', 'b-roll', 'gfx', 'teleprompter', 'control room', 'air', 'segment'],
        related: ['journalism', 'media', 'video'],
        synonyms: ['tv journalism', 'on-air reporting'],
        intents: ['writing for broadcast', 'shooting a package', 'going live'],
        starters: ['How do I write for broadcast?', 'What is a standup?', 'How do I structure a TV news package?', 'What makes a good soundbite?'],
      },
      Photojournalism: {
        expertise: ['photojournalism', 'photography', 'ethics', 'captions', 'news images'],
        welcome: 'Photojournalism question? Ask about technique, ethics, or captions.',
        allowed: ['photojournalism', 'photography', 'photo', 'news photo', 'caption', 'composition', 'decisive moment', 'ethics', 'manipulation', 'authenticity', 'portrait', 'protest', 'war photography', 'edit', 'permissions'],
        related: ['journalism', 'photography', 'media'],
        synonyms: ['news photography', 'photo reportage'],
        intents: ['improving photos', 'writing captions', 'navigating ethics'],
        starters: ['How do I improve news photography?', 'What are the ethics of photo editing?', 'How do I write a caption?', 'How do I cover protests safely?'],
      },
      'Digital Media': {
        expertise: ['digital media', 'websites', 'seo', 'social distribution', 'analytics'],
        welcome: 'Digital media question? Ask about platforms, seo, or distribution.',
        allowed: ['digital media', 'digital', 'website', 'seo', 'search', 'social media', 'facebook', 'instagram', 'tiktok', 'youtube', 'newsletter', 'subscription', 'paywall', 'analytics', 'traffic', 'engagement', 'algorithm'],
        related: ['journalism', 'technology', 'marketing'],
        synonyms: ['online media', 'new media'],
        intents: ['growing audience', 'understanding seo', 'analyzing traffic'],
        starters: ['How do I grow a digital audience?', 'What is SEO for news?', 'How do paywalls work?', 'How do algorithms distribute news?'],
      },
      Ethics: {
        expertise: ['journalism ethics', 'codes', 'conflict of interest', 'privacy', 'accuracy'],
        welcome: 'Journalism ethics question? Ask about codes, conflicts, or privacy.',
        allowed: ['journalism ethics', 'ethics', 'code', 'spj', 'conflict of interest', 'privacy', 'accuracy', 'fairness', 'independence', 'plagiarism', 'disclosure', 'correction', 'embargo', 'off the record'],
        related: ['journalism', 'law', 'media'],
        synonyms: ['media ethics', 'news ethics'],
        intents: ['understanding codes', 'navigating conflicts', 'handling corrections'],
        starters: ['What is the SPJ code of ethics?', 'How do I handle a conflict of interest?', 'What does "off the record" mean?', 'How do I issue a correction?'],
      },
      Editing: {
        expertise: ['editing', 'copy editing', 'headlines', 'style', 'structure'],
        welcome: 'Editing question? Ask about copy, headlines, or structure.',
        allowed: ['editing', 'editor', 'copy editing', 'copyediting', 'headline', 'style', 'ap style', 'structure', 'cut', 'trim', 'revision', 'grammar', 'clarity', 'lede', 'fact-check', 'assignment'],
        related: ['journalism', 'writing', 'publishing'],
        synonyms: ['copyediting', 'newsroom editing'],
        intents: ['improving editing', 'writing headlines', 'using style guides'],
        starters: ['What is AP style?', 'How do I write a headline?', 'How do I edit a story for clarity?', 'What does a copy editor do?'],
      },
      'Sports Journalism': {
        expertise: ['sports journalism', 'game coverage', 'analysis', 'interviews', 'features'],
        welcome: 'Sports journalism question? Ask about coverage, analysis, or features.',
        allowed: ['sports journalism', 'sports', 'game recap', 'recap', 'analysis', 'stats', 'interview', 'locker room', 'feature', 'column', 'commentary', 'score', 'draft', 'trade', 'season'],
        related: ['journalism', 'sports', 'media'],
        synonyms: ['sportswriting', 'sports reporting'],
        intents: ['covering games', 'writing analysis', 'conducting interviews'],
        starters: ['How do I write a game recap?', 'How do I interview athletes?', 'What makes a good sports column?', 'How do I use stats in sports writing?'],
      },
      'Political Reporting': {
        expertise: ['political reporting', 'campaigns', 'government', 'interviews', 'fact-checking'],
        welcome: 'Political reporting question? Ask about campaigns, coverage, or fact-checking.',
        allowed: ['political reporting', 'politics', 'campaign', 'election', 'government', 'policy', 'interview', 'debate', 'fact-check', 'spin', 'press conference', 'poll', 'briefing', 'congress', 'parliament'],
        related: ['journalism', 'politics', 'government'],
        synonyms: ['politics journalism', 'political coverage'],
        intents: ['covering campaigns', 'interviewing politicians', 'fact-checking'],
        starters: ['How do I cover a campaign?', 'How do I interview a politician?', 'What is spin?', 'How do I fact-check political claims?'],
      },
      'Data Journalism': {
        expertise: ['data journalism', 'data analysis', 'visualization', 'databases', 'stories'],
        welcome: 'Data journalism question? Ask about analysis, tools, or visualization.',
        allowed: ['data journalism', 'data', 'dataset', 'analysis', 'excel', 'python', 'r', 'pandas', 'visualization', 'chart', 'infographic', 'mapping', 'scrape', 'api', 'database', 'trend'],
        related: ['journalism', 'data science', 'technology'],
        synonyms: ['computational journalism'],
        intents: ['analyzing data', 'building visualizations', 'finding stories in data'],
        starters: ['How do I start with data journalism?', 'What tools do data journalists use?', 'How do I find stories in data?', 'How do I build an infographic?'],
      },
    },
  },

  'Logistics & Supply Chain': {
    themes: ['Mono', 'Midnight', 'Amber'],
    specialties: {
      Warehousing: {
        expertise: ['warehouse operations', 'layout', 'picking', 'packing', 'storage'],
        welcome: 'Warehousing question? Ask about operations, layout, or picking.',
        allowed: ['warehouse', 'warehousing', 'storage', 'layout', 'shelf', 'pallet', 'racking', 'picking', 'packing', 'shipping', 'receiving', 'inventory', 'wms', 'forklift', 'dock', 'slotting', 'throughput'],
        related: ['logistics', 'supply chain', 'operations'],
        synonyms: ['fulfillment center', 'distribution center'],
        intents: ['improving picking', 'designing layout', 'managing inventory'],
        starters: ['How do I optimize warehouse layout?', 'What is slotting?', 'How do I improve picking accuracy?', 'What is a WMS?'],
      },
      Shipping: {
        expertise: ['shipping', 'freight', 'ocean', 'air', 'parcels'],
        welcome: 'Shipping question? Ask about freight, methods, or costs.',
        allowed: ['shipping', 'freight', 'ocean freight', 'air freight', 'parcel', 'package', 'delivery', 'carrier', 'dhl', 'ups', 'fedex', 'usps', 'container', 'fcl', 'lcl', 'incoterm', 'customs', 'bill of lading'],
        related: ['logistics', 'supply chain', 'trade'],
        synonyms: ['freight forwarding', 'transportation'],
        intents: ['choosing a carrier', 'understanding incoterms', 'reducing costs'],
        starters: ['What are Incoterms?', 'Air vs ocean freight — which should I choose?', 'How do I reduce shipping costs?', 'What is a bill of lading?'],
      },
      Inventory: {
        expertise: ['inventory management', 'stock', 'forecasting', 'abc analysis', 'optimization'],
        welcome: 'Inventory question? Ask about management, forecasting, or optimization.',
        allowed: ['inventory', 'stock', 'reorder', 'safety stock', 'forecast', 'forecasting', 'abc', 'cycle count', 'sku', 'turnover', 'shrinkage', 'par', 'replenishment', 'obsolete', 'demand'],
        related: ['logistics', 'supply chain', 'retail'],
        synonyms: ['stock management', 'stock control'],
        intents: ['reducing stockouts', 'forecasting demand', 'managing inventory'],
        starters: ['How do I calculate safety stock?', 'What is ABC analysis?', 'How do I reduce inventory costs?', 'What is inventory turnover?'],
      },
      Procurement: {
        expertise: ['procurement', 'sourcing', 'vendors', 'negotiation', 'purchasing'],
        welcome: 'Procurement question? Ask about sourcing, vendors, or negotiation.',
        allowed: ['procurement', 'sourcing', 'vendor', 'supplier', 'purchase', 'purchasing', 'rfp', 'rfq', 'negotiation', 'contract', 'spend', 'category', 'e-procurement', 'po', 'quote', 'supplier management'],
        related: ['supply chain', 'business', 'operations'],
        synonyms: ['purchasing', 'buying'],
        intents: ['finding suppliers', 'negotiating contracts', 'managing spend'],
        starters: ['How do I find suppliers?', 'What is an RFP?', 'How do I negotiate with vendors?', 'What is spend analysis?'],
      },
      Distribution: {
        expertise: ['distribution', 'channels', 'network', 'routing', 'last mile'],
        welcome: 'Distribution question? Ask about networks, routing, or channels.',
        allowed: ['distribution', 'channel', 'network', 'routing', 'route', 'hub', 'spoke', 'dc', 'cross-dock', 'delivery', 'last mile', 'carrier', 'warehouse', 'fulfillment', 'coverage'],
        related: ['logistics', 'supply chain', 'operations'],
        synonyms: ['distribution network', 'channel management'],
        intents: ['designing a network', 'optimizing routes', 'managing last mile'],
        starters: ['How do I design a distribution network?', 'What is cross-docking?', 'How do I optimize delivery routes?', 'What is the last-mile problem?'],
      },
      'Fleet Management': {
        expertise: ['fleet management', 'vehicles', 'maintenance', 'fuel', 'tracking'],
        welcome: 'Fleet management question? Ask about vehicles, maintenance, or tracking.',
        allowed: ['fleet', 'fleet management', 'vehicle', 'vehicles', 'truck', 'maintenance', 'fuel', 'gps', 'telematics', 'tracking', 'route', 'driver', 'logs', 'compliance', 'depreciation', 'dispatch'],
        related: ['logistics', 'automotive', 'operations'],
        synonyms: ['vehicle fleet', 'fleet operations'],
        intents: ['managing costs', 'tracking vehicles', 'scheduling maintenance'],
        starters: ['How do I reduce fleet costs?', 'What is telematics?', 'How do I schedule fleet maintenance?', 'How do I optimize routes for a fleet?'],
      },
      'Last Mile': {
        expertise: ['last mile', 'delivery', 'couriers', 'customer experience', 'optimization'],
        welcome: 'Last-mile question? Ask about delivery, couriers, or optimization.',
        allowed: ['last mile', 'delivery', 'courier', 'dispatch', 'route', 'optimization', 'customer', 'time slot', 'proof of delivery', 'pod', 'crowd shipping', 'locker', 'parcel', 'same day', 'returns'],
        related: ['logistics', 'supply chain', 'retail'],
        synonyms: ['final mile', 'delivery operations'],
        intents: ['optimizing delivery', 'reducing cost', 'improving experience'],
        starters: ['How do I reduce last-mile costs?', 'What are delivery time slots?', 'How do I handle returns?', 'What is crowd-sourced delivery?'],
      },
      Freight: {
        expertise: ['freight', 'rates', 'booking', 'containers', 'forwarders'],
        welcome: 'Freight question? Ask about rates, booking, or forwarders.',
        allowed: ['freight', 'rate', 'rates', 'booking', 'container', 'teu', 'feu', 'forwarder', 'broker', 'carrier', 'truckload', 'ltl', 'ftl', 'drayage', 'intermodal', 'transit time', 'freight class'],
        related: ['logistics', 'supply chain', 'trade'],
        synonyms: ['cargo', 'goods transport'],
        intents: ['booking freight', 'comparing rates', 'choosing a forwarder'],
        starters: ['What is the difference between LTL and FTL?', 'How do I book a container?', 'What is drayage?', 'How do freight forwarders work?'],
      },
      'Supply Chain Tech': {
        expertise: ['supply chain technology', 'erp', 'ai', 'iot', 'blockchain'],
        welcome: 'Supply chain tech question? Ask about software, ai, or iot.',
        allowed: ['supply chain technology', 'supply chain', 'erp', 'sap', 'oracle', 'wms', 'tms', 'ai', 'machine learning', 'iot', 'rfid', 'barcode', 'blockchain', 'digital twin', 'visibility', 'automation', 'robotics'],
        related: ['logistics', 'technology', 'supply chain'],
        synonyms: ['scm software', 'digital supply chain'],
        intents: ['choosing software', 'implementing ai', 'improving visibility'],
        starters: ['What is a TMS vs WMS?', 'How is AI used in supply chains?', 'What is RFID?', 'How do I improve supply chain visibility?'],
      },
      'Quality Control': {
        expertise: ['quality control', 'inspection', 'standards', 'defects', 'continuous improvement'],
        welcome: 'Quality control question? Ask about inspection, standards, or improvement.',
        allowed: ['quality control', 'qc', 'quality', 'inspection', 'inspect', 'standard', 'iso', 'defect', 'defective', 'rework', 'scrap', 'samples', 'first article', 'control plan', 'corrective action', 'continuous improvement'],
        related: ['logistics', 'manufacturing', 'operations'],
        synonyms: ['quality assurance', 'qa'],
        intents: ['building qc processes', 'reducing defects', 'implementing standards'],
        starters: ['What is the difference between QA and QC?', 'How do I create a quality checklist?', 'What is ISO 9001?', 'How do I reduce defects?'],
      },
    },
  },
};
