"""{{BOT_NAME_HTML}} - identity, behavior and style of this chatbot.

Generated by the Scarlet Chatbot Factory on every deploy. Edit freely for
local experiments - re-shipping from the factory regenerates this file.
"""

import os

BOT_NAME = {{BOT_NAME_PY}}
DOMAIN = {{DOMAIN_PY}}
SPECIALTY = {{SPECIALTY_PY}}
WELCOME_MESSAGE = {{WELCOME_PY}}
STARTER_QUESTIONS = {{STARTERS_PY}}

GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "{{MODEL_NAME}}")

SYSTEM_PROMPT = {{SYSTEM_PROMPT_PY}}
